### ISSUE TITLE
GitBlog

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#105]
The current blog mechanism we are using in the NodeOS web page based on Jekyll
although flexible, is tedious to write and maintain (compared to Blogger or
WordPress) specially to include images, don't allow comments and it's not
integrated with our current workflow based on GitHub issues. That's why I've
though we could use the GitHub API to create a blog system that use the issues
as engine. This way, we allow to readers to left comments but also we get
notified about them, would not require any maintenance, and making a new blog
entry would be as simple as create a new issue and add a 'blog' tag :-) I think
it would be done as a pure client-side Javascript webapp that does requests to
the GitHub API, but it would be a plus if it would be integrated in Jekyll (at
least by using CSS) so it could be published in GitHub pages :-)

**Comment by piranna** [comment]
Ok, although it's not supported natively, it's also possible to [automatically](http://pipes.yahoo.com/pipes/pipe.info?_id=02bfefe73ba14054570ce82f1929e433) get a [RSS feed](http://pipes.yahoo.com/pipes/pipe.run?_id=02bfefe73ba14054570ce82f1929e433&_render=rss&owner=NodeOS&repo=NodeOS)... :-P

Definitely, this would be a really interesting project... :-)

**Comment by formula1** [comment]
https://gist.github.com/formula1/e4be0a9263da28c59d5a

Heres a very simple gist using angular for a blog based off of github. I was going to do more things, such as using [markdown-js](https://github.com/evilstreak/markdown-js) to display the markdown as well as use async to display eachone one at a time. However, I realized that I needed to host the clientside scripts which I decided against. That being said, built in about an hour and I have to get back to work

**Comment by piranna** [comment]
This is hilarious! :-P Yeah, I supossed it would be an easy and funny hack, but not just one hour! A little bit of CSS and it's ready ;-)

I had in mind other features like a main and a per-post page with comments, but showing only the list and pointing directly to the GitHub issue is a good solution, too. The markdown can be generated by GitHub itself, and in fact [it can render the full posts with internal links to users and other issues](https://developer.github.com/v3/markdown/), so there's no need to include external libraries :-)

It can be easily hosted at [GitHub pages](https://pages.github.com/), that's in fact [how current NodeOS webpage is hosted](https://github.com/NodeOS/nodeos.github.io) ;-) I've tried to publish it with http://gist.io/ but it's broken for new ones like this :-( So in resume: if you convert your gist to a proper GitHub project, anything that goes to a 'gh-pages' branch, or if you create a project with a special name (like the one we are using for NodeOS webpage project), it get's automatically published ;-) There's a lot of projects that host their webpages this way... :-)

I don't know how Jekyll plugins works, too, but I think you are correct. Also, they have the premise that "html is valid Jekyll code" so we could just drop your gist directly on the NodeOS webpage code, but I believe it would be better as a reusable project (at least as an independent project only for the blog engine) so other could fork it and create their own GitHub based blog... :-)

Good job! :-D

**Comment by piranna** [comment]
I've improved the RSS pipe to [include the label](http://pipes.yahoo.com/pipes/pipe.info?_id=d98a965ba7d3f6555b939d707b18dc39), the new RSS feed is http://pipes.yahoo.com/pipes/pipe.run?_id=d98a965ba7d3f6555b939d707b18dc39&_render=rss&label=blog&owner=NodeOS&repo=NodeOS :-) I've also seen that the 'sort' query argument is not neccesary, so I'm not using ig

**Comment by piranna** [comment]
Changing the file name to [index.html](https://gist.github.com/piranna/5b40a7afff28752262fe) and with some quick tune-ups... [here you have it online](http://bl.ocks.org/piranna/raw/5b40a7afff28752262fe/)! :-D

**Comment by formula1** [comment]
I'm getting a 403 with pipes when debbuging : / And now I'm getting 403's with my own page. At some point we're probably going to need to create an API key to avoid this problem.

https://github.com/formula1/NodeOS-Blog

Just created the repo. Also made it look like your website, also handling errors and directing them to submit them to My repo to create an issue. If you run into 403 at some point, you'll know what it looks like.

I'm questioning just hosting the scripts on my server and allowing a Cors request. Of course that can be faked, but Its a bit frustrating how I have no access to browserified modules. Though, It's not 100% necessary.

Amoungst the issues that I have yet to solve are

* [Markdown to HTML](https://github.com/evilstreak/markdown-js) - Github's rate limit causes 403's which is not a happy place to be. By avoiding the markdown parsing, each client may be able to avoid using up more bandwith than needed. Optionally, I can also cache everything on the clients computer and just request things one at a time, though it feels a bit invasive.
* [Highlighting Code](https://github.com/isagalaev/highlight.js)-This is again something simple, however it is code that needs to be hosted somewhere

Something Else I can do is running the requests serverside (again on a different server) and making the Angular base its model off of what that gives back. This will be a slower then just directly getting it from github though.

**Comment by netlovers** [comment]
I think the main problem with this is that google won't find it. So if someone searches for NodeOS blog they'll find the issue list first and not the actual blog, which makes it quite unnecessary to be honest.
Or you have to make the `?_escaped_fragment_=` stuff work too, I'm not sure how much extra work is that with Angular.

**Comment by formula1** [comment]
I thought about the lack of SEO as an issue as well, though I figured build first figure out the rest later. Now adays [google runs javascript](http://googlewebmastercentral.blogspot.no/2014/05/understanding-web-pages-better.html). However, this doesn't make it more SEO friendly, only allows us to be a bit more lazy.  

Should I just build a server and host it on nodejitsu/heroku? The theme isn't that complex and would be able to be converted to any template easily (though obviously jade/blade/etc would require a little more work). This would allow the github app to work without problem, rendering serverside would allow Search Engines to index as they please and etc. It probably won't take more than a few days making the github integration most likely most of the work.

Of course, an operating system's website would be using that operating system to get the feel of real world use cases.

**Comment by piranna** [comment]
> I'm getting a 403 with pipes when debbuging : / And now I'm getting 403's with my own page. At some point we're probably going to need to create an API key to avoid this problem.

Oh, what a shame... :-( I don't know how limits could be gotten, I don't thnk we have use them so much... :-/


> Just created the repo. Also made it look like your website, also handling errors and directing them to submit them to My repo to create an issue. If you run into 403 at some point, you'll know what it looks like.

Cool :-) We can work there or we can move it to NodeOS organization, what do you think?

> I'm questioning just hosting the scripts on my server and allowing a Cors request. Of course that can be faked, but Its a bit frustrating how I have no access to browserified modules. Though, It's not 100% necessary.

This should not be necesary at all using GitHub Pages, that I believe it's the best option for this (and free!!! :-D ), and also probably being served by GitHub itself there's no so restrictive limits or could be found a workaround (they have some repo APIs to have better integration on organization pages...), and if you are thinking about hosting the scripts only for the browserified files, [maybe your google-fu is not as good as my google-fu](https://wzrd.in/)... ;-)


> Markdown to HTML - Github's rate limit causes 403's which is not a happy place to be. By avoiding the markdown parsing, each client may be able to avoid using up more bandwith than needed.

Great :-)


> Optionally, I can also cache everything on the clients computer and just request things one at a time, though it feels a bit invasive.

I don't think is a bad idea, in fact both localStorage and more specially IndexedDB were designed for this purposses :-) Problem is that we are using directly the GitHub API and don't think there's a way to be notified of changes on an issue... :-/ I think that just by rendering markdown on the client (although loosing links to other issues and users) would drop drastically the API usage since will only be needed a request per view.


> Highlighting Code-This is again something simple, however it is code that needs to be hosted somewhere

The same, browserify as a service :-) Other option is to commit the node_modules folder...


> Something Else I can do is running the requests serverside (again on a different server) and making the Angular base its model off of what that gives back. This will be a slower then just directly getting it from github though.

I think a pure client-side solution is possible and just enough, we don't need to deploy (and maintain) our own servers here. Static content (HTML, Javascript...) can be hosted on GitHub Pages or Dropbox, or as I showed you yesterday, as a gist + bl.ocks.io or gist.io to work as proxies, and probably rawgit.com too.


> I think the main problem with this is that google won't find it. So if someone searches for NodeOS blog they'll find the issue list first and not the actual blog, which makes it quite unnecessary to be honest.

I don't think SEO is so important here, since there's only one NodeOS blog and just by the HTML content should be enough to be identified, specially if we link to it from the main page and/or is hosted in the same domain integrated with the current Jekyll web page project (that after @formula1 work, now I think the integration is not need anymore). Only problem would be with the blog post since they disappear and they will be available only as GitHub issues, but since we are mainly moving here at the issues tracker, I think it makes sense (and in fact was one of the points that I though about doing it this way :-P ).

**Comment by piranna** [comment]
> Of course, an operating system's website would be using that operating system to get the feel of real world use cases. But we're probably not there yet

Yeah, this would be a good way to eat our own dog food :-D But we would need to re-enable Docker and network support first, and later find a (free) place where to upload it... :-/

**Comment by formula1** [comment]
> Moving it to NodeOS

I would be honoured for it to be there. Everyone I've met so far here seems like a rockstar and this is a project I earnestly believe in. So if I can stamp my name here I would be glad.

> Just precompiling it

Your google-fu is indeed superior. You win this one.

> gist.io / github pages / hosting it at a proxy

Thinking about it, I could technically avoid gist.io and just grab the [raw content](https://gist.githubusercontent.com/formula1/e4be0a9263da28c59d5a/raw/d59c28d6c0bf5e39511439a9628aee39ec94e81d/blog.html). This would would send `content-type: text/plain` as a header. But most modern browsers don't care so long as you set `<script type="text/javascript" ...`. And even if you don't it will probably interpret it as javascript anyway at least in Chrome/Firefox. But you are correct, gist.io flew by my head as a something much more complex than it had to be. Also, for github pages, if static html is considered a valid jekyll page. Will a text document? Granted, it may send the wrong headers (Most likely `text/html` for jekyll). I suppose, I'm getting snobby about headers when I'm getting stuff for free.

> Moving current blog posts

One thing I considered was sorting the posts by update date. In this manner, you'll be able to choose which is considered "featured". In addition, some blog posts may get updated with new information/etc



I gotta get some sleep, tomarrow.

**Comment by piranna** [comment]
> Moving it to NodeOS
> 
> I would be honoured for it to be there. Everyone I've met so far here seems like a rockstar and this is a project I earnestly believe in. So if I can stamp my name here I would be glad.

Set me as collaborator (or is it owner?) so I have permissions and I'll move it ;-)


> Just precompiling it
> 
> Your google-fu is indeed superior. You win this one.

Not so, just that I remembered about seeing it sometime ago due to work :-P


> gist.io / github pages / hosting it at a proxy
> 
> Thinking about it, I could technically avoid gist.io and just grab the raw content. This would would send content-type: text/plain as a header. But most modern browsers don't care so long as you set <script type="text/javascript" .... And even if you don't it will probably interpret it as javascript anyway at least in Chrome/Firefox. But you are correct, gist.io flew by my head as a something much more complex than it had to be. Also, for github pages, if static html is considered a valid jekyll page. Will a text document? Granted, it may send the wrong headers (Most likely text/html for jekyll). I suppose, I'm getting snobby about headers when I'm getting stuff for free.

Take a look at GitHub Pages. Honestly, for static content is one of the best hosting services you would want: cached, unlimited size, fast delivering, no transfer limits, SSL... and free!!!! :-P NodeOS web page is running there, and my P2P WebRTC serverless webapp was doing it too ;-) Dropbox is a good alternative too but it's more complex to manage for public sites, it's better to see it as an alternative for AWS.


> Moving current blog posts
> 
> One thing I considered was sorting the posts by update date. In this manner, you'll be able to choose which is considered "featured". In addition, some blog posts may get updated with new information/etc

I would like a more traditional publish-date sort, but this could be configurable by user (it's just a parameter on the request). Main problem I have is with the publish date or authoship of old post, but maybe would be a good moment to do a clean-up of outdated info :-)

**Comment by formula1** [comment]
I just updated the blog to make it a little easier for me to work in because a single page started feeling a bit sloppy. https://github.com/formula1/NodeOS-Blog/tree/master

Things Working

* Hello, highlight, markdown are all being browserified (though they were already before) then minified
* I'm compiling the views instead of creating one big html page
* everything gets created when calling `npm start` in `/dist`

Things Untested
* Everything.
* Blog List -> Blog Article
* 403 -> Login

I basically did this just so that I have reasonable files to work within. From here, I'll probably be making my own gitpage for testing purposes. Once everything feels correct. I also still need to incorperate historyjs but I didn't want to over complicate things right away.

**Comment by formula1** [comment]
Quick Update: https://github.com/formula1/NodeOS-Blog/tree/master

I have it working as intended. The markdown is getting parsed, the code is getting highlighted (I think?) and I am able to get issues via `#issueid`

From here...

* Make pictures not look gigantic
* 403 -> Login
* Start testing on github pages + gist

**Comment by piranna** [comment]
> I just updated the blog to make it a little easier for me to work in because a single page started feeling a bit sloppy. https://github.com/formula1/NodeOS-Blog/tree/master

Great :+1: 

I've cloned the repo on NodeOS organization and added you to the webpage team, now you have permissions to push there :-) I've also creted a gh-pages branch from master and renamed blog.html to index.html and it's automagically available at http://node-os.com/NodeOS-Blog (yes, domain too! :-D I think is a feature of GitHub organizations so it's possible to have a main organization page and per-project ones... :-) ). It looks good, so we could start moving the blog entries to GitHub issues and when it's ready just rename the project and have it available as the NodeOS blog (the current one is still available at http://node-os.com/blog, so we could add a redirect).

I think a good idea would be to just rename the project to GitBlog as I proposed, so it can became a generic tool that other can fork and use, while at the same time we can have NodeOS specific things on the gh-pages branch and use it as NodeOS oficial blog, what do you think?

By the way, when doing scroll the post are shown under the top traslucent menu I think it's a bug... but I love it!!! It's cool!!! :-D

P.D.: you are doing an awesome work, thank you! :-)

**Comment by piranna** [comment]
I've just updated project page to use GitBlog, good job @formula1! :-)

**Comment by formula1** [comment]
Thanks @piranna :)

Btw, you have posted in almost every issue I've looked up recently. Including a firefox bug! I thought you were badass before, You are at a new level badass in my eyes now. It's cool to think I'm following in your "bug awareness" footsteps as I enhance my google fu.

I'll tear down my repository so that theres no conflict. It was only up for you to see how I implemented it

**Comment by piranna** [comment]
Well, you should say this to my boss... :-P Also, don't having a life nor a girlfriend helps to achieve this... :-/

**Comment by formula1** [comment]
Aw..... Well, I don't want to hold you back from having a life. We need piranna's in the genepool! Practice makes perfect, understanding the problem well will make things more basic, Fearlessly doing something even when you aren't sure you will succeed also helps. Theres plenty of documentation on how to find a girlfriend/etc. It's all about whether or not thats the path you want to take now. : P
