### ISSUE TITLE
IPFS in the core

### ISSUE THREAD

**Issue by 21xhipster** [NodeOS/NodeOS#109]
NodeOS could be cooler if will be designed in mind with [InterPlanetary File System](https://github.com/jbenet/ipfs). There is embryo [Node implementation](https://github.com/jbenet/node-ipfs), but at this point of time [Go implementation](https://github.com/jbenet/go-ipfs) is reference.

**Comment by piranna** [comment]
Sorry, but no. NodeOS aims to be a minimalistic system, so this kind of features are better managed as user dependencies instead of being included in the OS core.
