### ISSUE TITLE
how installed at windows8

### ISSUE THREAD

**Issue by codebeautiful** [NodeOS/NodeOS#112]

**Comment by piranna** [comment]
Sorry but NodeOS can't installed on Windows 8, at this moment you need a
Linux host to compile it. There has been some work to compile it on MacOS X
without result, if you want to compile it on Windows you'll need a Linux
virtual machine, but it will be terrible slow. Maybe it could work on
Cygwin, pull-requests welcome :-)

**Comment by codebeautiful** [comment]
sorry, now i forgot -),thanks also
