### ISSUE TITLE
genfatfs.js

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#113]
Create Javascript port of [getfatfs](https://github.com/NodeOS/genfatfs), utility adapted from [genext2fs](http://genext2fs.sourceforge.net/). It could be used [fatfs](https://github.com/natevw/fatfs) as basis as substitute of [fatfs](http://elm-chan.org/fsw/ff/00index_e.html).

**Comment by 5paceManSpiff** [comment]
:+1: genext2fs is not available in the default repositories of arch linux.

**Comment by piranna** [comment]
Is there any workaround for Arch? If not, you could create a pull-request based on thr code to fetch and compile getfatfs...

**Comment by 5paceManSpiff** [comment]
Nope, though it's pretty easy to compile.  I'll give the pull request a shot.

**Comment by 5paceManSpiff** [comment]
It appears `genext2fs` version `1.4.1` does not include the `--block-size` or `--creator-os` flags.  Are these necessary?

**Comment by piranna** [comment]
The man page don't have them, but they are definitely on the executable

```bash
[piranna@Mabuk:~/workspace/kurento-utils-js]
 (master) > genext2fs -v
genext2fs 1.4.1
genext2fs: Not enough arguments. Try --help or else see the man page.

[piranna@Mabuk:~/workspace/kurento-utils-js]
 (master) > genext2fs --help
Usage: genext2fs [options] image
Create an ext2 filesystem image from directories/files

  -x, --starting-image <image>
  -d, --root <directory>
  -D, --devtable <file>
  -B, --block-size <bytes>
  -b, --size-in-blocks <blocks>
  -i, --bytes-per-inode <bytes per inode>
  -N, --number-of-inodes <number of inodes>
  -m, --reserved-percentage <percentage of blocks to reserve>
  -o, --creator-os <os>      'linux', 'hurd', 'freebsd' or a numerical value.
  -g, --block-map <path>     Generate a block map file for this path.
  -e, --fill-value <value>   Fill unallocated blocks with value.
  -z, --allow-holes          Allow files with holes.
  -f, --faketime             Set filesystem timestamps to 0 (for testing).
  -q, --squash               Same as "-U -P".
  -U, --squash-uids          Squash owners making all files be owned by root.
  -P, --squash-perms         Squash permissions on all files.
  -h, --help
  -V, --version
  -v, --verbose

Report bugs to genext2fs-devel@lists.sourceforge.net
```

They are not "necessary" but it's good to have them set instead of depend on their default values ;-)
