### ISSUE TITLE
browser display server

### ISSUE THREAD

**Issue by 5paceManSpiff** [NodeOS/NodeOS#117]
i think it would be really cool to use something like [atom-shell](/atom/atom-shell) to create a universal display server completely run on html and javascript injections

**Comment by netlovers** [comment]
Check out this thread: https://github.com/NodeOS/NodeOS/issues/79

**Comment by piranna** [comment]
Clossing as duplicate of #79

**Comment by 5paceManSpiff** [comment]
thanks!
