### ISSUE TITLE
npm command stalls in nsh

### ISSUE THREAD

**Issue by 5paceManSpiff** [NodeOS/NodeOS#124]
I'm not quite sure if this is the right place, but the npm command in the 2015-03-31 qemu release seems to stall for me on a newline without producing any output.

**Comment by piranna** [comment]
Are you talking about the ```npm``` command running inside NodeOS? We have at this moment network support disabled, so this may be the reason why it's not working for you. Definitely something that need to be reviewed soon.

**Comment by 5paceManSpiff** [comment]
Yup, the npm command from within NodeOS.

**Comment by 5paceManSpiff** [comment]
How would I go about enabling network support?  Do I have to do anything fancy from within qemu?

**Comment by piranna** [comment]
QEmu itself have by default a basic network interface, problem is regarding to NodeOS itself. In old instances it was working on Docker, but lately the dependencies doesn't compile and need a review, and also the new filesystem would lead to problems if it needs access to ```/proc``` :-/ I have been focusing on make a solid base and a secure architecture, sorry. Pull-request welcome, though :-P

**Comment by 5paceManSpiff** [comment]
Sweet!  I'm gonna play around with creating some sort of user facing device manager interface, possibly through my flow based programming library [forker](https://github.com/purityapp/forker).

**Comment by piranna** [comment]
A better alternative [is to do it as a FUSE filesystem](https://github.com/NodeOS/NodeOS/issues/95), this way current apps that use the ```/dev``` filesystem can still work the same way.

**Comment by piranna** [comment]
Seems it was a problem due to lack of memory, on real hardware `npm` works without problems, although I forgot to test to download any module. Could you be able to download latest release and check it?

**Comment by piranna** [comment]
Closed since this is working now on master.
