### ISSUE TITLE
It's alive!

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#127]
It's has been a tough week, but as we advanced on [our previous post](https://github.com/NodeOS/NodeOS/issues/118), finally we got a great milestone leading to [our first alpha release](https://github.com/NodeOS/NodeOS/issues/37) to raise lower the entry barrier to new NodeOS users: now NodeOS has [pre-build images](https://github.com/NodeOS/NodeOS/releases) automatically generated both for QEmu, CD live ISOs images ([one of the most requested issues](https://github.com/NodeOS/NodeOS/issues/30), also on [Twitter](https://twitter.com/espectalll123/status/566359430472957952)), and disk images (with a writable usersfs partition! permanent storage! yay!:-D )...
![img-20150402-wa0002](https://cloud.githubusercontent.com/assets/532414/6964862/627916c4-d94d-11e4-8da6-84c2d8dc8001.jpeg)
...that work on real hardware!!! :-D

To create the CD-live ISOs it was more-or-less easy thanks to the fact that now the root filesystem is read-only (so it can boot from a CD-ROM) and using [grub-mkrescue](https://www.gnu.org/software/grub/manual/html_node/Invoking-grub_002dmkrescue.html). Problem is, that it requires to define a usersfs partition by hand, or if not the changes would only be done on memory. To allow to make them persistent the best option was to make a partitioned disk image with both a read-only rootfs and a read-write usersfs, and allow to write it to an USB pendrive. At first I though about continue using grub, but after two days I left it: it's difficult to use on disk images, bloated and require to use ```sudo```, so I decided to [think different](http://en.wikipedia.org/wiki/Think_different) (I did already by using [musl](http://www.musl-libc.org/) instead of [glibc](http://www.gnu.org/software/libc/)) and ended using [syslinux](http://www.syslinux.org/wiki/index.php/The_Syslinux_Project). Result? Easy to configure (and similar to the one used on the Raspberry Pi boot process), works natively with disk images, don't need ```sudo``` and it was ready in just two hours :-D I'll later from grub-mkrescue to use [isolinux](http://www.syslinux.org/wiki/index.php/ISOLINUX) so I can use only one boot system.

Oh, and if you want to write it to an USB pendrive, t[here's also a tool to do this](https://github.com/NodeOS/NodeOS/blob/master/bin/installUSB) and automatically expand the full disk space... Would be interesting to see this on a hard disk... ;-)

There are some more issues to fix. For example, the errors you see on the previous image are regarding that the image is prepared to mount usersfs from ```/dev/sda2```, while as you can see it has set the USB drive as ```/dev/sdb``` (and ```/dev/sda``` is my internal hard disk), so I'll need to add support on [nodeos-mount-filesystems](https://github.com/piranna/nodeos-mount-filesystems) to mount them based on UUIDs to prevent this. Another more annoying was that the first test on real hardware on [my work](https://www.kurento.org/) MacBook didn't booted at all, just to get to the point later that Macs are using EFI instead of BIOS, so I'll need to investigate how to do a disk image that can boot on both systems.

Anyway, now I can say it:
![its-alive](https://cloud.githubusercontent.com/assets/532414/6963698/8463c9c4-d942-11e4-9423-eb88f56d4b27.jpg)
 :-P

**Comment by formula1** [comment]
:O!!!

**Comment by naturalethic** [comment]
:+1:
