### ISSUE TITLE
NPAPI Support

### ISSUE THREAD

**Issue by jaruba** [NodeOS/NodeOS#128]
I'm simply trying to wrap my mind around how NodeOS works and what developer capabilities it has.

Is NodeOS some sort of Browser OS (maybe chromium such as node-webkit) that introduces node.js as the primary programming language for the OS? If so, what are the possibilities of supporting NPAPI plugins too?

I'm asking because I'm looking for a way to bring [WebChimera](http://www.webchimera.org/) to ARM devices for video support with a developer friendly UI and a very powerful JS API.

Could NodeOS be the solution to this? If not, I'm still curious of how one would go about creating an app for such an OS.

Thanks in advance for an answer and sorry if my questions seem dumb as I did not research this project very well, I can only talk from experience with node.js and node-webkit. :)

**Comment by piranna** [comment]
NodeOS is not a browser OS, and there's not support for NPAPI at all, and will never have. NodeOS is a Linux-based operating system that use Node.js as runtime environment, the same way others use GNU libraries or FirefoxOS use Gecko. As such one, it provides a minimalist environment where Node.js apps can run, so apps developed for NodeOS are the same ones developed for Node.js running on any other operating system.

At this moment there are no native GUI but some people is working to port CEF to NodeOS, so graphic apps can be build as tipical webapps with a clent-served architecture, so they could be able to run on any web browser without modifications.

**Comment by jaruba** [comment]
Thanks for the info!

Your doing great work, keep it up! :)

**Comment by piranna** [comment]
You're welcome :-)
