### ISSUE TITLE
Manual compilation doesn't start login prompt

### ISSUE THREAD

**Issue by 5paceManSpiff** [NodeOS/NodeOS#134]
After manually compiling NodeOS with `npm install`, and running it with `npm start`, I get a nodejs REPL prompt rather than a login and nsh shell.  Is this intentional?  If so, how do I go about installing nsh?

**Comment by piranna** [comment]
Does it compiled everything correctly? If so, it would be an error on the boot process, could you be able to send it? What's the prompt of the REPL (it show the actual module that got the error)?

**Comment by piranna** [comment]
@5paceManSpiff, did you get any progress with this? Can we close it?

**Comment by piranna** [comment]
Close by lack of feedback.
