### ISSUE TITLE
error: 'SIOCSIFNAME' was not declared in this scope

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#137]
I've retaken the net support and found the problem was a bad name on one of the dependencies package.json, so it got to be overwritten and that's why it wasn't found. After that, I got be able to compile ```node-bin-ifconfig``` and exec it on my Ubuntu machine and set the IP of my eth0 card :-) But when doing so on NodeOS, compile fails with the next error:

```
> src-sockios@0.1.0 install /home/piranna/Proyectos/NodeOS/node_modules/nodeos-usersfs/obj/nocona/nodeos/lib/node_modules/bin-ifconfig/node_modules/src-sockios
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/piranna/Proyectos/NodeOS/node_modules/nodeos-usersfs/obj/nocona/nodeos/lib/node_modules/bin-ifconfig/node_modules/src-sockios/build'
  CXX(target) Release/obj.target/binding/src/sockios.o
../src/sockios.cc: In function 'void GetFlags(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/sockios.cc:48:62: error: 'SIOCSIFNAME' was not declared in this scope
binding.target.mk:85: recipe for target 'Release/obj.target/binding/src/sockios.o' failed
make: *** [Release/obj.target/binding/src/sockios.o] Error 1
make: Leaving directory '/home/piranna/Proyectos/NodeOS/node_modules/nodeos-usersfs/obj/nocona/nodeos/lib/node_modules/bin-ifconfig/node_modules/src-sockios/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/piranna/Proyectos/NodeOS/node_modules/nodeos-barebones/deps/node/deps/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-13-generic
gyp ERR! command "node" "/home/piranna/Proyectos/NodeOS/node_modules/nodeos-barebones/deps/node/deps/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/piranna/Proyectos/NodeOS/node_modules/nodeos-usersfs/obj/nocona/nodeos/lib/node_modules/bin-ifconfig/node_modules/src-sockios
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

So, ```SIOCSIFNAME``` is not found on [sys/ioctl.h](http://git.musl-libc.org/cgit/musl/tree/include/sys/ioctl.h) nor ```bits/ioctl.h```. In fact, in that last file there's a lot of defines but the entry for ```SIOCSIFNAME``` (0x8923) is missing! The point is that's defined on the [Linux kernel](http://lxr.free-electrons.com/source/include/uapi/linux/sockios.h#L52), so only explanation I can find is the fact that [the man pages says](http://linux.die.net/man/7/netdevice) it's a priviledged operation and due to this, the Linux kernel ```make install_headers``` don't export it... or some of the [NodeOS Linux kernel config](https://github.com/NodeOS/NodeOS/blob/master/node_modules/nodeos-barebones/config) has blocked it (that would explain why [Debian had the same problem on glibc](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=164638), so maybe I should write to musl guys...), although I can't be able to find what could do it (specially since there's no KCONFIG macros near in the source code...). 

Probably it's somewhat related to issue #96. @netlovers, since you could be able to compile it, could you be able to confirm this is still working on Linux 4.0? I didn't give it a try until now... :-/

Another option I'm thinking is to just comment [the line on the node-src-sockios](https://github.com/netlovers/node-src-sockios/blob/master/src/sockios.cc#L48) project so it doesn't get exported since we are not using it anyway, so maybe it's the easies one... What do you think?

**Comment by piranna** [comment]
```Javascript
/ # ifconfig 
{}
/ # ifconfig eth0 10.0.0.1
[   29.547836] e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
/ # ifconfig
{ eth0: { address: '10.0.0.1' } }
/ # node
> var os = require('os')
undefined
> os.networkInterfaces
[Function: getInterfaceAddresses]
> os.networkInterfaces()
{ eth0: 
   [ { address: '10.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '52:54:00:12:34:56',
       internal: false },
     { address: 'fe80::5054:ff:fe12:3456',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '52:54:00:12:34:56',
       scopeid: 2,
       internal: false } ] }
> 
```

Well, seems just commenting the line works, it's something! :-) But we would need to know why the ```SIOCSIFNAME``` define is not available :-/ Oh, and a Javascript implementation of ping and dns to do tests! :-P

**Comment by netlovers** [comment]
Okay, I'll try to compile this when I have some more time, but maybe tonight.

**Comment by piranna** [comment]
Cool, take your time :-)

**Comment by piranna** [comment]
```Javascript
> var dns = require('dns');
undefined
> dns.getServers()
[ '127.0.0.1' ]
> dns.setServers(['10.0.2.3'])
undefined
> dns.getServers()
[ '10.0.2.3' ]
> dns.resolve4('www.google.com', function (err, addresses) {
...   if (err) throw err;
... 
...   console.log('addresses: ' + JSON.stringify(addresses));
... 
...   addresses.forEach(function (a) {
...     dns.reverse(a, function (err, hostnames) {
.....       if (err) {
.......         throw err;
.......       }
..... 
...       console.log('reverse for ' + a + ': ' + JSON.stringify(hostnames));
...     });
...   });
... });
{ bindingName: 'queryA',
  callback: { [Function: asyncCallback] immediately: true },
  hostname: 'www.google.com',
  oncomplete: [Function: onresolve] }
> addresses: ["216.58.211.228"]
reverse for 216.58.211.228: ["mad01s24-in-f4.1e100.net","mad01s24-in-f4.1e100.net"]

undefined
>
```

YESSSSSS!!!!!!!!!!! F*CK YEAH!!!!!!!!! DNS RESOLUTION!!!!!!!!! :-D

Woah, I didn't got it to work, but later when I did it, it was really easy! :-D This is inside QEmu after setting by hand with ifconfig the default IP given by its virtual DHCP server (10.0.2.15). After that, I tried to download an HTML file from my host Ubuntu since we don't have a ping command (yet), but it gave a timeout error (that's better than a host unreachable, by the way ;-) ). So, reading the [dns module](https://nodejs.org/api/dns.html) docs found that the ```resolve()``` functions do a real network DNS lookup instead of using local utilities like ```/etc/hosts``` or ```resolv.conf``` files that we don't have (and I don't want it, but a per-user ```hosts``` file would be a cool thing... :-) ), so after seeing it was using the virtual machine as DNS server instead of the one offered by QEmu (10.0.2.3), I changed it, used the resolve() function... et voila, internet access!!! :-D

This needs some work, for instance the ```http``` module is still throwing a ```getaddrinfo EAI_AGAIN``` error, so that means it uses ```dns.lookup()``` function. That's why I think [we could patch the dns module](https://github.com/NodeOS/NodeOS/issues/139) so lookup functions and its dependents can still work, maybe with a simple mapping between them and their resolv() counterparts, or maybe giving them some more logic (cache, reading config files...), what do you thing?

Woah, I still don't believe network is working, now I will be able to add some network performance statistics to my degree thesis!!! :-D

**Comment by piranna** [comment]
[DNS working](http://www.musl-libc.org/doc/1.0.0/manual.html), it was just that the ```/etc/resolv``` file I was using was pointing to Google DNS servers instead the one on the QEmu local network... and no need to patch Node.js dns module :-) Now it only left to define the default gateway (and maybe the routes).

**Comment by piranna** [comment]
```Javascript
/ # ip route add default via 10.0.2.2
SIOCADDRT failed , ret->-1
Could Not Set Default gateway
/ # ifconfig eth0 10.0.2.15
[   36.114512] e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
/ # ip route add default via 10.0.2.2
/ # ifconfig
{ eth0: { address: '10.0.2.15' } }
/ # ip
Usage: /bin/ip route add default via <ip>
/ # node
> http.get("http://www.google.com/index.html", function(res) {
...   console.log("Got response: " + res.statusCode);
... }).on('error', function(e) {
...   console.log("Got error: " + e.message);
... });
> Got response: 302
```

Yes, full network support! :-D Routes were already available with the [ip](https://www.npmjs.com/package/bin-ip) command, only that it needed to be updated to use the new [sockios](https://github.com/NodeOS/sockios) by @netlovers, so [I've also uploaded it](https://github.com/NodeOS/ip) so it's available here at GitHub. Yay! :-D
