### ISSUE TITLE
NodeOS prebuilt binaries should contain a folder with files rather than a bunch of files

### ISSUE THREAD

**Issue by dbkaplun** [NodeOS/NodeOS#142]

**Comment by secrettriangle** [comment]
Continuing discussion from slap-editor/slap#150...

It's a matter of standards conformance. Typically software zips contain a folder with files rather than a bunch of files. If a user calls `unzip nodeos-bin.zip` he shouldn't get his directory polluted with a bunch of random files.

**Comment by piranna** [comment]
> Continuing discussion from slap-editor/slap#150...

:+1: 


> It's a matter of standards conformance. Typically software zips contain a folder with files rather than a bunch of files. If a user calls unzip nodeos-bin.zip he shouldn't get his directory polluted with a bunch of random files.

Maybe that's one of the reasons why cpio only accept to compress one file and if you want to compress more you need to tar a folder?

**Comment by lite20** [comment]
Status?

**Comment by piranna** [comment]
Very low priority. Let's see how this going on with the `prebuild` module, whatever behaviour it has when we'll use it for the NodeOS prebuild images we'll follow it, so I would close this and keep going on.

**Comment by lite20** [comment]
Okay hahaha
