### ISSUE TITLE
Linux kernel elimination

### ISSUE THREAD

**Issue by HackerGaucho** [NodeOS/NodeOS#145]
There is the possibility of eliminating the linux kernel in the future? it seems more complicated than help in several cases also slows the installation. look this: Python without an operating system http://lwn.net/SubscriberLink/641244/5d1d6d20aeb0a647/

**Comment by piranna** [comment]
Thank you, but no. Why you think it's more complicated? What alternatives are you thinking about?

Probably what you are looking for is [runtime.js](https://github.com/runtimejs/runtime), an OS kernel written in Javascript. NodeOS is mostly kernel agnostic and I was thinking about doing a FreeBSD port just for the sake of it, so probably in the future we use runtime.js as the default kernel of NodeOS and make use of its advantages.

The link that you posted is interesting (and the fact that they were doing the demo directly on BITS by using the EFI Graphics Protocol is really cool :-D ), but they haven't done anything that has been done before, only paste the CPython code to the GRUB2 code and add some glue code. They could have been able to do the same by using directly CPython and NewLib so it could run baremetal ([I did something similar in the past](https://github.com/piranna/Gaia) using [PyMite](https://code.google.com/p/python-on-a-chip/) instead, but today I would use [MicroPython](https://github.com/micropython/micropython) instead). This could be done with NodeOS too, but you missed one important point: drivers. Linux provides drivers for almost all hardware available today, and it's frequently updated. By using a raw system like runtime.js, you need to write drivers for _everything_, that's definitely not something easy to do...

**Comment by HackerGaucho** [comment]
Thx piranna.
