### ISSUE TITLE
Display/include version information within runtime

### ISSUE THREAD

**Issue by dbkaplun** [NodeOS/NodeOS#148]

**Comment by piranna** [comment]
What are you exactly thinking about? How should it be showed? process.versions is the ideal candidate, but that require patch Node.js sources. Also, how the version could be included? The one from the package.json? This could need to be published, but I set it as private on purposse so people don't try to use NodeOS as dependendy and instead make their own custon forks on GitHub...

**Comment by secrettriangle** [comment]
I was thinking like a MOTD, as that's how other systems do it.

**Comment by piranna** [comment]
Ok, lgtm, but I was asking more exactly about how and where store that info ;-)

**Comment by piranna** [comment]
https://github.com/NodeOS/NodeOS/commit/0b4dd56a7d07e7ce973805a083894f5409435ce3 fixed this, you can get the current NodeOS version by doing ```require('os).nodeos``` :-)
