### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by riordanp** [NodeOS/NodeOS#150]
Hi, I get this error running the install-dependencies script

```
dpkg: dependency problems prevent configuration of extlinux:
 syslinux-common (3:6.03~pre18+dfsg-1ubuntu1) breaks extlinux (<< 3:6.03~pre18+dfsg-1ubuntu1) and is installed.
  Version of extlinux to be configured is 3:4.05+dfsg-6+deb8u1.

dpkg: error processing package extlinux (--install):
 dependency problems - leaving unconfigured
```

this seems to have broken apt now, running elementaryOS Freya (Ubuntu 14.04)

Any thoughts?

Edit:
running apt-get autoremove -f seems to have got rid of the problematic extlinux package and fixed apt but still leaves me with incorrect dependencies to build NodeOS

**Comment by piranna** [comment]
I have only tested it on vanilla Ubuntu 14.04, not on ElementaryOS. Extlinux is not necesary for NodeOS, only Syslinux, anyway it shoukd be removed in the future and used the pre-buikd binaries from the project page (pull-request welcome! ;-) ). Meanwhile, you can use one of the precompiled releases.

**Comment by riordanp** [comment]
I figured it wasn't required and proceeded to try the build again. Now, while the toolchain and node itself seems to compile, linux does not. Looks like this is due to missing files in the toolchain target folder?

```
npm WARN package.json nodeos-initramfs@0.0.0 No repository field.
npm WARN package.json nodeos-usersfs@0.0.0 No repository field.
npm WARN package.json nodeos-rootfs@0.0.0 No repository field.
npm WARN package.json nodeos-barebones@0.0.0 No repository field.

> nodeos-barebones@0.0.0 preinstall /home/riordan/Coding/NodeOS/node_modules/nodeos-barebones
> scripts/preinstall
> nodeos-cross-toolchain@0.0.0 preinstall /home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/preinstall
> nodeos-cross-toolchain@0.0.0 install /home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/install
'/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/usr' -> '.'
'/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib64' -> 'lib'
> nodeos-cross-toolchain@0.0.0 postinstall /home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/postinstall

x86_64-nodeos-linux-musl-strip: Warning: '/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out//lib/gcc' is not an ordinary file
x86_64-nodeos-linux-musl-strip: '/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib/ld-musl-x86_64.so.1': No such file
x86_64-nodeos-linux-musl-strip: Warning: '/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib/ldscripts' is not an ordinary file
x86_64-nodeos-linux-musl-strip: unable to copy file '/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out//bin/x86_64-nodeos-linux-musl-strip'; reason: Text file busy
x86_64-nodeos-linux-musl-strip: unable to copy file '/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/bin/strip'; reason: Text file busy
Successfully built a x86_64-nodeos-linux-musl cross-toolchain

> nodeos-barebones@0.0.0 install /home/riordan/Coding/NodeOS/node_modules/nodeos-barebones
> scripts/install

Compiling Linux
#
# configuration written to .config
#
.config:3724:warning: override: reassigning to symbol INITRAMFS_SOURCE
.config:3731:warning: override: reassigning to symbol MODULES
.config:3738:warning: override: reassigning to symbol OSF_PARTITION
.config:3739:warning: override: reassigning to symbol AMIGA_PARTITION
.config:3741:warning: override: reassigning to symbol BSD_DISKLABEL
.config:3742:warning: override: reassigning to symbol MINIX_SUBPARTITION
.config:3743:warning: override: reassigning to symbol SOLARIS_X86_PARTITION
.config:3744:warning: override: reassigning to symbol UNIXWARE_DISKLABEL
.config:3746:warning: override: reassigning to symbol SGI_PARTITION
.config:3748:warning: override: reassigning to symbol SUN_PARTITION
.config:3755:warning: override: reassigning to symbol NETFILTER_XT_MARK
.config:3762:warning: override: reassigning to symbol NETFILTER_XT_TARGET_LOG
.config:3769:warning: override: reassigning to symbol NF_LOG_IPV6
.config:3776:warning: override: reassigning to symbol HAMRADIO
.config:3783:warning: override: reassigning to symbol DEVTMPFS_MOUNT
.config:3790:warning: override: reassigning to symbol X86_PKG_TEMP_THERMAL
.config:3798:warning: override: reassigning to symbol FB_VESA
.config:3799:warning: override: reassigning to symbol FB_EFI
.config:3806:warning: override: reassigning to symbol FUSE_FS
.config:3808:warning: override: reassigning to symbol OVERLAY_FS
.config:3815:warning: override: reassigning to symbol MISC_FILESYSTEMS
.config:3822:warning: override: reassigning to symbol DEBUG_KERNEL
.config:3829:warning: override: reassigning to symbol STACKTRACE
.config:3836:warning: override: reassigning to symbol FTRACE
.config:3843:warning: override: reassigning to symbol VIRTUALIZATION
.config:3844:warning: override: reassigning to symbol BINARY_PRINTF
#
# configuration written to .config
#
File /home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib/libgcc_s.so.1 could not be opened for reading
 line 34
File /home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib/libstdc++.so.6.0.17 could not be opened for reading
 line 35
make[2]: *** [usr/initramfs_data.cpio.gz] Error 255
make[1]: *** [usr] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [sub-make] Error 2
Error compiling '/home/riordan/Coding/NodeOS/node_modules/nodeos-barebones/obj/nocona/linux'

npm ERR! nodeos-barebones@0.0.0 install: `scripts/install`
npm ERR! Exit status 26
npm ERR! 
npm ERR! Failed at the nodeos-barebones@0.0.0 install script.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-53-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/riordan/Coding/NodeOS
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/riordan/Coding/NodeOS/npm-debug.log
npm ERR! not ok code 0
```
I tried the current precompile release but it seems broken? Using commands slap or npm as the demo user just drops my prompt and recuires a Ctrl+C to get me out of NodeOS again. I am aware networking isn't enabled at the moment and I wanted to have a go at enabling that and tinkering with some sort of UI system.

**Comment by piranna** [comment]
Seems that the build process was wrong somewhere and the toolchain is in bad state, I would remove all the deps, obj and out directories and build it again. Slap and npm are not working yet but don't know why, seems they enter in some kind of loop or similar. Regarding networking it works in an experimental status, I'm not sure if I uploaded the changes but the point it's that's working, but it's cumbersome to enable it. Hope to be able to use node-dhcpjs in the near future, but I'll be busy with my degree thesis and examns until July.

**Comment by riordanp** [comment]
Finally got it built, removing the output folders worked and I now have my very own NodeOS enviroment with my own user added in!

Another issue I encountered was the install scripts failing to use my ~/.npm directory which was solved by a simple chown.

Really excited about this project, going to play with it now. Thanks for your help and good luck with your thesis :)

**Comment by piranna** [comment]
> Finally got it built, removing the output folders worked and I now have
my very own NodeOS enviroment with my own user added in!

Good yo know! :-) How did you added your own user? How would you improve
the process? Or better than this... pull-reqyest welcome! :-)

> Another issue I encountered was the install scripts failing to use my
~/.npm directory which was solved by a simple chown.

Well... another (better) options are to use 'npm cache clean' or directly
remove the folder... :-)

> Really excited about this project, going to play with it now. Thanks for
your help and good luck with your thesis :)

Thank you! :-)

**Comment by riordanp** [comment]
I added a new user by just copy and pasting the section in the usersfs install script for the demo user and created a new logon.json which was copied to obj too. I suppose adding a new user just involves them having a user folder in the filesystem generated but probably only root should be able to. What are your thoughts on some sort of privilege escalation? Could run a network service a root which you can HTTP post commands to with some sort of authentication and if you're a whitelisted user/have permission to use the command it will call it from root. Similar to sudo for the user I suppose.

**Comment by piranna** [comment]
> I suppose adding a new user just involves them having a user folder in the filesystem generated but probably only root should be able to.

Yes, that's just the idea, but I'm not sure root should be the only one capable to do it. I was thinking that logon itself could allow to everybody to create an account on the system, but don't know if it would have some drawbacks...


> What are your thoughts on some sort of privilege escalation?

For system services, or as a security flaw?


> Could run a network service a root which you can HTTP post commands to with some sort of authentication and if you're a whitelisted user/have permission to use the command it will call it from root. Similar to sudo for the user I suppose.

I'm against to have any sudo-like system on NodeOS, both from a security and architectural perspective. NodeOS should not have priviledged users, everybody should have the same restrictive permissions. This makes it more difficult to think about some othervise trivial thinks like how to reboot the system, but also this constraints allow to find some more better and creatives alternatives (and the same happened with the build process to don't need to use sudo at all... :-) )
