### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#152]
Update info on the website, people is still mocking about us... :-(

https://twitter.com/sarahlicity/status/610600592612925440

Hope when we launch 0.1.0 with the new architecture we can give them a bazinga... :-)

**Comment by formula1** [comment]
Man, this hits home pretty hard : (

Is that info still up there? For what its worth, I know a guy that takes security very seriously. I can talk to him about his techniques, maybe build a module for it. I don't like something I care about to be rediculed (for fixable/non-philosophical reasons).

**Comment by aulvi** [comment]
Haters gunna hate. This isn't anywhere near a production-ready system, security is not a forefront concern at this stage. Focus on the immediate tasks at hand, and if someone is really concerned about security, well, PRs are welcomed!

Chin up everyone, this is a fun project, happy hacking!

**Comment by piranna** [comment]
> Is that info still up there?

That (outdated) info is available in the old blog, from some post of @groundwater from more than a year ago, so they doesn't have anything to do with the actual status but people seems to take them as the rule, like the instructions for Docker, that's currently unmaintained. Maybe we should add them a big note saying that's only there for historical purposses and redirect them to the GitHub page or something... ideas?

And obviously, work hard for a great 0.1.0 release... :-D


> For what its worth, I know a guy that takes security very seriously. I can talk to him about his techniques, maybe build a module for it.

I don't think this is necesary at this moment, but a little security auditory for the current structure would be great. I think I've done correctly the users isolation, but maybe I could have slipped something when using chroot, and if I allow logon to access anybody and create user accounts just for the sake of openess it could lead to fill up the hard disk... :-/


> I don't like something I care about to be rediculed (for fixable/non-philosophical reasons).

Me too. That kind of things make oneself want to drop it at all :-( At least I've known the other day at [OpenExpo Day](http://www.openexpo.es/) at least [one company](https://crowdference.org/) interested on the project... :-)


> Chin up everyone, this is a fun project, happy hacking!

Yes, I think we are in the stage of think different and make it fun :-D

**Comment by formula1** [comment]
I like that :D think different, have fun

**Comment by lite20** [comment]
Closing as this is under way
