### ISSUE TITLE
Change boot logo

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#156]
Framebuffer currently use the vanilla Tux logo on boot, we can cnange it to show NodeOS logo. Also, just today has been submitted a patch to Linux kernel [to allow full-screen logos](http://comments.gmane.org/gmane.linux.kernel/1988133), that would be cool... :-)

**Comment by lite20** [comment]
@piranna Looking into this!

**Comment by lite20** [comment]
@piranna  would you like a startup screen similar to that of Ubuntu?

**Comment by piranna** [comment]
> @piranna Looking into this!

Cool! You have the logo sources on the NodeOS/media repository :-)

**Comment by piranna** [comment]
> @piranna would you like a startup screen similar to that of Ubuntu?

This is somewhat conplicated, but I've read about it's possible to add full
screen logos that mimic this, but I'm not sure it it's just an offtree
patch. One step at a time, let's change first the logo and later we'll see
about the full screen one ;-)

**Comment by lite20** [comment]
@piranna it would be easier to go straight to that as these are actually completely different systems. Swapping the logo is very easy but you need to recompile the kernel. What kernel are we using right now with NodeOS? (i haven't checked)

**Comment by piranna** [comment]
Vanilla 4.4.3 from kernel.org. If you could provide a patch or better a script to generate it directly from an image it would be awesome :-) 2 and 16 colors versions are just enought.

**Comment by Coretool** [comment]
> it would be easier to go straight to that as these are actually completely different systems.

Are you talking about plymouth ?

**Comment by Coretool** [comment]
We could set the kernel output to `quiet` (this comes with the bonus of speeding the boot process up ) and draw the image (or animation) with the init. I think, this is also how most of the android distributers do it...

**Comment by piranna** [comment]
> We could set the kernel output to quiet (this comes with the bonus of
speeding the boot process up ) and draw the image (or animation) with the
init. I think, this is also how most of the android distributers do it...

Boot takes only about 5 seconds when running on real hardware or with KVM
enabled and most of the time it's about kernel loading, so it doesn't make
sense to show an splash on init. Kernel boot logo or fullscreen boot logo
makes sense since they are shown as soon as framebuffer is ready, almost at
the start of kernel loading.

**Comment by Coretool** [comment]
Hm... If you want an animation (not just the static image) you can start the animation in the bootloader (the kernel has to bequiet) like it is done with many embedded systems...

**Comment by piranna** [comment]
I'm honestly only interested on change framebuffer penguin for NodeOS logo,
but use the bootloader is a good alternative, syslinux support it... :-)

**Comment by lite20** [comment]
> We could set the kernel output to quiet (this comes with the bonus of speeding the boot process up ) and draw the image (or animation) with the init. I think, this is also how most of the android distributers do it...

I had something similar in mind for the full screen. Making the kernel quiet and rendering to the frame buffer the image instead of  the kernel using it for output.

@piranna did you want a kernel patch file for replacing tux? I can do that

**Comment by piranna** [comment]
>> We could set the kernel output to quiet (this comes with the bonus of
speeding the boot process up ) and draw the image (or animation) with the
init. I think, this is also how most of the android distributers do it...
>
> I had something similar in mind for the full screen. Making the kernel
quiet and rendering to the frame buffer the image instead of the kernel
using it for output.

Yeah, but peobably it's better to do it on the bootloader since it start
before. I don't believe anyone support animations, though...

> @piranna did you want a kernel patch file for replacing tux? I can do that

Yeah! But instead a patch, it would e better a script that generate that
patch so we can integrate it better in NodeOS build steps. If you write
down the steps that you follow, we could do the script later as has been
done with noGUI... :-) Don't worry, an independent project is not needed
here ;-)

**Comment by Coretool** [comment]
Since Syslinux supports (full screen) splash screens, it shouldn't bee too hard to change the splash screen... I asked my friends over at the arch forums if it is also possible to use anomated gifs (if you want to add something like a process bar or whatever)... still waiting for a response :/

**Comment by lite20** [comment]
:D status? Was anyone able to pick this up?

**Comment by piranna** [comment]
There was some progress here and was almost working, but don't remember how it's now... Could someone refresh my memory?

**Comment by Coretool** [comment]
@piranna Diffs have to be compressed into one file and the Logo.ppm has to be refreshed since it's to small. I'll do that asap.

**Comment by Coretool** [comment]
Ok, something's pretty sad.

**Comment by piranna** [comment]
How have you done it? It's impossible it get's so ugly... What steps have you followed to do the ppm file?

**Comment by Coretool** [comment]
The [one you posted](http://web.archive.org/web/20140707092448/http://sumanprasanna.wordpress.com/2012/12/11/how-to-change-your-boot-logo-in-linux-kernel)

```sh
pngtopnm logo.png | ppmquant -fs223| pnmtoplainpnm > logo_linux_clut224.ppm
cp logo_linux_clut224.ppm /usr/src/linux/drivers/video/logo/
```

**Comment by piranna** [comment]
How did you create the png image? Does it looks good? Can you attach it
here?

**Comment by Coretool** [comment]
I use gimp to create the png. 
![nodeos](https://cloud.githubusercontent.com/assets/9163037/17517343/53b953ca-5e43-11e6-99ce-1e43a5a36345.png)

**Comment by piranna** [comment]
Try to check the output of each piped command to see where is failing.

**Comment by piranna** [comment]
Wait: are you using anti-aliasing? That probably is the reason why the png
image has no sharp borders, because the aliasing is increasing the numbers
of colours... It should be enough a palette of just three colours, I set
them specially.

Is there any command line svg raster so we don't need Gimp?

**Comment by piranna** [comment]
http://graphicdesign.stackexchange.com/a/50850

Seems here there are a solution, there's an attribute that can be added to
the SVG file to notify borders should be sharp always and Gimp will respect
that, could you be able to take a look and if so do a pull-request on the
media repo?

**Comment by Coretool** [comment]
Sure !

**Comment by Coretool** [comment]
PR done

**Comment by piranna** [comment]
Did you get any advance creating the patch?

**Comment by Coretool** [comment]
Yeah, I think I'll push it tomorrow... I'm not sure though if the Download Manager supports patches that create new files ...

**Comment by piranna** [comment]
It should... and if not, now we have something to do ;-)

**Comment by lite20** [comment]
@piranna I like the new "level of difficulty" tags you've added! Excellent work

**Comment by piranna** [comment]
You are welcome ^^

**Comment by piranna** [comment]
Clossing since this is already in master since a while.
