### ISSUE TITLE
Isn't it possible to use node-webkit for a desktop ?

### ISSUE THREAD

**Issue by Coretool** [NodeOS/NodeOS#161]
Hi 

I recently stumbeld upon your project an saw that it doesn't have a desktop ! Isn't it possible to use node-webkit for the desktop ? I have written a window manager once and would like to do it a second time! Since node WebKit has got a rendrer for HTML and is compatible with node.js it should be perfect for this...

**Comment by piranna** [comment]
Node-webkit is not an option since it integrate node js APIs with the html dom, while we want to have them isolated so gui apps could be used on estandar web browsers, and also there's the problem that node-webkit get compiled for X11 that we don't use it. At this moment we have only support for Linux frambuffer and in the future we hope to have EGL, but it's not easy.

Chrome Content API seems promising, but needs some testing. Another option is to use Gecko, but we didn't thought too much about it. Anyway, if you can provides us an easy to compile autonomous web renderer (html + javascript + url fetching) that works on fbdev and ideally with html5 support (specially canvas and video) we could use it :-)

**Comment by Coretool** [comment]
OK, I will start working on it ;)! I don't have much experience with fbdev itself but I will work on it !

**Comment by piranna** [comment]
That would be cool ;-) FbDev is really easy to work with (that it's purposse after all! :-D), so if you can make it to work on FbDev on your desktop without dependencies on X11 at all, then it should be easy to package as a npm package and make it to work on NodeOS :-)

**Comment by Coretool** [comment]
So do you want it as a part of the kernel or as a "extra" which you have to install over npm?

**Comment by piranna** [comment]
FbDev is part of the Linux kernel and enabled by default, but by NodeOS design the web renderer must be a npm package. It can be a compiled module as node-canvas does, for example. I don't have problems here, but until we can make npm on NodeOS itself to build compiled modules (mostly port a C++ compiler), they'll need to be included at build time. More on this later, first let's get the web renderer to work with fbdev on desktop linux and later will talk about craft a npm package and port it to NodeOS ;-)

**Comment by Coretool** [comment]
OK, I will write another "issue" when I got the first stable build of the engine!

**Comment by piranna** [comment]
Cool then! :-)

**Comment by Coretool** [comment]
Is there a good source to get started with fbdev ?

**Comment by piranna** [comment]
Besides linux kernel documentation, no. It's basically about open the device, use mmap and then you can modify directly the pixels. You can take a look on NodeOS node-canvas fork to see how to use it from Cairo.

**Comment by Coretool** [comment]
Bad news... I created a first version of the engine (it just supports/supported h1,h2,...,h6) and tried it out...
It worked, but it took just too long to use it as an engine for GUIs!! I think you have to use a real engine ! I am really sorry =(

**Comment by piranna** [comment]
FbDev is software rendered, could this be the reason? Do you have the source code somewhere? Maybe it can be useful to others to do some basic things... :-)

**Comment by piranna** [comment]
If you are doing the web renderer in pure Javascript aybe you could take a look on jsDom for the parser, seems it's not too fast but it's very complete.

**Comment by Coretool** [comment]
I've got htmlparser2 which seems to be the fastest ([more information here] (https://www.npmjs.com/package/htmlparser2))

**Comment by piranna** [comment]
Cool! :-D

**Comment by piranna** [comment]
Clossing since node-webkit was never an option and things are moving towards usage of noGUI.
