### ISSUE TITLE
concept for the gui

### ISSUE THREAD

**Issue by Coretool** [NodeOS/NodeOS#165]
OK, I got a concept for the GUI (or better the "renderer"): 

1. Render HTML with WebKit.js ! (To canvas)
2. Give this out over node-canvas 

This may not be the fastest way but it should make possible that the user doesn't see the loading process. If somebody wants to help, he can commit to my repository when i've pushed the first version out! Let me know about ways to speed this up ;)

**Comment by piranna** [comment]
> Render HTML with WebKit.js ! (To canvas)
> Give this out over node-canvas

That's what I was suggesting you to do :-) From previous posts seems you
got it working, isn't it?

> This may not be the fastest way but it should make possible that the user
doesn't see the loading process.

What do you mean by loading process? The Linux boot messages? This need to
be done at kernel and fbdev level, maybe I would do it when change the
Linux logo for the NodeOS one, but first we would need to original files
(@groundwater, are you there? ;-) ) or recreate it in SVG.

> If somebody wants to help, he can commit to my repository when i've
pushed the first version out!

I'm willingly to see the code :-) The most important thing I believe is to
add the patches and integrate the build process as a prepublish script and
publish it to npm.

> Let me know about ways to speed this up ;)

It's fully software rendered, so difficult, the best is to move to
content_shell + EGL. Besides that, maybe using a graphic card with support
for hardware accelerated framebuffer, not too much can be done... :-(

**Comment by netlovers** [comment]
@Coretool if you check the comments here:
https://github.com/NodeOS/NodeOS/issues/79#issuecomment-126714207
You can see that it's not super easy to use `webkit.js`. With the basic `node-canvas` module it does not even work. @piranna found this:
http://cimaron.net/projects/cwebgl/
I guess this could actually work, but at the moment I don't have time to try it. But it could be a good starting point.

**Comment by Coretool** [comment]
@piranna with "loading process" i mean the rendering time ! It takes its time ot render HTML in js since its (sadly) not Hardware accelerated! @netlovers Didn't saw that... I will test it =) Corss the fingers for me! cWebGL sounds good ! I just don't understand what you exactly want to do with it... Do you wanna use it to implement a opengl stack to give the canvas from webkit out to the screen ? (I am not sure it that works =/ ...)

**Comment by piranna** [comment]
> cWebGL sounds good ! I just don't understand what you exactly want to do with it... Do you wanna use it to implement a opengl stack to give the canvas from webkit out to the screen ? (I am not sure it that works =/ ...)

cWebGL add support for WebGL on 2D canvas contexts like the one only supported by node-canvas, doing by software all the WebGL operations, so theorically it would allow that all the OpenGL transformations done by webkit.js would be rendered on node-canvas without crashing. Problem? Slow :-)

**Comment by Coretool** [comment]
I think we should wait with the GUI until nodeOs has reached a stable release with most of the planed features ! As alternative to a "native" GUI we can also add something like an  external web interface (over a webserver or just http(s))...

**Comment by piranna** [comment]
> I think we should wait with the GUI until nodeOs has reached a stable
release with most of the planed features !

Agree, but it's not too bad to go out of the roadmap to have a break time.
That's why I was working on node-canvas during my examns time and during my
jobs change, to aliviate stress :-)

> As alternative to a "native" GUI we can also add something like an
external web interface (over a webserver or just http(s))...

That's the idea why we are proposing to use a vanilla web browser to design
the gui, having a "native" GUI will be "as simple" as being able to run
content_shell on kiosk mode.

**Comment by Coretool** [comment]
So do we stick to the plan with cWebGL ?

**Comment by piranna** [comment]
You can if you want, it would be good to do some comparations, but I would go for content_shell at least for fbdev, specially if webkit.js consume so much memory.

**Comment by Coretool** [comment]
Ok, we will stick to content_shell! Webkit.js consumes more memory then you want it too =/ (on such system) !

**Comment by Coretool** [comment]
However, I would like to work on your project =) So what can I do ?

**Comment by piranna** [comment]
Well, what are you interested about? :-)

**Comment by zreo15** [comment]
I dont get what content shell 
Is the plan to make the GUI using fbdev and javascript like silk GUI or to control the system remotely

**Comment by piranna** [comment]
> I dont get what content shell

https://www.chromium.org/developers/design-documents/ozone content_shell is a minimal version of Chromium that only renders a webpage, think of it as Chrome but without tabs or other browser specifc things, only HTML5 web rendering (including WebRTC! :-D). Mostly what we wants is first to build a statically linked version of content_shell using fbdev (the drm/dri Ozone platform on that page), later modify it to allow adaptative screen resolution instead of being hardcoded to 800x600, and ideally in the future move to use EGL instead of FbDev to can be able to have hardware acceleration.


> Is the plan to make the GUI using fbdev and javascript like silk GUI or to control the system remotely

Ideally and in the long term, the idea is to have the GUI written in plain HTML5 + Javascript + CSS so NodeOS apps can run locally by using content_shell or remotely using a vanilla web browser. That means that at this moment, a GUI can be build using the remote web browser approach.

**Comment by zreo15** [comment]
ohk got it but how will a sysytem written on c/c++ run on sysytem with js base

**Comment by netlovers** [comment]
It'll run, because NodeOS is not written in JavaScript.

**Comment by piranna** [comment]
At its heart, NodeOS is a vanilla Linux OS, only using Node.js for the userspace instead of bash or other languajes/frameworks/libraries...

Other thing is runtime.js, that's entirelly written in Javascript. In that case there would be problems.

**Comment by zreo15** [comment]
ah okay i thought OS was configured in such a way that only stuff written in js would work and others wil have to be ported but nice to know its possible

**Comment by Globik** [comment]
Exguse me, nodeOs does work on windows 7? Clang compiler is ok for node OS?

**Comment by piranna** [comment]
> nodeOs does work on windows 7?

At this moment, to build it you need a Linux machine (we use mainly Ubuntu, but someone help to make the scripts compatible with Arch). The run one of the pre-build images, they can be run ostly wherever QEmu run, if you have problems please open a new issue.


> Clang compiler is ok for node OS?

Don't know, NodeOS cross-toolchain is based on GCC, but I would like to see it working with Clang instead :-)

**Comment by lite20** [comment]
Closing for completion, but starting new thread to discuss Clang.
