### ISSUE TITLE
media

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#166]
I've created a [new repo](https://github.com/NodeOS/media) to host media files related to NodeOS, starting with a redraw of the NodeOS logo. I did it because I needed a good logo image for my thesis, so since there's no copy in vectorial format I did it. It follow the same proportions of the original logo in PNG format (or I think so), only fixed some minor adjustment on the lines. Also I've changed the colors to be someones from the basic VGA palette, so it can be correctly drawn on the console. Anyone is welcome to contribute with wallpapers or similar things based on the [human interface guidelines](https://github.com/NodeOS/NodeOS/issues/147) colors and schemes... or not :-)

Comments? Questions? Suggestions?

**Comment by lite20** [comment]
Maybe this should be mentioned in the wiki or on the ReadMe?

**Comment by piranna** [comment]
Done in readme file ;-)
