### ISSUE TITLE
Error on install nodeos

### ISSUE THREAD

**Issue by nicolsondsouza** [NodeOS/NodeOS#167]
Ubuntu 14.04

npm install
npm WARN package.json nodeos-barebones@0.0.0 No repository field.
npm WARN package.json nodeos-initramfs@0.0.0 No repository field.
npm WARN package.json nodeos-rootfs@0.0.0 No repository field.
npm WARN package.json nodeos-usersfs@0.0.0 No repository field.

> nodeos-barebones@0.0.0 preinstall /home/trinisoft001/office/nodeos/NodeOS/node_modules/nodeos-barebones
> scripts/preinstall

> nodeos-cross-toolchain@0.0.0 preinstall /home/trinisoft001/office/nodeos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/preinstall

> nodeos-cross-toolchain@0.0.0 install /home/trinisoft001/office/nodeos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/build

'/home/trinisoft001/office/nodeos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/usr' -> '.'
'/home/trinisoft001/office/nodeos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/lib64' -> 'lib'
Compiling binutils
mkdir -p -- ./intl
mkdir -p -- ./libiberty
mkdir -p -- ./etc
Configuring in ./libiberty
Configuring in ./intl
Configuring in ./etc
configure: WARNING:
*** Makeinfo is missing. Info documentation will not be built.
mkdir -p -- ./binutils
mkdir -p -- ./gprof
mkdir -p -- ./gas
mkdir -p -- ./ld
Configuring in ./binutils
Configuring in ./ld
Configuring in ./gprof
Configuring in ./gas
mkdir -p -- ./bfd
Configuring in ./bfd
mkdir -p -- ./opcodes
Configuring in ./opcodes
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: creating po/POTFILES
config.status: creating po/Makefile
creating bfdver.h
Making info in doc
WARNING: `makeinfo' is missing on your system.  You should only need it if
         you modified a `.texi' or `.texinfo' file, or any other file
         indirectly affecting the aspect of the manual.  The spurious
         call might also be the consequence of using a buggy `make' (AIX,
         DU, IRIX).  You might want to install the `Texinfo' package or
         the `GNU make' package.  Grab either from any GNU archive site.
make[3]: *** [bfd.info] Error 1
Making info in po
config.status: creating po/Makefile.in
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing bfd_stdint.h commands
config.status: executing default commands
make[2]: *** [info-recursive] Error 1
make[1]: *** [all-bfd] Error 2
make: *** [all] Error 2
Error compiling '/home/trinisoft001/office/nodeos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/obj/nocona/binutils'

npm ERR! nodeos-cross-toolchain@0.0.0 install: `scripts/build`
npm ERR! Exit status 22
npm ERR! 
npm ERR! Failed at the nodeos-cross-toolchain@0.0.0 install script.
npm ERR! This is most likely a problem with the nodeos-cross-toolchain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-cross-toolchain
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-45-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/trinisoft001/office/nodeos/NodeOS
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/trinisoft001/office/nodeos/NodeOS/npm-debug.log
npm ERR! not ok code 0

**Comment by lite20** [comment]
This is seemingly old but to anyone who hits this error too, try using node 4.0. It should come with npm 2 (ish). the version packaged by default in the Ubuntu repositories is insufficient for the NodeOS build process. If you don't already use nvm, I suggest it for managing node as I've loved it ever since I got it.
