### ISSUE TITLE
Move to Node.js 4.0.0

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#169]
I've just surprised to know that [Node.js 4.0.0 was released yesterday](https://nodejs.org/en/blog/release/v4.0.0/) :-P We are currently using 0.11.14 due to [problems with the version of v8](https://github.com/nodejs/node-v0.x-archive/issues/9097), maybe they have just fixed them...

**Comment by piranna** [comment]
I have been trying the last days to upgrade to Node.js 4.1.0 and got some problems, so I've created a new [branch](https://github.com/NodeOS/NodeOS/tree/nodejs_4) to manage this work.

First of all, Node.js 4.1.0 requires gcc 4.0 or greater, while we are using gcc 4.7.3. I've found that the patch we were using to add support for musl on gcc is in fact one from the [musl-cross](https://github.com/GregorR/musl-cross) project, so I've moved to use them directly instead, but unfortunatelly I only got it to work with the version 4.7.3 and no one other, so here we have three options:

1. keep trying to make it work
2. move (partially) to use musl-cross for the cross-compiler (their code is simple and minimalist the same way we have it already)
3. move to a full-fledged cross-compiler platform like [crosstool-NG](http://crosstool-ng.org)

I think the 2 is a good option, maybe helping them to clean a little bit the code and add support for recent versions of vanilla linux kernel (not only a sabotage linux patched 3.16), but there's the issue that maybe this doesn't work if the v8 problem is still there... :-/ Ideas? Suggestions?

/cc @heavyk

**Comment by heavyk** [comment]
I just tried your branch and I think I had less success than you did. I got a segmentation fault in my compiler.

```
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/gcc/bb-reorder.c: In member function 'void fibonacci_heap<K, V>::insert_root(fibonacci_heap<K, V>::fibonacci_node_t*) [with K = long int; V = basic_block_def; fibonacci_heap<K, V>::fibonacci_node_t = fibonacci_node<long int, basic_block_def>]':
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/gcc/bb-reorder.c:2803:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
Makefile:1065: recipe for target 'bb-reorder.o' failed
make[1]: *** [bb-reorder.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:4105: recipe for target 'all-gcc' failed
make: *** [all-gcc] Error 2
Error compiling '/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/obj/nocona/gcc'

npm ERR! Linux 3.18.6
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v2.4.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE
npm ERR! nodeos-cross-toolchain@0.0.0 install: `scripts/build`
npm ERR! Exit status 33
npm ERR!
npm ERR! Failed at the nodeos-cross-toolchain@0.0.0 install script 'scripts/build'.
npm ERR! This is most likely a problem with the nodeos-cross-toolchain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-cross-toolchain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /NodeOS/npm-debug.log
[ root@a67ed9c75d72:/NodeOS {nodejs_4} ]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.2-10ubuntu13' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
```

what was the error you got? I'm going to keep playing with this as the day goes on.

I honestly don't know anything about toolchains and stuff like that (yet) so I'm still learning here. one thing I used to do when I ran gentoo a long time ago was have the cross compiler and cross compilation libs right there in the os. what is the advantage to using a cross-compiler? I'm gonna try and see if I can't get it working with the ubuntu system compiler first.

**Comment by heavyk** [comment]
forgive my ignorance, but why not just use glibc instead of musl? it seems like it would have a higher chance of working... I know glibc is big, but we're not talking about *that* much of a difference here... a few mb of ram even on a mobile phono nowadays is nothing. embedders wanting to use NodeOS will certainly contribute this improvement.

the other idea I had is to get the coreos cross-compiler environment and use that. that would make your life a WHOLE LOT easier actually. I did this a long time ago for coreos when it came out. I added all the necessary ebuilds to get a minimal xorg-x11 running and just booted right into a fullscreen node-webkit instance. it's not that hard to do actually.

**Comment by heavyk** [comment]
well, I'm getting further along this time (I decided to try again with PLATFORM=docker) and now I get this error:

```
Making all in testsuite
Making all in sanitizer_common
In file included from /NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/libsanitizer/sanitizer_common/sanitizer_linux.cc:60:0:
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/x86_64-nodeos-linux-musl/include/sys/signal.h:1:2: warning: #warning redirecting incorrect #include <sys/signal.h> to <signal.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/signal.h> to <signal.h>
  ^
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc: In function 'bool __sanitizer::SetEnv(const char*, const char*)':
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:121:19: error: 'RTLD_NEXT' was not declared in this scope
   void *f = dlsym(RTLD_NEXT, "setenv");
                   ^
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:121:38: error: 'dlsym' was not declared in this scope
   void *f = dlsym(RTLD_NEXT, "setenv");
                                      ^
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc: In function 'void __sanitizer::InitTlsSize()':
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:166:41: error: 'RTLD_NEXT' was not declared in this scope
   void *get_tls_static_info_ptr = dlsym(RTLD_NEXT, "_dl_get_tls_static_info");
                                         ^
/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:166:77: error: 'dlsym' was not declared in this scope
   void *get_tls_static_info_ptr = dlsym(RTLD_NEXT, "_dl_get_tls_static_info");
                                                                             ^
Makefile:449: recipe for target 'sanitizer_linux_libcdep.lo' failed
make[4]: *** [sanitizer_linux_libcdep.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
Makefile:437: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
Makefile:307: recipe for target 'all' failed
make[2]: *** [all] Error 2
Makefile:11617: recipe for target 'all-target-libsanitizer' failed
make[1]: *** [all-target-libsanitizer] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:881: recipe for target 'all' failed
make: *** [all] Error 2
```

a quick [google](http://stackoverflow.com/questions/1777397/rtld-next-undeclared) says that `__GNU_SOURCE` needs to be defined. 

where did your errors begin?

**Comment by piranna** [comment]
> I got a segmentation fault in my compiler.

This is mostly due to an out of memory error. Are you generating it insidea virtual machine?


> what was the error you got? I'm going to keep playing with this as the day goes on.

For each gcc version I got a different error, but for 5.2.0 (the latest one) in particular, that `dlsym` and `RTLD_NEXT` were not defined, while it should be done by musl...


> I honestly don't know anything about toolchains and stuff like that (yet) so I'm still learning here.

I'm not an expert, too... ;-)


> one thing I used to do when I ran gentoo a long time ago was have the cross compiler and cross compilation libs right there in the os. what is the advantage to using a cross-compiler?

Mostly, isolate the build process from the system installed libraries and tools and make it easier to use since people don't need to install (almost) any more, just exec `npm install` and the build process gets into auto-pilot mode :-) Also the cross-compiler makes it easier to port to another platform like ARM processors.


> why not just use glibc instead of musl?

Originally we were using glibc, but when building the cross-compiler I found it was an absolutely PITA to compile, specially for a from scratch system. musl was already on the roadmap both for size issues (glibc is 4x bigger) but also for performance, so I give it a try and it was easier to make it work (something similar happened with the bootloader, I wanted to use GRUB but it's almost impossible to compile and install it without root permissions, while syslinux is specifically designed for this use case and it's simpler to configure, so it's a win-win situation). There are some problems later with some libraries, but that's mostly because they use GCC extensions without checking them first instead of follow ANSI C standards, so it's a bug on their side.


> I added all the necessary ebuilds to get a minimal xorg-x11 running and just booted right into a fullscreen node-webkit instance. it's not that hard to do actually.

Interesting... I wanted to use raw content_shell over EGL to get the best performance and don't need to add the bloatware that's X11, but if you got it working easily maybe it would be a simpler milestone to keep moving forward on the graphic part...


> I decided to try again with PLATFORM=docker

Docker support needs a lot of love, be adviced... ;-)


> a quick google says that __GNU_SOURCE needs to be defined.
> 
> where did your errors begin?

I got just to the same point :-) `__GNU_SOURCE` shouldn't be necesary since [it's already supported](https://fossies.org/dox/musl-1.0.5/dlsym_8c.html)... :-/ That's why I was tinking about replaced (at least for testing) part of the cross-compiler with the one from musl-cross, since this should work with it.

If so, where should the flag be set?

**Comment by heavyk** [comment]
> Are you generating it insidea virtual machine?

nope it's a real machine. it's a docker instance of ubuntu. it has 16GB -- `KiB Mem:  16186500 total,  9616272 used,  6570228 free,   482404 buffers`

I'll have a look to be sure I'm not limiting the memory or something. I think it's ok though. 

> For each gcc version I got a different error, but for 5.2.0 (the latest one) in particular, that dlsym and RTLD_NEXT were not defined, while it should be done by musl...

I did some looking and I found this. I'm gonna try this version and see how it goes.

https://github.com/bminor/musl.git

as for defining  `__GNU_SOURCE `, it sounds like a bigger problem with what I've seen so far. I dunno yet

**Comment by heavyk** [comment]
holy shit this stuff is way over my head right now.

how do you debug this stuff? are you just running the scripts manually?

**Comment by piranna** [comment]
> Are you generating it insidea virtual machine?
> 
> nope it's a real machine. it's a docker instance of ubuntu. it has 16GB -- KiB Mem: 16186500 total, 9616272 used, 6570228 free, 482404 buffers

It's strange, It should be far enough with just only two gigabytes... :-/


> how do you debug this stuff? are you just running the scripts manually?

Welcome to the jungle... }:-D

I've put a different error code for each operation, so when build fails, by combining the script path and the error status you can see what's the command that failed and get an idea what's happened.

**Comment by heavyk** [comment]
ok, got the toolchain to build. node had some errors as well. I've nearly got it

**Comment by piranna** [comment]
> ok, got the toolchain to build

With gcc 5.2.0???


> node had some errors as well

Maybe, it's a big project and has embeded a lot of libraries. Just a note: if you are using Node.js 4.1.0 you don't need to apply the patch for OpenSSL, since now it support musl. Hope it helps...

**Comment by DeanHristov** [comment]
Hi, guys. When this OS will be support EcmaScript 6 and can I use EcmaScript6 with some compiler as BabelJS?

**Comment by piranna** [comment]
Fixed in master using Node.js 4.3.1, clossing. Thank you for opening the path @heavyk :-)

**Comment by heavyk** [comment]
hey dude, sorry for so much silence... things were crazy... I'm glad I could be of some help and really glad to see everything has worked out too!!

I read your blog... looking back at it, it seems so obvious now about it needing `/dev/*` so loading it in tmpfs would obviously be necessary -- duh. dunno why it didn't occur to me then :(

glad to hear the progress and I'll be trying it out real soon. cheers!
