### ISSUE TITLE
Could not find userfs [Error: /dev/sdb2 not exists]

### ISSUE THREAD

**Issue by xerox95** [NodeOS/NodeOS#175]
I try to run NodeOS.

i become the error: Could not find userfs.

Host OS is Ubuntu 15.10,
I Downloaded the pre build iso and run QEMU (run.sh in Prebuild image)

**Comment by piranna** [comment]
From what date are you using the prebuild image?

**Comment by lite20** [comment]
When I got this error, entering in the location "./dev/sdb" worked. Looks like userfs isn't always at sdb2. Should sdb be checked?

**Comment by piranna** [comment]
Yes, partitions should be to detect by their UUID instead of using one hardcoded, but I'm not really sure how to do it... :-/ What image are you using? `/dev/sdb` should not be used, maybe there's a bug on the start script...

**Comment by lite20** [comment]
I'll see what I can do.

> What image are you using?

I'm afraid I can't remember, but I'll try out the new edition and if it's still an issue, I'll try and fix and make a PR.

**Comment by piranna** [comment]
Test with the new one and tell me if there are updates. Also next time remenber to look the prompt to know what's the module that has failed.

**Comment by lite20** [comment]
The new one was able to detect  :) although login took an awfully long time to kick, and never did show up when I ran a 32bit QEMU (my system is 64). What run's between "I'm a user init script :)" and the logon?

**Comment by piranna** [comment]
> What run's between "I'm a user init script :)" and the logon?

There shouldn't run anything, hum... :-/ The other day I got something similar, where the 64 bits images didn't finished booting. I cleaned up everything and build them again and now it worked... definitely we need to improve the tests.

**Comment by lite20** [comment]
Everything here now works cleanly. Closing

**Comment by lite20** [comment]
@xerox95 it appears that this issue has been resolved. Please do consider closing the thread unless you encounter more errors (in which case we would love to help you resolve them :) ).
