### ISSUE TITLE
Poweroff and reboot

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#176]
Allow to listen on the machine phisical buttons and do a clean poweroff and reboot (sync disk, send SIGKILL...). This is not against the idea that anyone could pull the cord in any moment so developers should design their apps accordingly, but since anyone that has access to the phisical buttons has phisical access to the machine and can do whatever he wants, at least let's do thing well...

**Comment by piranna** [comment]
I've found when using `Ctrl + Alt + Sup` on the NodeOS terminal the system automatically reboots as it's done in regular systems, so maybe it's done at kernel level... It's something, but we'll need to update `century` so it can be able to send `SIGTERM` to the process so they can end cleanly.

**Comment by lite20** [comment]
> `Ctrl + Alt + Sup`

What is this `Sup` key you speak of?

> we'll need to update century so it can be able to send SIGTERM to the process so they can end cleanly.

Sounds like a good idea.

**Comment by piranna** [comment]
> What is this Sup key you speak of?

`Sup` is the spanish translation of `Del`, sorry :-P

**Comment by lite20** [comment]
> > What is this Sup key you speak of?

> Sup is the Spanish translation of Del, sorry :-P

It all makes sense now. XD What is the status of docker by the way?

**Comment by piranna** [comment]
> What is the status of docker by the way?

[There's a bug on tar-stream](https://github.com/mafintosh/tar-stream/issues/44) that generate `tar` files that Docket can't be able to process, so no Docker images by the moment, only vagga, sorry.

**Comment by lite20** [comment]
> There's a bug on tar-stream that generate tar files that Docket can't be able to process, so no Docker images by the moment, only vagga, sorry.

All good. I was just curious to see if I could create a new dev environment.

**Comment by piranna** [comment]
nodeos-init now cleanly manages Ctrl+Alt-Del, so I'm clossing this one. It's needed [to force unresponding processes](https://github.com/piranna/nodeos-init/issues/1), though...
