### ISSUE TITLE
NSH command loader

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#182]
As we all know, bash searches and fetches commands. Instead of modifying the bash file to support the new command.

I suggest we implement a similar system with NSH. There are multiple ways it could be implemented. The easiest would be to have a commands folder, and have all commands in that folder. When a user executed a command we could run the corresponding file in the folder (assuming that they won't always be nodejs files. Gotta stay open to whatever the end users might need.) That system is pretty capable and would prevent a lot of rewrites. Optionally, we could hook into js files via some pre-designed interface.

There are multiple ways to do this, that's just one suggestion. Open for feedback!

**Comment by piranna** [comment]
I think you've missed the point... currently there's already a "commands folder", it's `/bin` :-) Other thing are build-ins, that I plan to use [coreutils.js](https://github.com/piranna/coreutils.js/tree/master), and for the executables $PATH I plan to use [npm-path](https://github.com/timoxley/npm-path) so it gets to be dynamic. I don't think we need a command loader at all... Or I have missed something?

**Comment by lite20** [comment]
Nope, I actually got an updated QEMU setup and noticed the bin folder. I might have to look over my other issues and see if they're already resolved XD. 

Haha thanks!

**Comment by piranna** [comment]
You are welcome :-)

**Comment by lite20** [comment]
Oh my! We're online at the same time! XD I'm going on  irc

**Comment by piranna** [comment]
I'm not into IRC, do you use hangout chat?

**Comment by lite20** [comment]
Yeah! Email me at lite260@gmail.com (my work email) and I'll send you my hangouts email :P

**Comment by piranna** [comment]
invited :-)
