### ISSUE TITLE
HTML 5 - remote GUI  ?

### ISSUE THREAD

**Issue by Coretool** [NodeOS/NodeOS#185]
I got a question about your latest commit: Does this now mean that nodeos is going to have a remote gui ?

**Comment by piranna** [comment]
In the core itself no, and will never have an official one. If you look at the changes, it's only installing two packages and the internal NodeOS structure is untoched... The point is there's too much interest of having a GUI, so this changes are a somewhat initial "official" support so there could be some coherence and common structure between the different alternatives and don't have problems in the future about using particular features of a system ;-)

**Comment by Coretool** [comment]
Ok... I was a bit confused there vecause you said that you don't want a remote gui thingy!

**Comment by Coretool** [comment]
BTW: is there a up to date roadmap or todo list ?

**Comment by piranna** [comment]
> Ok... I was a bit confused there vecause you said that you don't want a remote gui thingy!

Oh no, I didn't say that! What I don't want is a local "native" GUI where the graphical apps has direct access to the Node.js APIs, but instead have them separate. A pure HTML5 graphical interface that connect to a local or remote NodeOS server is OK.


> is there a up to date roadmap or todo list ?

There are still some pending issues for final 1.0 at https://github.com/NodeOS/NodeOS/issues/37, but the new roadmap is available at https://github.com/NodeOS/NodeOS/issues/146

**Comment by lite20** [comment]
Quote from another thread:

The beta of Yunitto has been released on npm. It supports only browser's at the moment. It's a super easy module that'll take complete care of the rendering layer and differences between interfaces. WM Dev's, go ahead and start hacking away! (yes it has been tested. Please report every issue on the issues threads)

**Comment by lite20** [comment]
Closing for ended conversation.
