### ISSUE TITLE
Yunitto

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#186]
So after the contemplation, research and advice I've received, I've begun what we can call the first implementation of a rendering solution for NodeOS.

I've begun developing Yunitto for the following reasons:
- > Developers would be able to render to any interface with any interface (supported of course)
- > Developers can implement once, and render to multiple destinations (backends)
- > Backends can easily be updated without having to touch client code. (Gain without pain)

Yunitto is a unique rendering system. It uses a client <-> server interface, where applications (referred to as clients) connect to the server using the client module. You will be able to render to Yunitto by different intefaces. I will first implement the Canvas API, (as much as possible from the latest W3 specification), and then an HTML interface, and an interface I designed a while back named FFluid. 

Here's an outline of Yunitto's design.

- > Yunitto server starts
- > A Yunitto backend hooks in to Yunitto. For example, Yunitto-framebuffer or Yunitto-browser.
- > A client connects to Yunitto and starts rendering.

If a specific backend was not requested by the client, Yunitto will automatically route the request to the default backend which is the first of not otherwise configured.

I've began development at https://github.com/lite20/Yunitto

Feedback is appreciated! If you'd like to contribute, just make a pull request! (after a few PR's, I'll just give access to the alpha branch). 

P.S. If you're creating a window manager or desktop environment, you can implement this in so many ways. You might want to use a Yunitto-browser interface so you don't have to change your code! You would simply launch the browser back-end on the same device as the server, and then in your browser, point iframes to the URLS of the client's.

P.P.S Yunitto is Japanese for unit :smile:

**Comment by piranna** [comment]
Congrats, you've reinvented X11 :-D That's not a bad idea by itself, though... I like more to push the graphic rendering and all the possible CPU operations to the client instead of doing them on the server, but maybe that would be a good solution too, keep working ;-)

**Comment by Coretool** [comment]
Hey! That sounds good ! Can I help you? I tried building a GUI myself (as you may know) :)

**Comment by lite20** [comment]
> you've reinvented X11

I tried to avoid mentioning it but yes. It's x11 all over again. But let's do it right this time haha.

> I like more to push the graphic rendering and all the possible CPU operations to the client instead of doing them on the server.

Well I guess a back-end could be written to do exactly that no? I did imagine that it a lot of cases the server and client would be the same device, but in the case that they aren't, Yunitto is capable of client side rendering.

**Comment by sidorares** [comment]
one thing X11 lacks is "client side scripting" extension ( Its possible to create it using standard extensions mechanism but I have not seen anyone trying to start implementing anything similar ) In X11 all interactive logic always happen on the client, and all input comes from display server server so even simple things like "change button color on hover" require network roundtrip - this is different from webpage/web server architecture where you usually script those type of logic on the web page ( x server side in x11 world analogy )

**Comment by lite20** [comment]
> one thing X11 lacks is "client side scripting" extension ( Its possible to create it using standard extensions mechanism but I have not seen anyone trying to start implementing anything similar ) In X11 all interactive logic always happen on the client, and all input comes from display server server so even simple things like "change button color on hover" require network roundtrip - this is different from webpage/web server architecture where you usually script those type of logic on the web page ( x server side in x11 world analogy )

Do you have a suggestion of what we should do differently? @sidorares Erecting a issue thread on the Yunitto repository would be awesome for discussing this :smile:

**Comment by sidorares** [comment]
You'll need to add some kind of compatibility layer ( x11, vnc, rdesktop, Mir etc ) if you going to use different protocol

**Comment by piranna** [comment]
@lite20, your focus (and X11, by the way) os on "thin clients", while mine is more focused on "fat clients". Web browsers today are more than capable to do anything and client CPUs are really powerful, not the same situation of 20-30 years ago. That's why I try to put as much as possible CPU processing on the client side and use "dumb servers" instead of "dumb terminals", reducing costs on the server side. Also, if you plan to exec both server and client on the same machine, what one of them do the thing is not relevant since they are using the same CPU... :-)

**Comment by derhuerst** [comment]
@piranna Why not let the client do everything and let it access just the system resources over an api?

For example, i might imagine having a client app (html5, native, whatever) CRUDing files over http, reading from device files (and similar stuff) over WebSockets.

This way there is no distinction between a stand-alone app and apps inside a client. in the first case, the app talks to the nodeos machine directly and in the latter case, it gets the necessary connections from the client.

**Comment by piranna** [comment]
I had somewhat the same idea that @derhuerst :-)

**Comment by Coretool** [comment]
And I the but you were working on something like that ^^ Should have read all the issues on this topic !

**Comment by lite20** [comment]
> Why not let the client do everything and let it access just the system resources over an api? So don't put any "displaying logic" on the server.

Makes sense. I can do that ^_^

**Comment by lite20** [comment]
> @lite20, your focus (and X11, by the way) os on "thin clients", while mine is more focused on "fat clients". Web browsers today are more than capable to do anything and client CPUs are really powerful, not the same situation of 20-30 years ago. That's why I try to put as much as possible CPU processing on the client side and use "dumb servers" instead of "dumb terminals", reducing costs on the server side. Also, if you plan to exec both server and client on the same machine, what one of them do the thing is not relevant since they are using the same CPU... :-)

Ah the Yunitto module will do graphic processing on the server, if the script runs on the server. A js file can be linked and used for browser-based implementation so that rendering is done on the client. Yunitto itself does nothing but route graphic maps from clients, to back-ends, and make an easy interface to hook them all together. Whether they be apps running remotely, or on the server. So all the processing does happen on the client. They are fat clients :stuck_out_tongue:, however I left the option for the client to be scripted in nodejs, or in normal js.

**Comment by lite20** [comment]
> Why not let the client do everything and let it access just the system resources over an api? So don't put any "displaying logic" on the server.

The reason I have the client do most of the processing, and not everything (that would mean routing the maps to their back-ends) is because I'm trying to leave the ability for the rendering surface to be anything people intend to implement. Doing everything on the client would require the render surface to also be on the client, which won't always be the case. Doing it via this interface, allows different kinds of back-ends to be easily implemented. :smile:

**Comment by piranna** [comment]
> which won't always be the case

Could you be able to give us an example, and tell us why the client could not be able to do the routing on that situation?

**Comment by lite20** [comment]
> Could you be able to give us an example, and tell us why the client could not be able to do the routing on that situation?

The Yunitto router requires ports. That's the big reason why I didn't think of making a client implementation. "clients" which I assume are what you are calling a browser connecting to the system are actually back-ends to Yunitto. Yunitto would receive a packet from the client (the application) and forward it to the backend (browser). If the router is run on the client, backends and clients need to connect to it which isn't do-able on devices like phones. (ports are often closed) and on multiple computing devices.

If the application is to render to a browser, and is being executed in that browser, packets shouldn't pass through Yunitto. Because that'd be an unnecessary round-trip. I will remember that in my implementation of Yunitto. Maybe that's an improvisation right there.

If someone can create a yunitto router that runs on connecting devices, I will most gladly include it in the Yunitto releases

**Comment by Coretool** [comment]
What do you mean by "connecting devices" ?

**Comment by lite20** [comment]
> What do you mean by "connecting devices" ?

Any device that isn't the host (aka "server" device). If I connected via my phone, my phone would be the connecting device @Coretool :smile:

**Comment by lite20** [comment]
I should probably explain why I'm closing . While working on Yunitto it dawned on me the way it handled the backends. Yunitto provided a back-end rendering system and handled displays, however the only module that should be writing to it is the display manager.

This is because this display manager needs to manage what and where windows and their respective data are being rendered. Because of that, Yunitto should be baked into window managers. I will continue to develop it as a module for window manager developers but because it's only a module now for the window managers and not directly a node-os specific module, I'll be closing this thread.

Do look into the new thread to help us discuss the protocol for rendering with window managers.
