### ISSUE TITLE
Use a simple standalone C init command

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#190]
As [suggested](https://github.com/NodeOS/NodeOS/issues/187#issuecomment-164025249) by @Xe, we could use a simple C init command like [sinit](http://core.suckless.org/sinit) as `PID 1`. This could be a workaround to the v8 problem that prevents to use newer versions of Node.js than the v0.11.14. This way the system will not be so "Javascript pure" and maybe not so *nice* to have a Node.js REPL as `/init` on the barebones layer, but the advantages would be bigger, and if we remove the usage of [century](https://github.com/groundwater/node-century) (since it's done just the same things that `sinit`), then we could earn some memory space by not having an idle v8 instance running on the system :-)

**Comment by lite20** [comment]
Why not give this a shot? Of course I wouldn't know where to start with this, but you might and you could give me directions.

**Comment by piranna** [comment]
Could sound pretentious... but I've also started this too :-P It doesn't works since needs some testing (maybe I was too ambitious?), but I can be able to upload tomorrow my current code if you want :-)

Just a question: is there a good and simple C testing framework sonewhere?

**Comment by lite20** [comment]
> Could sound pretentious... but I've also started this too :-P It doesn't works since needs some testing

Ah I see. I will take a look. I can't say my C skills are very polished but I will try my best.

> Just a question: is there a good and simple C testing framework sonewhere?

https://cmocka.org/

A quick google search brought up this however I haven't worked with it. Frankly, I don't test my C code as I don't often write any. However this looks like a fairly nice system.

**Comment by piranna** [comment]
>> Could sound pretentious... but I've also started this too :-P It doesn't
works since needs some testing
>
> Ah I see. I will take a look. I can't say my C skills are very polished
but I will try my best.

I'll upload it tomorrow :-)

>> Just a question: is there a good and simple C testing framework
sonewhere?
>
> https://cmocka.org/
>
> A quick google search brought up this however I haven't worked with it.
Frankly, I don't test my C code as I don't often write any. However this
looks like a fairly nice system.

I've just done the same quick search :-D Seems easy, but I'll need to look
it in detail since I've  never tested my C code too :-/ At least Travis CI
support it... :-)

**Comment by lite20** [comment]
> At least Travis CI support it... :-)

Oh! Haha okay awesome!

P.S. made a PR for updating the readme

**Comment by piranna** [comment]
Ok, so I forgot I had uploaded one month ago... :-P

https://github.com/piranna/nodeos-init

I need to review it and make it work, though :-)

**Comment by piranna** [comment]
I've just uploaded a new version, I was not be able to test it on NodeOS and don't know if I will be able to find time this weekend, but at least now it can be used by regular users and seems it doesn't enter in an infinite loop :-P If you want you can take it a look, maybe it would be cleaner or has a better organization but in any case it's a really good piece of cake :-D If you are interested you could be able to give it a look for the tests or the docs... :-)

**Comment by lite20** [comment]
> I've just uploaded a new version, I was not be able to test it on NodeOS and don't know if I will be able to find time this weekend, but at least now it can be used by regular users and seems it doesn't enter in an infinite loop :-P If you want you can take it a look, maybe it would be cleaner or has a better organization but in any case it's a really good piece of cake :-D If you are interested you could be able to give it a look for the tests or the docs... :-)

Fantastic! I'll surely take a look at this and additionally document it if I can find time. Are there any current known issues with the program?

**Comment by piranna** [comment]
> Fantastic! I'll surely take a look at this and additionally document it
if I can find time. Are there any current known issues with the program?

Besides untested on NodeOS, none that I could tell... It just exec another
command and waits to all child processes to exit so it can try to shutdown
the machine, no more.

**Comment by piranna** [comment]
I've tested it on NodeOS and seems to work since the vkrtual machine exists correctly when the prompt ks finished :-) Unfortunately it seems it only works shen compiled statically, so it would need the toolchain to be updated to generate the static libraries, it not I get the "init not tainted" error... :-/ Don't know if we could accept this special case, but the truth is that using Node.js dynamically linked as init there's no problems... :-/

**Comment by lite20** [comment]
> Node.js dynamically linked as init there's no problems... :-/

could you explain what you mean by this?

**Comment by piranna** [comment]
That by using a dynamically linked Node.js executable I can be able to use
it (up to 0.11.14, obviously), but by some reason, nodeos-init only works
correctly when statically linked, when used dynamically it give the not
tainted error and raise a kernel panic on exit (but curiously it exec the
Node.js symlink at /sbin/init instead...).

**Comment by piranna** [comment]
I have just checked it and having the `init` in an independent command don't fix [the v8 problem](https://github.com/NodeOS/NodeOS/issues/187), so we need to still stick with Node.js v0.11.14 :-( It at least close nicely the virtual machine instead of [hang](https://github.com/NodeOS/NodeOS/issues/90) [out](https://github.com/NodeOS/NodeOS/issues/180), but anyway it's a shame... :-(

**Comment by piranna** [comment]
Ok, the problem with the dynamically linked init was related that nodeos-init was being compiled with my Ubuntu machine gcc and glibc instead of NodeOS cross-compiler, so now that I've fixed it I've pushed it to master.Unluckily there's still the problem with v8, but since it has its own issue I'm going to close this one.
