### ISSUE TITLE
Use QEmu nomenclatures

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#199]
Use QEmu nomenclatures to designate platforms, machines and cpus, and use them to get correct default values when generating the different system images. This would be more clear and simple to manage that the current one.

**Comment by lite20** [comment]
What exactly do you have in mind when you suggest this? Wouldn't mind taking a chip at it! :D

**Comment by piranna** [comment]
To make it a little bit easier to port to other platforms, use the same machine, cpu and architecture names used by QEmu, so not only there's a 1:1 relationship with it when tested but also there's an already clear defined nomenclature about what means each thing, so it would lead to less confusion.

**Comment by lite20** [comment]
> To make it a little bit easier to port to other platforms, use the same machine, cpu and architecture names used by QEmu, so not only there's a 1:1 relationship with it when tested but also there's an already clear defined nomenclature about what means each thing, so it would lead to less confusion.

Ah okay, that makes sense.

**Comment by lite20** [comment]
I believe we do this, so closing.

**Comment by piranna** [comment]
This is not yet scheudled, and probably it will not be after 1.0.0 because it needs breaking changes affecting several projects in a lot of places.

**Comment by lite20** [comment]
Ah okay. Thanks for the correction

**Comment by piranna** [comment]
Fixed in master, clossing.
