### ISSUE TITLE
Init scripts

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#203]
Does NodeOS already have a utility to launch applications that need to begin on start up? If there is one, does it have an interface for apps to add or remove themselves from this list? I'm thinking of people who run servers for testing (like redis) or for GUI users, messengers and such.

**Comment by piranna** [comment]
There's no specific utility, but if there's a '/init' executable on the
root of a user $HOME it gets executed, so you can put there a symlink to
any command the user want to exec at boot time, for example the utility you
are asking about :-) nodeos user has a demo script that prints on the
console, but root user use instead 'forever' to start both logon for the
virtual terminals and exclfs for /dev.

On the other hand 'forever' is too big, so I was thinking to develop a
tasks starter that uses directly the json format used by ndm. It would be
an easy and funny task, so if you are interested... :-)

**Comment by lite20** [comment]
> On the other hand 'forever' is too big, so I was thinking to develop a
tasks starter that uses directly the json format used by ndm. It would be
an easy and funny task, so if you are interested... :-)

Why not? Give me a quick blue print of what you have in mind. You're thinking a task launcher/scheduler to replace forever?

**Comment by piranna** [comment]
>You're thinking a task launcher/scheduler to replace forever?

Yes, that's it. Something small focused only on start commands configured
on json files and restart them when they finish, without a cli or a socket
to manage them while running (if needed, this could be done later by using
ndm).

**Comment by piranna** [comment]
You have ndm at https://github.com/npm/ndm. I think we could be able to
reuse the format of the 'service.json' file and the 'service' field they
added to 'package.json', although it seems to ne that the docs are
outdated, they added support for single servers some time ago and the docs
sah nothing...

**Comment by Coretool** [comment]
What about forever-monitor ? It's forever without a cli ^^

**Comment by piranna** [comment]
> What about forever-monitor ? It's forever without a cli ^^

In fact is what we are using ;-) But it's still to heavyweight since it
retains all the forever functionality that we are not needing.

**Comment by Coretool** [comment]
Ah, ok

**Comment by lite20** [comment]
> Yes, that's it. Something small focused only on start commands configured on json files and restart them when they finish, without a cli or a socket to manage them while running (if needed, this could be done later by using ndm).

Okay I will create this today or latest tomorrow (if my parents take my stuff or something)

**Comment by piranna** [comment]
Ok, keep me informed as soon as you start on it so we can work together. I
think you could take as basis both the ndm format and the
forever-starter.json file available on NodeOS source code.

**Comment by piranna** [comment]
I think it could be created a class to monitor a single command and start
it and keep it running, and later create instances of that Monitor class
from the info on the json file, how do you see it?

**Comment by lite20** [comment]
> Ok, keep me informed as soon as you start on it so we can work together. I
think you could take as basis both the ndm format and the
forever-starter.json file available on NodeOS source code.

Alright I'm getting started now. I'll create a repository on Github and give you access.

> I think it could be created a class to monitor a single command and start
it and keep it running, and later create instances of that Monitor class
from the info on the json file, how do you see it?

Yes this seems reasonable. However I was hoping we could create something where we can start and stop services. (commands launched) and list them. For this to work smoothly we could just save all the started processes in a file when launched and create a command line tool for interacting with the monitor.

That'll allow us to easily stop started services instead of trying to track down the pID

**Comment by piranna** [comment]
> Alright I'm getting started now. I'll create a repository on Github and
give you access.

Thank you, I've received it :-)

>> I think it could be created a class to monitor a single command and start
>> it and keep it running, and later create instances of that Monitor class
>> from the info on the json file, how do you see it?
>
> Yes this seems reasonable. However I was hoping we could create something
where we can start and stop services. (commands launched) and list them.
For this to work smoothly we could just save all the started processes in a
file when launched and create a command line tool for interacting with the
monitor.
>
> That'll allow us to easily stop started services instead of trying to
track down the pID

I don't think this is the way to go, since we would be replicating
'forever'.

What we need on a first iteration is just start the processes on boot from
a json file, no more. This json file would be used to list what's currently
configured and what ones are enabled and could be edited by hand (KISS
principle ;-) ). I think this is just enough for a first iteration.

Later, if you want a cli we could use a modified version of ndm to update
that json file, that could also be used to list what ones of the enabled
tasks are in fact running (but we would need some way to get the processes
PIDs to check this). The remaining bits of your use case are starting new
tasks while system is running (not only on boot) and stop them. This would
need some way to comunicate with the tasks manager, so it would complicate
it and also don't know how much useful it would be on real world, so I
would not implement it or would made it optional for security issues (root
user will not need it anyways...).

**Comment by lite20** [comment]
Gotcha. Where would you like said JSON file storing all the services to be?
In the root home directory?

**Comment by piranna** [comment]
Let's put all config files in user /etc folder.

**Comment by lite20** [comment]
Alright I've pushed to the repo. How does it look?

For integration, would we replace that "Hi I'm a user init script" with this? Or bake it into the build process?

**Comment by piranna** [comment]
> Alright I've pushed to the repo. How does it look?

It's a good first approach. I have some suggestions:

* remove the `colors` dependency, it's just aesthetics and increase memory footprint
* don't write a default json file if not available, better throw an error
* processes don't get restarted automatically :-P


> For integration, would we replace that "Hi I'm a user init script" with this? Or bake it into the build process?

`PalmTree` would replace `forever` for the `root` user, but since `nodeos` is just an example one I would left the current script there. But yes, if someone would like to use `PalmTree` as its `/init`, yes it would replace it with a symlink :-)

**Comment by lite20** [comment]
> remove the colors dependency, it's just aesthetics and increase memory footprint

okay :(

> don't write a default json file if not available, better throw an error

Oh! It's just that I didn't expect it to exist on first run. Thought it might make it more robust if it's accidentally deleted but okay!

> processes don't get restarted automatically :-P

Yeah they don't... did you wan't them to be?

> PalmTree would replace forever for the root user, but since nodeos is just an example one I would left the current script there. But yes, if someone would like to use PalmTree as its /init, yes it would replace it with a symlink :-)

Ah okay. So it won't be an official package in NodeOS? D:

**Comment by piranna** [comment]
> remove the colors dependency, it's just aesthetics and increase memory footprint
> 
> okay :(

[KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [minimalism](https://en.wikipedia.org/wiki/Minimalism_%28computing%29). Don't think of it as something bad, in fact in UNIX style commands should not output any messages except if an error or bad behaviour happened, and in fact in my college they don't allow us to do it. You'll someday get the beauty on it ;-)


> Oh! It's just that I didn't expect it to exist on first run. Thought it might make it more robust if it's accidentally deleted but okay!

Yeah, but if it's get accidentally deleted, by adding a default one you are hidding an error! Is not better that the user get easily noticed that something were really wrong? :-P


> Yeah they don't... did you wan't them to be?

In fact, that's the main purposse of `forever` and the reason why we were using it, and the same still applies here... ;-) That's why I tell you before about crafting a monitor class to manage each process and keep it running... ;-)


> Ah okay. So it won't be an official package in NodeOS? D:

It will be if we use it to replace `forever`... ;-)

**Comment by lite20** [comment]
Okay, I've made the tweaks. How's that?

**Comment by piranna** [comment]
> Okay, I've made the tweaks. How's that?

Way far better ;-) Look? It was an easy one :-D Let's talk about optimizations and clean-up other day ;-)

One flaw I see is that you are not setting the `stdio` of the process so it will create a pipe by default, when its internal buffer gets filled the process will pause (It happened to me some weeks ago...), set it to `inherit` or better to `ignore`, and you should check for spawn `error` event, and would be good to set a min uptime so on failure it doesn't spin up undefinitely... :-) Oh, and some test would be cool if possible :-)

Just a last good trick: `require()` supports to load json files the same way it does for javascript ones, so you could be able to remove all the loading and checking and parsing code you have at the beggining ;-) That's awesome simple when you need to store some plain data on your package or load some config files, or also to load a module `package.json` file to fetch some of its metadata like the version number... :-D

**Comment by lite20** [comment]
> One flaw I see is that you are not setting the stdio of the process so it will create a pipe by default, when its internal buffer gets filled the process will pause

I did not know this... the doc's didn't say anything :stuck_out_tongue: 

> Just a last good trick: require() supports to load json files the same way it does for javascript ones, so you could be able to remove all the loading and checking and parsing code you have at the beggining ;-) 

Where do you learn this?? XD If only I knew this was a thing. Okay I'm making the changes.

**Comment by piranna** [comment]
> One flaw I see is that you are not setting the stdio of the process so it will create a pipe by default, when its internal buffer gets filled the process will pause
> 
> I did not know this... the doc's didn't say anything :stuck_out_tongue:

https://nodejs.org/api/child_process.html#child_process_options_stdio


> Just a last good trick: require() supports to load json files the same way it does for javascript ones, so you could be able to remove all the loading and checking and parsing code you have at the beggining ;-)
> 
> Where do you learn this?? XD If only I knew this was a thing. Okay I'm making the changes.

https://nodejs.org/api/modules.html#modules_file_modules

Yeah, I know, I need a life X-D

**Comment by lite20** [comment]
Would you mind implementing the require thing? I don't want to do it wrong D:

**Comment by lite20** [comment]
> https://nodejs.org/api/child_process.html#child_process_options_stdio
You just had to prove me wrong :stuck_out_tongue:. Well, it looks like I can't read!

**Comment by lite20** [comment]
@piranna Okay, so the script has been greatly shrunk since when we began :stuck_out_tongue: 

I've implemented the two deficiencies you noted. I've pushed to the repository and the code is available for revision.

**Comment by piranna** [comment]
> @piranna Okay, so the script has been greatly shrunk since when we began :stuck_out_tongue:

Why would we need more than this? :-)


> I've implemented the two deficiencies you noted. I've pushed to the repository and the code is available for revision.

You could be able to add an optional argument to set the location of the config file,  and use `forEach()` to cleanly iterate over the array. Also, the throw statement would crash the whole process, while you can get the same error on the `error` event of `spawn`. Besides that, it seems a good improvement :-)

P.S.: why did you generated a minified version?

**Comment by lite20** [comment]
> P.S.: why did you generated a minified version?
I was coding in brackets and it automatically minifies any JS for me (I configured it to do that)

**Comment by piranna** [comment]
> I was coding in brackets and it automatically minifies any JS for me (I configured it to do that)

It's a curious feature...

**Comment by lite20** [comment]
> It's a curious feature...

I don't generally use Brackets for back-end dev. (NodeJs). For front end, its highly useful to have my files automatically minified. Anyway, I've pushed the update

**Comment by lite20** [comment]
@piranna Just let me know when you've revised it :smile:

**Comment by lite20** [comment]
Bump :3

**Comment by piranna** [comment]
Yeah, I have this on my todo list, but since I've started as a contractor
last month I don't have almost time :-P Exactly what are you willing for,
that I review or test your code, or that I integrate it on NodeOS? This
last will take some more time, but you could do it youself and send a
pull-request too :-)

**Comment by lite20** [comment]
> Exactly what are you willing for,
that I review or test your code, or that I integrate it on NodeOS? This
last will take some more time, but you could do it youself and send a
pull-request too :-)

I'm waiting for permission to integrate it myself via PR ^_^

>  I've started as a contractor last month

Congrats!

**Comment by piranna** [comment]
You don't need permission, just checks it works :-) By far it seems ok to
me :-)

**Comment by lite20** [comment]
> You don't need permission, just checks it works :-) By far it seems ok to
me :-)

Forked. I've begun integrating ^_^

**Comment by piranna** [comment]
:+1:

**Comment by lite20** [comment]
**Error**
@piranna New errors, after compiling successfully for three hours D:

  LINK(target) /home/lite/Documents/lnodes/node_modules/nodeos-barebones/deps/node/out/Release/node
  LINK(target) /home/lite/Documents/lnodes/node_modules/nodeos-barebones/deps/node/out/Release/node: Finished
/usr/bin/env: node: No such file or directory

npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@0.0.0 install: `scripts/build`
npm ERR! Exit status 15
npm ERR! 
npm ERR! Failed at the nodeos-barebones@0.0.0 install script.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lite/Documents/lnodes/npm-debug.log

*debug log is massive. I can't paste the whole thing, so if it's even needed then mention.*

**Odness**
btw when I attempt to find the compiled "node" binary I do find a file, but for some reason when attempting to execute it, bash says it doesn't exist when it's clearly there. Is this a broken symlink?

*Me in the terminal:*

lite@lite-pc:~/Documents/lnodes$ cd node_modules/nodeos-barebones/deps/node/lite@lite-pc:~/Documents/lnodes/node_modules/nodeos-barebones/deps/node$ ls
android-configure  common.gypi      deps      node       test
AUTHORS            config.gypi      doc       node.gyp   tools
benchmark          config.mk        lib       out        vcbuild.bat
BSDmakefile        configure        LICENSE   README.md
ChangeLog          CONTRIBUTING.md  Makefile  src
lite@lite-pc:~/Documents/lnodes/node_modules/nodeos-barebones/deps/node$ ./node bash: ./node: No such file or directory
lite@lite-pc:~/Documents/lnodes/node_modules/nodeos-barebones/deps/node$

**Comment by piranna** [comment]
Can you send the output of `ls -l`? Maybe it's a permissions issue, since the `node` file is already there, but it's strange...

And yes, three hours... there's a lot of sh*t to compile here :-(

**Comment by lite20** [comment]
lite@lite-pc:~/Documents/lnodes/node_modules/nodeos-barebones/deps/node$ ls -l
total 356
-rwxrwxr-x  1 lite lite    498 Jan 23 20:52 android-configure
-rw-rw-r--  1 lite lite  21140 Jan 23 20:52 AUTHORS
drwxrwxr-x 10 lite lite   4096 Jan 23 20:52 benchmark
-rw-rw-r--  1 lite lite     61 Jan 23 20:52 BSDmakefile
-rw-rw-r--  1 lite lite 156813 Jan 23 20:52 ChangeLog
-rw-rw-r--  1 lite lite   8863 Jan 23 20:52 common.gypi
-rw-rw-r--  1 lite lite   1581 Jan 25 15:32 config.gypi
-rw-rw-r--  1 lite lite    124 Jan 25 15:32 config.mk
-rwxrwxr-x  1 lite lite  22702 Jan 23 20:52 configure
-rw-rw-r--  1 lite lite   4791 Jan 23 20:52 CONTRIBUTING.md
drwxrwxr-x 10 lite lite   4096 Jan 23 20:52 deps
drwxrwxr-x  4 lite lite   4096 Jan 23 20:52 doc
drwxrwxr-x  2 lite lite   4096 Jan 23 20:52 lib
-rw-rw-r--  1 lite lite  39874 Jan 23 20:52 LICENSE
-rw-rw-r--  1 lite lite  11695 Jan 23 20:52 Makefile
lrwxrwxrwx  1 lite lite     16 Jan 25 15:41 node -> out/Release/node
-rw-rw-r--  1 lite lite  18786 Jan 23 20:52 node.gyp
drwxrwxr-x  4 lite lite   4096 Jan 25 15:32 out
-rw-rw-r--  1 lite lite   2425 Jan 23 20:52 README.md
drwxrwxr-x  3 lite lite   4096 Jan 23 20:52 src
drwxrwxr-x 13 lite lite   4096 Jan 23 20:52 test
drwxrwxr-x 10 lite lite   4096 Jan 23 20:52 tools
-rw-rw-r--  1 lite lite   8077 Jan 23 20:52 vcbuild.bat

**Comment by lite20** [comment]
there is no 'out' folder to be found anywhere in the project tree...

**Comment by piranna** [comment]
> lrwxrwxrwx 1 lite lite 16 Jan 25 15:41 node -> out/Release/node
> drwxrwxr-x 4 lite lite 4096 Jan 25 15:32 out

That's really strange, the binary is correctly created... :-/ Error 15 is because test os Node.js binary is failling. Could you be able to exec `npm run testNode`? Also it would be good to have the output of `ls -l out` and `cat /proc/cpuinfo`, maybe you are having a rare CPU... :-/

Other culprit would be to have Node.js installed on `/usr/local/bin`, how did you managed to install it there? Have you installed it from sources or from the PPA? If you installed from sources I recomend you uninstall it and use the PPA:

```sh
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by lite20** [comment]
**test node**
> nodeos-barebones@0.0.0 testNode /home/lite/Documents/lnodes/node_modules/nodeos-barebones
> scripts/testNode

fs.js:905
  return binding.readlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, readlink 'out/latest'
    at Error (native)
    at fs.readlinkSync (fs.js:905:18)
    at processArguments (/home/lite/Documents/lnodes/node_modules/nodeos-barebones/scripts/processArguments.js:15:25)
    at Object.<anonymous> (/home/lite/Documents/lnodes/node_modules/nodeos-barebones/scripts/testNode:12:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)

npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "testNode"
npm ERR! node v5.0.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@0.0.0 testNode: `scripts/testNode`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeos-barebones@0.0.0 testNode script 'scripts/testNode'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/testNode
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodeos-barebones
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lite/Documents/lnodes/node_modules/nodeos-barebones/npm-debug.log

**ls -l out**
s-cross-toolchain$ ls -l out/
total 20
drwxr-xr-x 2 lite lite 4096 Jan 25 15:32 bin
drwxr-xr-x 3 lite lite 4096 Jan 25 15:32 lib
drwxr-xr-x 3 lite lite 4096 Jan 25 15:02 libexec
drwxr-xr-x 3 lite lite 4096 Jan 25 15:32 share
drwxr-xr-x 5 lite lite 4096 Jan 25 14:42 x86_64-nodeos-linux-musl

**cat /proc/cpuinfo**
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Core(TM) i3 CPU       U 330  @ 1.20GHz
stepping	: 5
microcode	: 0x1
cpu MHz		: 666.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm arat dtherm tpr_shadow vnmi flexpriority ept vpid
bugs		:
bogomips	: 2394.29
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Core(TM) i3 CPU       U 330  @ 1.20GHz
stepping	: 5
microcode	: 0x1
cpu MHz		: 666.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm arat dtherm tpr_shadow vnmi flexpriority ept vpid
bugs		:
bogomips	: 2394.29
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Core(TM) i3 CPU       U 330  @ 1.20GHz
stepping	: 5
microcode	: 0x1
cpu MHz		: 799.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 2
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm arat dtherm tpr_shadow vnmi flexpriority ept vpid
bugs		:
bogomips	: 2394.29
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Core(TM) i3 CPU       U 330  @ 1.20GHz
stepping	: 5
microcode	: 0x1
cpu MHz		: 1199.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 2
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm arat dtherm tpr_shadow vnmi flexpriority ept vpid
bugs		:
bogomips	: 2394.29
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

> Other culprit would be to have Node.js installed on /usr/local/bin, how did you managed to install it there? 

Oh there we go. Yes I have it there. No, I didn't install via sources. My attempts to get the legacy node binary in different versions resulted in that. So removing it should allow nodeos to build?

**Comment by piranna** [comment]
> ls -l out
> s-cross-toolchain$ ls -l out/
> total 20
> drwxr-xr-x 2 lite lite 4096 Jan 25 15:32 bin
> drwxr-xr-x 3 lite lite 4096 Jan 25 15:32 lib
> drwxr-xr-x 3 lite lite 4096 Jan 25 15:02 libexec
> drwxr-xr-x 3 lite lite 4096 Jan 25 15:32 share
> drwxr-xr-x 5 lite lite 4096 Jan 25 14:42 x86_64-nodeos-linux-musl

Well, I wanted the output on nodeos-barebones... :-P

> cat /proc/cpuinfo

Ok, seems here is not the problem. Just curious: what cpu is it? Seems to
be really slow, but being a quad core should be high end, but cores are
i3... curious mixture :-P

>> Other culprit would be to have Node.js installed on /usr/local/bin, how
did you managed to install it there?
>
> Oh there we go. Yes I have it there. No, I didn't install via sources. My
attempts to get the legacy node binary in different versions resulted in
that. So removing it should allow nodeos to build?

As far it's on the $PATH is should not give problems, I think something was
wrong on the build process. Did you compiled it from scratch, or did you
need to try it several times? If so, exec 'npm run unbuild' and later build
it again. Sorry, three more hours :-( but Star Wars VII is cool, so enjoy
it :-P

**Comment by lite20** [comment]
> Just curious: what cpu is it? Seems to
be really slow, but being a quad core should be high end, but cores are
i3... curious mixture :-P

I don't actually remember the name. It's a super old computer. I think it has the Intel Atom processor.

lite@lite-pc:~/Documents/lnodes/node_modules/nodeos-barebones$ ls -l 
total 40
drwxrwxr-x 4 lite lite 4096 Jan 23 20:52 deps
drwxrwxr-x 4 lite lite 4096 Jan 25 14:04 node_modules
-rw-rw-r-- 1 lite lite 3024 Jan 26 13:54 npm-debug.log
drwxrwxr-x 3 lite lite 4096 Jan 25 15:41 obj
-rw-rw-r-- 1 lite lite  546 Jan 23 20:53 package.json
-rw-rw-r-- 1 lite lite  302 Jan 23 20:52 README.md
drwxrwxr-x 2 lite lite 4096 Jan 23 20:53 resources
drwxrwxr-x 2 lite lite 4096 Jan 23 20:53 scripts
drwxr-xr-x 6 lite lite 4096 Jan 23 20:53 usr
-rw-rw-r-- 1 lite lite  205 Jan 23 20:53 vagga.yaml

There's the output! Re attempting build...

**Comment by piranna** [comment]
> I don't actually remember the name. It's a super old computer. I think it has the Intel Atom processor.

That makes sense...


> There's the output!

Well, in fact I wanted the output of `out` directory inside `nodeos-barebones`... :-P What I want to know is if the `latest` link is created and where is pointing to. In fact, it would be better to get the output of the `tree` command... Did you get any result with the rebuild?

**Comment by lite20** [comment]
>  Did you get any result with the rebuild?

Wasn't able to complete it. Hopefully I can get it going today.

**Comment by piranna** [comment]
Ok, please keep me informed, I'm curious to know what's happenning...

**Comment by lite20** [comment]
meanwhile, were you able to test the fork? It's up under my repositories and adds the init scripts. I haven't been able to test it yet but if you're free I'm assuming you wouldn't mind reviewing the integration

**Comment by piranna** [comment]
I'm a bit busy lately with my job, but also I'm working on other things on the project, but they are a secret ;-)

**Comment by lite20** [comment]
Now with PalmTree, this is one thing more off our list :)
