### ISSUE TITLE
Magical Disappearing Toolchain

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#204]
So I attempted to compile nodeos to test the PalmTree addition. (attempt is the key word in that sentence).

After it completes downloading what seemingly is a billion modules, the build sequence then proceeds to build nodeos-barebones. To it's dismay, the "nodeos-cross-toolchain" module is missing!

I was a little surprised. I git reset, and checked to see if it was there in the first place which it was. I ran the build process again, and I hit the same error.

It seems that the build process removes the nodeos-cross-toolchain module. It's there before compilation, and gone after. Does the install script attempt to install a newer version which doesn't contain the toolchain, and then fails when attempting to use it? Happy to feed off whatever logs you may request!

npm debug log: http://paste.ubuntu.com/14626927/

error spit out:

> nodeos-barebones@0.0.0 preinstall /home/lite/Documents/lnodes/node_modules/nodeos-barebones
> scripts/preinstall

> nodeos-barebones@0.0.0 install /home/lite/Documents/lnodes/node_modules/nodeos-barebones
> scripts/build

scripts/build: line 13: /home/lite/Documents/lnodes/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/scripts/adjustEnvVars.sh: No such file or directory

npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@0.0.0 install: `scripts/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeos-barebones@0.0.0 install script 'scripts/build'.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lite/Documents/lnodes/npm-debug.log

**Comment by piranna** [comment]
> npm ERR! node v500
> npm ERR! npm v336

Just with the issue title supposed the problem was here :-P npm3 is the
guilty, by not reason is removing it, and will need a lot of work to change
the way how NodeOS is build (this will be after 1.0 release). Please use
npm2, that's still available on Node.js 4.x.x.

**Comment by lite20** [comment]
What version of node is needed? I downgraded as suggested and now I'm hitting new errors.

Error: http://paste.ubuntu.com/14654490/

**Comment by piranna** [comment]
Node.js version is not so important as the npm version, that should be the
latest one on the 2.x.x branch. If you install the latest Node.js on the
4.x.x branch you should be ok, that's what I'm using.

**Comment by lite20** [comment]
:/ build server ran out of memory trying to compile. Idek what specs were
on that thing but I guess I'll lose another three hours sometime soon.

**Comment by piranna** [comment]
> :/ build server ran out of memory trying to compile. Idek what specs were
> on that thing but I guess I'll lose another three hours sometime soon.

It's sad to heard that :-( I need to do some work, but I'll try to review
it this afternoon. Until that, reboot the machine try to compile it again
:-/

Memory issues are probably related to the decompress module, since it load
the full file in memory instead of stream it. Also it's strange it spend so
much time compiling being a quad core... Are you using a virtual machine to
compile it?

**Comment by lite20** [comment]
No its being compiled off bare metal. I was a little surprised to. Usually
computer doesn't struggle with compiling.

**Comment by piranna** [comment]
> No its being compiled off bare metal. I was a little surprised to. Usually
> computer doesn't struggle with compiling.

Gcc, Linux, Node.js and QEmu are HUGE projects to compile, also configuring
them to don't compile useless things...

**Comment by lite20** [comment]
> Gcc, Linux, Node.js and QEmu are HUGE projects to compile
Wait, it compiles QEMU? Why?

I wish I could use a prebuilt barebones layers and just build the rest.

**Comment by piranna** [comment]
>> Gcc, Linux, Node.js and QEmu are HUGE projects to compile
>> Wait, it compiles QEMU? Why?

Not all of it, only i386 and x86_64... I was using the one from Uvuntu, but
since Microsoft is working on some patches for adding Raspberry Pi 1 & 2 as
native platforms and also the version included on Ubuntu 14.04 is outdated,
then I decided to download and compile it.

> I wish I could use a prebuilt barebones layers and just build the rest.

You can be able to download one on the prebuild images and use it as basis,
problem is how to craft the other layers independently... This should be
possible when we split the layers on independent modules and port them to
npm3 and its flat hierarchy, but it's a lot of work and should be done
after a stable 1.0 release, so without help I don't think it would be
possible until summer :-(

**Comment by lite20** [comment]
> so without help I don't think it would be
possible until summer :-(

...

> without help

... :3 we're here.

Some things I've noted about the build process through my many attempts:
1) Node needs to be less, than five but greater than four.
2) Npm needs to be less than three, but greater than two.

Without those, the build doesn't even get five minutes in. Ubuntu's repo doesn't contain a nodejs and npm that meet these standard so Ubuntu users have a bit more work to do to compile NodeOS.

**Comment by piranna** [comment]
> so without help I don't think it would be
>     possible until summer :-(
> 
> ...
> 
>     without help
> 
> ... :3 we're here.

Don't take it that way... I know you and others are there, but I'm nobody to ask anybody to do this or that, just only manage what anyone volunteer wants to do. I must to admit that I should have a to-do list somewhere so people could know what tasks can work with, but I can't be able to tell anybody what to do with his spare time :-/


> Some things I've noted about the build process through my many attempts:
> 1) Node needs to be less, than five but greater than four.
> 2) Npm needs to be less than three, but greater than two.

Currently Node.js needs to be greater than 0.12 and npm needs to be less than three, that correspond to Node.js 4.x. Is this what you tried to say?


> Without those, the build doesn't even get five minutes in. Ubuntu's repo doesn't contain a nodejs and npm that meet these standard so Ubuntu users have a bit more work to do to compile NodeOS.

By executing `bin/install-dependencies` should install all the required system dependencies, including a good version of Node.js and npm, and if not tell me and I'll fix it (or do a pull-request instead! :-D )

**Comment by lite20** [comment]
> Don't take it that way... I know you and others are there, but I'm nobody to ask anybody to do this or that, just only manage what anyone volunteer wants to do. I must to admit that I should have a to-do list somewhere so people could know what tasks can work with, but I can't be able to tell anybody what to do with his spare time :-/

Ah no I mean't we'd be able to help you in your quest to improve the build system. Now is an ideal time for me to work as classes are just starting up again and none of the teachers are assigning any work so I have lots of time.

> Currently Node.js needs to be greater than 0.12 and npm needs to be less than three, that correspond to Node.js 4.x. Is this what you tried to say?

I didn't know node 0.12 worked. So yes, 4.x

> By executing bin/install-dependencies should install all the required system dependencies, including a good version of Node.js and npm, and if not tell me and I'll fix it (or do a pull-request instead! :-D )

Oh awesome! I wish you'd told me in advance :stuck_out_tongue:

**Comment by lite20** [comment]
> By executing bin/install-dependencies should install all the required system dependencies, including a good version of Node.js and npm, and if not tell me and I'll fix it (or do a pull-request instead! :-D )

I am having issues with the script. I will carry out its commands on my own and see if I can find (more so understand) the issue and make a PR. Here's the output:

lite@lite-pc:~/Documents/lnodes/bin$ sudo ./install-dependencies 
W: Failed to fetch http://ppa.launchpad.net/cairo-dock-team/ppa/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/cairo-dock-team/ppa/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by piranna** [comment]
> Ah no I mean't we'd be able to help you in your quest to improve the build system. Now is an ideal time for me to work as classes are just starting up again and none of the teachers are assigning any work so I have lots of time.

Ok, I think it could be a good and easy task, to check how to make it easier to use :-)


> I didn't know node 0.12 worked. So yes, 4.x

Yes it does, in fact I'm using it currently to tests some things that will need to work on NodeOS. 4.x is a good alternative, and hope someday we can move forward to it :-)


> Oh awesome! I wish you'd told me in advance :stuck_out_tongue:

It's on the readme... :-P


> I am having issues with the script. I will carry out its commands on my own and see if I can find (more so understand) the issue and make a PR. Here's the output:
> 
> lite@lite-pc:~/Documents/lnodes/bin$ sudo ./install-dependencies
> W: Failed to fetch http://ppa.launchpad.net/cairo-dock-team/ppa/ubuntu/dists/wily/main/binary-amd64/Packages 404 Not Found
> 
> W: Failed to fetch http://ppa.launchpad.net/cairo-dock-team/ppa/ubuntu/dists/wily/main/binary-i386/Packages 404 Not Found
> 
> W: Failed to fetch http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu/dists/wily/main/binary-amd64/Packages 404 Not Found
> 
> W: Failed to fetch http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu/dists/wily/main/binary-i386/Packages 404 Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.

There are not related to NodeOS, seems you have configured some non-existent APT repositories regarding to cairo-dock and ffmpeg-next.

**Comment by lite20** [comment]
> There are not related to NodeOS, seems you have configured some
non-existent APT repositories regarding to cairo-dock and ffmpeg-next.

Ah okay. Do I need to uninstall my current node and npm before running this
script? I didn't see any results the first time.

**Comment by piranna** [comment]
> > There are not related to NodeOS, seems you have configured some
> non-existent APT repositories regarding to cairo-dock and ffmpeg-next.
>
> Ah okay. Do I need to uninstall my current node and npm before running
this
> script? I didn't see any results the first time.

If you want to downgrade it then yes, uninstall them first. There's an
option to force to downgrade a package but don't remember it, so it's
easier to uninstall it by hand first.

**Comment by lite20** [comment]
Alright. Would be an upgrade for me actually. Thx
