### ISSUE TITLE
How to use NPM ?

### ISSUE THREAD

**Issue by p4ulolol** [NodeOS/NodeOS#205]
Hello,

I was just wondering how I can use NPM inside of NodeOS ?

The OS started, it launched a REPL session correctly.

But when I type "npm _something_", it tells me that NPM should be run outside of the REPL. So I press Ctrl+D to quit the REPL and then... The OS doesn't do anything! I can only type things, they appear on screen, but nothing happens.

So how are we supposed to use NPM ?

**Comment by piranna** [comment]
How have you downloaded and exec the OS? You should get up to a shell on
the standard prebuilds, if you got a REPL then something went wrong...

**Comment by p4ulolol** [comment]
I downloaded the pre-build i386-pc_iso version from the Releases page. The only thing I can say is that the REPL works fine.

**Comment by piranna** [comment]
What's the prompt of the REPL? This should tell you in what step it failed.

**Comment by p4ulolol** [comment]
NodeOS-mount-filesystems. Also I noticed I had this error before :
`Could not find userfs: [Error: /dev/sdb2 not exists]`
And then it prompted me for the path to userfs. As I didn't know what to type, I pressed enter and it told I won't be able to save changes.

**Comment by piranna** [comment]
Then there you have the answer, it can't find the users partition :-) Just
set the path to the partition and you are fine.

Are you using it in real hardware? This should not give problems on QEmu...
We don't have yet a proper way to autodetect partitions and it's hardcoded
the most usual one, pull-requests are welcome :-)

**Comment by p4ulolol** [comment]
Ok :-) but what path should I give ? The path where it is on my harddisk, like C:\etc. ? Or the cygwin path ? (```/cygdrive/c/users/paul/downloads/i386-pc_iso``` )

**Comment by piranna** [comment]
> Ok :-) but what path should I give ? The path where it is on my harddisk,
like C:\etc. ? Or the cygwin path ?
(/cygdrive/c/users/paul/downloads/i386-pc_iso )

You need to give the path to the device on Linux, like /dev/sdb2. Are you
getting this error on QEmu? That's sounds terrible bad... :-/ How are you
running it?

**Comment by p4ulolol** [comment]
Yes I get this error on QEmu, that's why I can't figure what path I have to give...
I run it using cygwin, with this command : ```sh run.sh``` (the run.sh file is the one which is present in the pre-build archive)

**Comment by piranna** [comment]
Try with /dev/sda2. Since you are using the iso image instead of the qemu
image it could be trying to find the partition in the wrong place since
it's intended to be flashed on a pendrive and run on real hardware, where
usually there's already a hard disk, but on QEmu doesn't.

**Comment by p4ulolol** [comment]
Nop, /dev/sda2 doesn't exist. I tried with /dev/sda , but it obviously didn't work.
Maybe I should just take the qemu image. I took the iso one thinking I would get an ISO file, to run on a VM, but I was wrong

**Comment by piranna** [comment]
The ISO image should work on virtual machines, but it's not so tested. Yes,
it's better you take the QEmu one ;-)

**Comment by p4ulolol** [comment]
Well with QEmu one, I also have a strange error (I took a screenshot because I was too lazy to retype it) : http://grab.by/NWYW

And I don't know how to get the ISO file from rootfs and usersfs... I knew how to do with a kernel using xorriso on a linux machine, but not on my Windows one...
I don't think that just copying those files in an iso file would work...

**Comment by piranna** [comment]
That error doesn't makes sense. Honestly, I don't know what's happening
here and don't have a Windows machine to test, sorry :-(

**Comment by p4ulolol** [comment]
Ok, well I'll search for a solution, I tell you if I find one

**Comment by lite20** [comment]
Good thing I'm good at reading errors :)

There seems to be an issue in NodeOs-mount-filesystems on line 36 of index.JS

It claims that the directory /tmp/dev has not been mounted. I'll look into this later.

**Comment by p4ulolol** [comment]
Ok, thank you lite.

**Comment by lite20** [comment]
@piranna where is this module on Github?

**Comment by piranna** [comment]
You can find it in my account, there was a conflict with nodeos-mount-rootfs. I'll need someday to clean up NodeOS organization and remove old ones...

**Comment by piranna** [comment]
Any progress with that?

**Comment by lite20** [comment]
Has this error ever re-occured? I can take a look right now.

**Comment by piranna** [comment]
I have been using npm from inside NodeOS without problems...

**Comment by lite20** [comment]
Let's close it for now, but if this re-occurs assign me to it.
