### ISSUE TITLE
npm WARN lifecycle NodeOS

### ISSUE THREAD

**Issue by swapdewalkar** [NodeOS/NodeOS#206]
> npm WARN lifecycle NodeOS@0.0.0~install: cannot run in wd %s %s (wd=%s) NodeOS@0.0.0 scripts/build

I have run this command 
npm install
Geeting this Error.

Error log when npm start
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle NodeOS@0.0.0~prestart: NodeOS@0.0.0
6 silly lifecycle NodeOS@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle NodeOS@0.0.0~start: NodeOS@0.0.0
8 verbose lifecycle NodeOS@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle NodeOS@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/media/swapnil/other1/NodeOS/NodeOS/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle NodeOS@0.0.0~start: CWD: /media/swapnil/other1/NodeOS/NodeOS
11 silly lifecycle NodeOS@0.0.0~start: Args: [ '-c', 'scripts/start' ]
12 silly lifecycle NodeOS@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle NodeOS@0.0.0~start: Failed to exec start script
14 verbose stack Error: NodeOS@0.0.0 start: `scripts/start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid NodeOS@0.0.0
16 verbose cwd /media/swapnil/other1/NodeOS/NodeOS
17 error Linux 4.2.0-27-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.4.1
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error NodeOS@0.0.0 start: `scripts/start`
22 error Exit status 1
23 error Failed at the NodeOS@0.0.0 start script 'scripts/start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the NodeOS package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     scripts/start
23 error You can get their info via:
23 error     npm owner ls NodeOS
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by lite20** [comment]
Please downgrade to npm2 for building NodeOS. Npm3 has issues :P. Fetching NodeJs 4 should come packaged with npm2.

**Comment by piranna** [comment]
When we release 1.0 we'll look about this. First thing will be move crosstool to an independent package.

**Comment by swapdewalkar** [comment]
Yes I have done some Google about it
First I need to run

npm install --unsafe-perm

Then it will show some other error.
To which solution is to downgrade npm (2-3) and node.js(4-5).
Is I am correct??

**Comment by piranna** [comment]
Fixed in master, clossing.
