### ISSUE TITLE
Node console OS

### ISSUE THREAD

**Issue by moshest** [NodeOS/NodeOS#207]
I'm looking for an "OS" that simply boot into a node console. I understand that NodeOS is way more complicated. Am I right?

Is there a way to create a simplified OS that only boot and start a Javascript console, from there we could evolve and add some more functionality such as NPM libraries, users, permission, and more..

Thoughts? Suggestions?

**Comment by piranna** [comment]
If you are interested on boot on a Node.js REPL you can use just the
nodeos-barebones layer, but if you want a lower level raw Javascript prompt
then maybe you would look into runtime.js. What's your intention? NodeOS
already provides support for Node.js modules, npm and multiuser...

**Comment by moshest** [comment]
Thank you. I will check it.

My intention is that the OS will be as light as it could. I recheck the roadmap and it's look like NodeOS is very light already so maybe I misunderstood the project goals.

**Comment by piranna** [comment]
NodeOS try to be very lightweight, so if you are thinking about working on
something similar probably it would be a better idea to join efforts.

**Comment by moshest** [comment]
Agreed.
