### ISSUE TITLE
Error compiling NodeOS

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#212]
Here's a new error I hit attempting to install NodeOS on a 64 bit Ubuntu computer:

triplebackslash@TriplePC:~/Documents/nodeos$ npm install
|
> nodeos-barebones@0.0.0 preinstall /home/triplebackslash/Documents/nodeos/node_modules/nodeos-barebones
> scripts/preinstall

     fetch : http://nodejs.org/dist/v0.11.14/node-v0.11.14.tar.gz
  progress : [====================] 100% 0.0s

Cloning into 'dtc'...
remote: Counting objects: 2778, done.
remote: Compressing objects: 100% (1692/1692), done.
remote: Total 2778 (delta 2058), reused 1415 (delta 1056)
Receiving objects: 100% (2778/2778), 654.26 KiB | 101.00 KiB/s, done.
Resolving deltas: 100% (2058/2058), done.
Checking connectivity... done.
{ [Error: Command failed: ./configure --prefix=/home/triplebackslash/Documents/nodeos/node_modules/nodeos-barebones/usr --target-list=arm-softmmu,i386-softmmu,x86_64-softmmu,arm-linux-user,i386-linux-user,x86_64-linux-user --disable-docs --disable-vnc --enable-sdl
]
  killed: false,
  code: 1,
  signal: null,
  cmd: './configure --prefix=/home/triplebackslash/Documents/nodeos/node_modules/nodeos-barebones/usr --target-list=arm-softmmu,i386-softmmu,x86_64-softmmu,arm-linux-user,i386-linux-user,x86_64-linux-user --disable-docs --disable-vnc --enable-sdl' }

npm ERR! Linux 3.16.0-62-generic
npm ERR! argv "/home/triplebackslash/.nvm/versions/node/v4.0.0/bin/node" "/home/triplebackslash/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@0.0.0 preinstall: `scripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeos-barebones@0.0.0 preinstall script 'scripts/preinstall'.
npm ERR! This is most likely a problem with the nodeos-barebones package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-barebones
npm ERR! There is likely additional logging output above.

I'm using node 4, and npm 2.14.2 so I'm not sure where to go from here. I'm attempting to use the latest on the 4 and 2 branches of node and npm respectively but not expecting drastic changes. Any idea what's going on?

**Comment by piranna** [comment]
It's failling to compile QEmu, another heavy one that should be put in a prebuild package project... Try executing `SILENT= npm install` to see if we get more output info.

**Comment by Coretool** [comment]
Looks like the configure script failed... but I've no plan what caused that !

**Comment by lite20** [comment]
Okay. It's actually going further using the latest node 4 and npm 2 which is surprising. I'll give an update on where it stops, if it stops.

**Comment by piranna** [comment]
Seems build errors are random, and the fact is that this also happens on the CI server... :-/ We need to split the project in submodules as soon as possible, so we can check them independently and also make build process faster by using prebuild packages. We could be able to start with noGUI or by packaging and publishing an already one. QEmu is a good candidate since it will always run on the host machine, so it's only a matter of cut-off the steps from the NodeOS build steps and make it an independent script...

**Comment by Coretool** [comment]
Do you have a functional build of noGui  ?

**Comment by lite20** [comment]
New error:


\
> nodeos-barebones@0.0.0 preinstall /home/triplebackslash/Documents/nodeos/node_modules/nodeos-barebones
> scripts/preinstall


> nodeos-cross-toolchain@0.0.0 preinstall /home/triplebackslash/Documents/nodeos/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain
> scripts/preinstall

     fetch : http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.gz
     fetch : http://www.musl-libc.org/releases/musl-1.1.14.tar.gz
     fetch : https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.4.3.tar.gz
     fetch : http://ftpmirror.gnu.org/binutils/binutils-2.25.1.tar.gz
  progress : [==============      ] 70% 567.0s
/home/triplebackslash/Documents/nodeos/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/scripts/preinstall:130
  if(error) throw error;
            ^

Error: ENOENT: no such file or directory, open 'deps/gcc/gcc/config.gcc'
    at Error (native)

npm ERR! Linux 3.16.0-62-generic
npm ERR! argv "/home/triplebackslash/.nvm/versions/node/v4.3.1/bin/node" "/home/triplebackslash/.nvm/versions/node/v4.3.1/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! nodeos-cross-toolchain@0.0.0 preinstall: `scripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeos-cross-toolchain@0.0.0 preinstall script 'scripts/preinstall'.
npm ERR! This is most likely a problem with the nodeos-cross-toolchain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-cross-toolchain
npm ERR! There is likely additional logging output above.

**Comment by lite20** [comment]
let the package splitting, begin. It would be nice if the scripts did logging on what they were doing so we could see where exactly scripts failed. (maybe this can be a parameter at build).

To split QEMU we just need to remove it's build steps from the build process?

**Comment by piranna** [comment]
> Do you have a functional build of noGui ?

I haven't touched it from last week since I though you wanted to take it a try. I tried to show a local html page but it was uncesful and also it needs to be seen how to make ICU statically linked, but it's on a good path anyway.


> let the package splitting, begin. It would be nice if the scripts did logging on what they were doing so we could see where exactly scripts failed. (maybe this can be a parameter at build).

It should work by defining the `SILENT=` environment variable to disable all silent output and make it verbose.


> To split QEMU we just need to remove it's build steps from the build process?

Mostly yes, just cut&paste.

**Comment by luii** [comment]
Getting the same error but after reentering the same command
its skips the first part

```
philipp ~/NodeOS master λ sudo npm install
\
> nodeos-barebones@0.0.0 preinstall /home/philipp/NodeOS/node_modules/nodeos-barebones
> scripts/preinstall

     fetch : http://nodejs.org/dist/v0.11.14/node-v0.11.14.tar.gz
  progress : [====================] 100% 0.0s

Klone nach 'dtc' ...
remote: Counting objects: 2778, done.
remote: Compressing objects: 100% (1692/1692), done.
remote: Total 2778 (delta 2058), reused 1415 (delta 1056)
Empfange Objekte: 100% (2778/2778), 654.26 KiB | 283.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (2058/2058), Fertig.
Prüfe Konnektivität ... Fertig.
{ [Error: Command failed: ./configure --prefix=/home/philipp/NodeOS/node_modules/nodeos-barebones/usr --target-list=arm-softmmu,i386-softmmu,x86_64-softmmu,arm-linux-user,i386-linux-user,x86_64-linux-user --disable-docs --disable-vnc --enable-sdl
]
  killed: false,
  code: 1,
  signal: null,
  cmd: './configure --prefix=/home/philipp/NodeOS/node_modules/nodeos-barebones/usr --target-list=arm-softmmu,i386-softmmu,x86_64-softmmu,arm-linux-user,i386-linux-user,x86_64-linux-user --disable-docs --disable-vnc --enable-sdl' }

npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! nodeos-barebones@0.0.0 preinstall: `scripts/preinstall`
npm ERR! Exit status 1
```

**Comment by Coretool** [comment]
@luii  @piranna @lite20 The preinstall script also fails when trying to build the toolchain. I opened an [issue](http://www.github.com/nodeos/nodeos-cross-toolchain/issues) at the corresponding repo.

**Comment by piranna** [comment]
The pull-request of @lite20 would fix it.

**Comment by piranna** [comment]
This should be already fixed in master, clossing.
