### ISSUE TITLE
Node-os.com's "read more" button is broken

### ISSUE THREAD

**Issue by Nepoxx** [NodeOS/NodeOS#219]
It points to this page: http://node-os.com/blog/get-involved/ which returns a 404.

**Comment by aulvi** [comment]
Removing the trailing slash seems to fix it.

**Comment by lite20** [comment]
The new website will fix this. Closing

**Comment by piranna** [comment]
I would not close and issue until it's fixed or superseeded by another one.
In that case, I would add this to a list of to-do things in the new website
issue or directly in its repo.

Anyway, what a hige work have you done by reviewing the issues! You rocks!
:-D

**Comment by lite20** [comment]
@piranna I read everyone of the 111 issues, and am now done reading anything for the rest of the day XD (just kidding, trying to compile mesa so more reading for me). And yeah I'll reopen this on the site repo
