### ISSUE TITLE
Build NodeOS from Source

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#220]
Hey,
i just want to ask if there is a way to build NodeOS, because the build process on the Readme seems a bit outdated(?) And which OS do i need for the build process?

**Comment by piranna** [comment]
Why do you think it's outdated? What steps are you following?

**Comment by luii** [comment]
I followed the steps in the main Readme but everytime i try to build it i get the errors described in #212.
But it seems that you've build it on Ubuntu. So my question is how to build it successfully because i want to create software for nodeos :D

**Comment by piranna** [comment]
There could be something odd with your computer, since I've recently compiled NodeOS from scratch on a fresh install of Ubuntu 16.04... It's true that there are problems on the server and that build process it's too much heavy weight, but I'm not able to replicate them :-( What system are you using for?

If you are interested in create software for NodeOS you could do it just for Linux and when it get working just port it :-)

**Comment by luii** [comment]
I used Ubuntu 15.10 for the compilation, and then switched to Arch but no success.

**Comment by Coretool** [comment]
Aw... arch isn't optimal for that... I'm a big arch fan, it's my main os, but since it's a rolling release os and always on the newest versions... NodeOs and bleeding edge versions  aren't big friends (what I can tell from my expremintes with it)

**Comment by piranna** [comment]
I don't think it's a problem of rolling release but instead of lack of libs
and components that need to be installed by hand. @SpaceManSpiff had
similar problems in the past about this.

**Comment by luii** [comment]
This issue can be closed because i've successfully compiled NodeOS from Source on Arch Linux x86_64!
```js
Success!
You just built a custom NodeOS image
```
I create a new Pull request if i have updated the docs for that and provide the prebuilt binaries for Arch Linux x86_64 and x86 (32bit)!

**Comment by lite20** [comment]
Oh that's awesome! I've began creating a list of events that occur in the
NodeOS build process to hopefully design a pull-and-pack build script for a
continual build server.

Many of us are pitching in to make a better build process so hopefully we
make headway on that soon

**Comment by piranna** [comment]
> This issue can be closed because i've successfully compiled NodeOS from
Source on Arch Linux x86_64!
>
> Success!
> You just built a custom NodeOS image
>
> I create a new Pull request if i have updated the docs for that and
provide the prebuilt binaries for Arch Linux x86_64 and x86 (32bit)!

That's cool! :-D I'll left this issue open until we got merged your
pull-request :-)

**Comment by piranna** [comment]
> Oh that's awesome! I've began creating a list of events that occur in the
> NodeOS build process to hopefully design a pull-and-pack build script for
a
> continual build server.

Could you be able to explain this a bit? Sounds interesting :-)

> Many of us are pitching in to make a better build process so hopefully we
> make headway on that soon

Then wait for the blog post I'll write tonight... ;-)

**Comment by luii** [comment]
Ive managed to build Arch but dont know how to pack it into a binary like @piranna did on his build today in the zip

**Comment by piranna** [comment]
> Ive managed to build Arch but dont know how to pack it into a binary like
@piranna did on his build today in the zip

Spoiler!!! :-P

That builds *should* be autogenerated by the CI server, but somehow it got
broken by several issues. I think I was able to fix them or find some hacky
workarounds, but they should work from now on. The prebuilds uploaded today
were build and uploaded by hand with scripts/BigRedButton and
scripts/publish, but they should be OS agnostic since they only host disk
images to exec with QEmu...

**Comment by lite20** [comment]
I'm basically extracting the list of commands/steps from the build process
and writing them down, then re creating the build scripts. I'm doing that
to create a custom CI server for me to use with NodeOS that will pull from
the branches I instruct, and compile over and over again (every time
someone makes a change). Then it packages them.

I'm creating it for said phone I'm working on. The beta testers are always
asking for updated builds so now I'm just gonna have the server auto build
and deploy for me.

(Those auto scripts may be useful for other things though)

**Comment by piranna** [comment]
Sound interesting what you said. Have you taken a look at [GreenKeeper](https://greenkeeper.io)? I would like to use it on NodeOS, but would be a tough work to add 100% coverage tests on all the projects... :-/

**Comment by lite20** [comment]
Ah yes I've seen it and I'm looking to integrate with it. If not I'd write
my own simpler engine to do so.

And yes, 100% test coverage is difficult. Writing ingenuous tests to test
everything is difficult. Often tests are created along side the software
but we don't have that option any more. I'm still working to add tests to
the JS modules and will continue when I have more free time but right now
things are tight with school.

**Comment by piranna** [comment]
I'm thinking about writting a tool to recursively ask to Coveralls and npm for the coverture stats of all the project dependencies and show them as a tree so we could later work on improve them, but both things will be a tough work :-P

**Comment by lite20** [comment]
Haha good idea! If you get it going let me know!

**Comment by piranna** [comment]
Yeah, but I don't have time! :-P

**Comment by lite20** [comment]
> Yeah, but I don't have time! :-P

D: I'd offer to help but I'm a bit tied with completing other projects, and stuff for work.

**Comment by piranna** [comment]
> but I'm a bit tied with completing other projects, and stuff for work

Me too :-(

**Comment by piranna** [comment]
I have started to accept some of the docs pull-requests, so I'll close this.
