### ISSUE TITLE
npm/npkg both show --> [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]

### ISSUE THREAD

**Issue by shubhamkumar13** [NodeOS/NodeOS#221]
`/ # npkg install bin-ncurl
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm http GET http://linux-x86.node-os.com/bin-ncurl
[Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]
/ # npm install bin-ncurl
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm ERR! Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:221:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:211:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.2.0-30-generic
npm ERR! command "node" "/bin/npm" "install" "bin-ncurl"
npm ERR! cwd /
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.23
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
`

**Comment by lite20** [comment]
Disable SSL checks then re-enable it after. Proxies often cause this.

Disable: `npm config set strict-ssl false`

Enable: `npm config set strict-ssl true`

Reference: http://stackoverflow.com/a/21385322

**Comment by lite20** [comment]
Ah wait is this from within NodeOS? Use npm directly not npkg. See if you get any farther

**Comment by piranna** [comment]
npkg and http://linux-x86.node-os.com repo are both deprecated since a long time ago, clossing.
