### ISSUE TITLE
NodeOS boot

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#223]
Is it normal that nodeos boots into a REPL? Because i cant use commands like ls, mkdir, etc?

**Comment by piranna** [comment]
How have you started NodeOS? Is there any error on the console? What says the prompt?

**Comment by luii** [comment]
I started  NodeOS with `npm start` and the prompt dont throws any error

**Comment by piranna** [comment]
What's the output of the prompt? Could you send a screenshoot or a picture?

**Comment by lite20** [comment]
> Is it normal that nodeos boots into a REPL? Because i cant use commands like ls, mkdir, etc?

So barebones loaded, but not the user space. Maybe it didn't mount the filesystem? 

What environment are you running this in? QEMU? Bare metal?

**Comment by luii** [comment]
im running this inside QEMU using just the command `npm start`

Unfortunatly i cant scroll up...
![nodeos](https://cloud.githubusercontent.com/assets/8077014/14389216/e5e5a73c-fdb1-11e5-9033-14c7877d4b2b.png)

And that is the output from my console on arch:
```bash
[philipp@arch NodeOS 64bit]$ npm start

> NodeOS@0.0.0 start /home/philipp/Dokumente/github/NodeOS 64bit
> scripts/start

qemu-system-x86_64: -redir tcp:50080::80: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
qemu-system-x86_64: -redir tcp:50443::443: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
WARNING: Image format was not specified for 'out/latest/usersfs' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.

```

**Comment by piranna** [comment]
Have you compiled the image yourself, or have you used one of the prebuilds ones?

**Comment by luii** [comment]
I compiled the image myself

**Comment by piranna** [comment]
Did you get any error during build process? Could you be able to exec `tree out` to know what files were generated?

**Comment by luii** [comment]
nope i think its only a temp folder with only the barebones when im starting up

**Comment by luii** [comment]
Ive tried the prebuilts and it works

**Comment by piranna** [comment]
> Ive tried the prebuilts and it works

This are good news :-) Maybe there was a problem with the build proccess, try to exec `npm install` to build it again.

**Comment by luii** [comment]
@piranna recompiled the source and got this:
![nodeos](https://cloud.githubusercontent.com/assets/8077014/14394520/f1052d0c-fdcc-11e5-805d-dba348aa7c3f.png)

**Comment by piranna** [comment]
It's the first time I see that error, but seems to be some incompatibility on fuse-bindings and the version of Node.js being used. Try executing `npm run unbuild` to clean all the products and dependencies and `npm install` to download and build them again.

**Comment by luii** [comment]
I've rebuild the package, but everytime i get the error showed above.
I researched for this error on google and it mostly says that precompiled binarys like `fuse-bindings`
are compiled with 5.x.x or higher and the `nodeos-barebones` are compiled with 4.x.x.
It seems that we need to use a older version of fuse-bindings on nodeos.

**Comment by piranna** [comment]
What version of Node.js do you have on your system? Seems `fuse-bindings` got compiled using Node.js 5.x.x and NodeOS is currently using 4.x.x, would it be possible? And what version of NodeOS are you compiling, have you downloaded it recently?

If you are using Node.js 5.x.x and NodeOS `package.json` is using `nodeos-cross-toolchain` module then it would be good news, since it would means it now require just some minor tune-ups to have support for Node.js 5 and npm 3! :-D

**Comment by luii** [comment]
@piranna my main node version is 4.3.1, im also using nvm for better testing and stuff :D
with node 5.x on nvm or with the node fish shell plugin (which includes node 5.10.1) i get the following error: 
```bash
[philipp@arch NodeOS]$ npm install
npm WARN prefer global node-ninja@1.0.1 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> qemu@2.5.50 install /home/philipp/Dokumente/github/NodeOS/node_modules/qemu
> prebuild --download https://github.com/NodeOS/qemu/releases/download/v{version}/{platform}-{arch}.tar.gz


> nodeos-cross-toolchain@0.0.1 install /home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-cross-toolchain
> prebuild --download https://github.com/NodeOS/nodeos-cross-toolchain/releases/download/v{version}/{platform}-{arch}.tar.gz


> genfatfs@1.0.1 install /home/philipp/Dokumente/github/NodeOS/node_modules/genfatfs
> prebuild --download https://github.com/NodeOS/genfatfs/releases/download/v{version}/{platform}-{arch}.tar.gz


> genext2fs@1.4.1 install /home/philipp/Dokumente/github/NodeOS/node_modules/genext2fs
> prebuild --download https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz


> NodeOS@0.0.0 install /home/philipp/Dokumente/github/NodeOS
> scripts/build

cp: der Aufruf von stat für 'node_modules/nodeos-barebones/out/latest' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'node_modules/nodeos-initramfs/out/latest' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'node_modules/nodeos-usersfs/out/latest' ist nicht möglich: Datei oder Verzeichnis nicht gefunden

> NodeOS@0.0.0 postinstall /home/philipp/Dokumente/github/NodeOS
> scripts/postinstall

------------------------------------------
Success!
You just built a custom NodeOS image
------------------------------------------

- Interactively run your image with:
    npm start
abbrev@1.0.7 node_modules/genext2fs/node_modules/prebuild/node_modules/node-gyp/node_modules/nopt/node_modules/abbrev -> node_modules/abbrev
after@0.8.1 node_modules/genext2fs/node_modules/prebuild/node_modules/ghreleases/node_modules/after -> node_modules/after
ansi@0.3.1 node_modules/genext2fs/node_modules/prebuild/node_modules/npmlog/node_modules/ansi -> node_modules/ansi
ansi-regex@2.0.0 node_modules/publish-release/node_modules/inquirer/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex -> node_modules/ansi-regex
ansi-styles@2.2.1 node_modules/publish-release/node_modules/inquirer/node_modules/chalk/node_modules/ansi-styles -> node_modules/ansi-styles
arr-flatten@1.0.1 node_modules/download-manager/node_modules/download/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/micromatch/node_modules/arr-diff/node_modules/arr-flatten -> node_modules/arr-flatten
arr-diff@2.0.0 node_modules/download-manager/node_modules/download/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/micromatch/node_modules/arr-diff -> node_modules/arr-diff
array-differ@1.0.0 node_modules/download-manager/node_modules/download/node_modules/gulp-decompress/node_modules/gulp-util/node_modules/array-differ -> node_modules/array-differ
array-find-index@1.0.1 node_modules/publish-release/node_modules/pretty-bytes/node_modules/meow/node_modules/loud-rejection/node_modules/array-find-index -> node_modules/array-find-index
array-uniq@1.0.2 node_modules/download-manager/node_modules/download/node_modules/gulp-decompress/node_modules/gulp-util/node_modules/array-uniq -> node_modules/array-uniq
array-unique@0.2.1 node_modules/download-manager/node_modules/download/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/micromatch/node_modules/array-unique -> node_modules/array-unique
asn1@0.2.3 node_modules/publish-release/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/asn1 -> node_modules/asn1
assert-plus@0.2.0 node_modules/publish-release/node_modules/request/node_modules/http-signature/node_modules/assert-plus -> node_modules/assert-plus
async@1.5.2 node_modules/genext2fs/node_modules/prebuild/node_modules/async -> node_modules/async
aws-sign2@0.6.0 node_modules/publish-release/node_modules/request/node_modules/aws-sign2 -> node_modules/aws-sign2
balanced-match@0.3.0 node_modules/genext2fs/node_modules/prebuild/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match -> node_modules/balanced-match
beeper@1.1.0 node_modules/download-manager/node_modules/download/node_modules/gulp-decompress/node_modules/gulp-util/node_modules/beeper -> node_modules/beeper

This block keeps going down a thousend lines
```

The main point is that the `barebone`, `initramfs` and `userfs` not creating the files in the `/out` folder

**Comment by piranna** [comment]
That's the problem, you are using Node.js 5.x, use 4.x instead without nvm,
it should work now.

**Comment by luii** [comment]
>That's the problem, you are using Node.js 5.x, use 4.x instead without nvm, it should work now.
Ok but then again i get the version module mismatch

**Comment by piranna** [comment]
> Ok but then again i get the version module mismatch

It's strange... Did you clean the repo and compiled from scratch with 4.x?

**Comment by luii** [comment]
yes, just fresh cloned it and compiled it but still i get this error

**Comment by piranna** [comment]
> yes, just fresh cloned it and compiled it but still i get this error

Sh*t, then I don't know what could be happening here, sorry :-(

**Comment by lite20** [comment]
Is npm3 a good thing or a bad thing?

**Comment by piranna** [comment]
> Is npm3 a good thing or a bad thing?

Definitely bad, we'll need to change several things in a backwards
incompatible way on the NodeOS build workflow to make it compatible with
npm 3 :-( Anyway it's the way to go, so we'll need to do it someday...

**Comment by lite20** [comment]
npm, why you do this :'(

Version mismatch...what's the package.json request? It seems you keep
getting a version higher. Try altering the package.json just to see?

**Comment by luii** [comment]
If i understand the install procedure correctly then it shoud go like this:
```
NodeOS -> npm install 

- calls npm install on the tool chain -> compiles
- then the barebones
- then initramfs
- then rootfs
- and then userfs
```
but why does it not go like this?
For me it looks like it just skip the part

```
cp: the stat for 'node_modules / node os-barebones / out / latest' is not possible: file or directory not found
cp: the stat for 'node_modules / nodeos-initramfs / out / latest' is not possible: file or directory not found
cp: the stat for 'node_modules / nodeos-usersfs / out / latest' is not possible: file or directory not found
```

**Comment by piranna** [comment]
You are right, for some reason the layers are not being procesed in the correct order. What version of npm are you using? npm 3 is not compatible...

**Comment by luii** [comment]
for the error above im using npm 3
and for everything else im using npm 2.14.12

@piranna the commit yesterday was not intended, i thought i had them pushed to my forked repo but instead i the original nodeos fork, im so sorry

**Comment by luii** [comment]
After hours of searching i think i found the badboy on the Module version mismatch.
`fuse-bindings` uses a package called `prebuild` that creates multiple "prebuild" binaries for node/io.js.
So my assumption on this was that `prebuild` loads the newest version of fuse-bindings but not the correct ABI version of Node (e.g. fuse-bindings: 2.8.1; Node.js ABI 47 (5.x.x) what it shoud look like fuse-bindings: 2.8.1; Node.js ABI 46 (4.4.2))

![badboy](https://cloud.githubusercontent.com/assets/8077014/14538766/a09bb880-027d-11e6-936a-239448f13730.png)
The first line on this picture shows that it downloaded ABI v47 instead of v46, which gave me this error:
https://github.com/NodeOS/NodeOS/issues/223#issuecomment-207559013

**Comment by piranna** [comment]
@luii, that totally makes sense, the point is that I don't understand why it downloaded such version... I got a similar problem some time ago with the CI server using nvm where the NodeOS build process was using the globally instaded `node` executable instead. Would happen the same here?

I would open an issue on `fuse-bindings` repo anyway...

**Comment by luii** [comment]
I dont think that this is a `fuse-bindings` related issue, its more a `prebuild` related issue
But first i look for a fix for that problem.

**Comment by piranna** [comment]
Both `fuse-bindings` and `prebuild` has been created by @mafintosh, so I think he's the best one to ask for this problem ;-)

**Comment by luii** [comment]
@piranna i found a workaround for this problem.
we can use a `.prebuildrc` on the project or in the home folder.

the content of the `.prebuildrc`:

```json
{
  "abi": "46"
}
```

**Comment by piranna** [comment]
We are using `prebuild` everywhere now, so I think this can be clossed... What do you think @luii ?
