### ISSUE TITLE
I've tried to use the '3stp install'

### ISSUE THREAD

**Issue by dodekaeder** [NodeOS/NodeOS#225]
Hey,
I'm running a fresh trusty vagrant box and would like to install nodeOS.

After I successfully run the dependencies script and the "npm install" runs
for a long time (throwing no errors) I tried to do "npm start", but a error appears:

```
vagrant@vagrant-ubuntu-trusty-64:~/NodeOS$ npm install
\
> genext2fs@1.4.1 install /home/vagrant/NodeOS/node_modules/genext2fs
> prebuild --download https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz

vagrant@vagrant-ubuntu-trusty-64:~/NodeOS$ npm start

> NodeOS@0.0.0 start /home/vagrant/NodeOS
> scripts/start

fs.js:857
  return binding.readlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, readlink 'out/latest'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:857:18)
    at Object.<anonymous> (/home/vagrant/NodeOS/scripts/start:11:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! NodeOS@0.0.0 start: `scripts/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the NodeOS@0.0.0 start script 'scripts/start'.
npm ERR! This is most likely a problem with the NodeOS package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs NodeOS
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls NodeOS
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/NodeOS/npm-debug.log
vagrant@vagrant-ubuntu-trusty-64:~/NodeOS$ npm install
|[[3~\
> genext2fs@1.4.1 install /home/vagrant/NodeOS/node_modules/genext2fs
> prebuild --download https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz


> nodeos-cross-toolchain@0.0.1 install /home/vagrant/NodeOS/node_modules/nodeos-cross-toolchain
> prebuild --download https://github.com/NodeOS/nodeos-cross-toolchain/releases/download/v{version}/{platform}-{arch}.tar.gz



vagrant@vagrant-ubuntu-trusty-64:~/NodeOS$ npm -v
2.15.0
vagrant@vagrant-ubuntu-trusty-64:~/NodeOS$ node -v
v4.4.2

**Comment by luii** [comment]
Are there any files in your `out/latest` folder, like `barebones` or `userfs` ?

**Comment by dodekaeder** [comment]
there isn't any folder like this.

When I follow this 3 step guide first thing is that there isn't any rep at git@github.com:NodeOS/NodeOS.git. So I cloned https://github.com/NodeOS/NodeOS.git.

After this I get

```
vagrant@vagrant-ubuntu-trusty-64:~/NodeOS$ ls
bin  Contributing.md  doc  Dockerfile  node_modules  npm-debug.log  package.json  README.md  resources  scripts  vagga.yaml

```
Then i run npm install which ends with just a little output:

```
vagrant@vagrant-ubuntu-trusty-64:~/NodeOS$ npm install
\
> genext2fs@1.4.1 install /home/vagrant/NodeOS/node_modules/genext2fs
> prebuild --download https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz
```
Then I try to start it with "npm start" running into the problem allready described...

**Comment by luii** [comment]
Have you set `PLATFORM=vagga npm install` when running this command?

**Comment by luii** [comment]
The `npm start` command only starts nodeos on qemu not vagga

**Comment by dodekaeder** [comment]
no I didn't. thx so far...

**Comment by dodekaeder** [comment]
so after `PLATFORM=vagga npm install` it sould start on vagga with `npm start!?`

**Comment by piranna** [comment]
Vagga and vagrant are not the same thing, and in fact vagrant is not
tested...

**Comment by dodekaeder** [comment]
> Vagga and vagrant are not the same thing, and in fact vagrant is not
> tested...
> El 10/4/2016 12:19 PM, "dodekaeder" <notifications@github.com> escribió:

got this! I thought a running Linux environment should make a good start...so I decided to build up on a vagrant box.

**Comment by dodekaeder** [comment]
But ended soon with

```
<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 0->1
Security context: 0x1118497b4629 <JS Object>
    3: render [/home/vagrant/NodeOS/node_modules/download-manager/node_modules/download-status/node_modules/progress/lib/node-progress.js:141] [pc=0x13c4c5250575] (this=0x1085db620df1 <a ProgressBar with map 0xf8101f40b1>,tokens=0x1118497041b9 <undefined>)
    4: /* anonymous */ [/home/vagrant/NodeOS/node_modules/download-manager/node_modules/download-status...

FATAL ERROR: Malloced operator new Allocation failed - process out of memory
```

So if I get it right. I shouldn't use vagrant and use my n

**Comment by dodekaeder** [comment]
Am I right remembering you recommend "google cloud" as a working platform.

**Comment by piranna** [comment]
> so after PLATFORM=vagga npm install it sould start on vagga with npm start!?

No, just exec `vagga` on the project directory, but you need to install it first. Anyway both vagga and docker don't fully work due to lack of support for OverlayFS and FUSE, but at least `barebones` layer should work.


> got this! I thought a running Linux environment should make a good start...so I decided to build up on a vagrant box.

As build environment? Didn't tested it, but should work... anyway I got it to build on a VirtualBox with Ubuntu, but testing it later is f*cking slow because QEmu is not able to use KVM inside a virtual machine :-(

**Comment by dodekaeder** [comment]
so.. the best way to see it working, is to run a prebuild in qemu?!

**Comment by piranna** [comment]
> so.. the best way to see it working, is to run a prebuild in qemu?!

It's the easiest one, yes. Other alternative is to build it from a Ubuntu environment, both running natively or from inside a virtual machine.

**Comment by piranna** [comment]
Master should have now some support to use vagrant as build environment, but needs some more testing, it's painfully slow and I don't have a powerful machine to give it more time, so I'll close this. By the moment, the recomended build environment is still to use Ubuntu running on real hardware.
