### ISSUE TITLE
Keynote at UC3M Linux Users Group

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#229]
As some of you would already know if you follow us on [Twitter](https://twitter.com/TheNodeOS), last Tuesday I was giving a keynote about NodeOS on the [Charles Third University Linux Users Group](http://www.gul.es/), and finally I've got the [recording](https://drive.google.com/file/d/0B9fEpRL8W1SPZUFkeGNDYk1RSlE/view?usp=sharing) of the keynote ready to be downloaded :-)

And in other news... :-P I have been fiddleing the last days with [coverdeeps](https://github.com/piranna/coverdeeps),  a little tool to check the global test coverage of a project and all its dependencies, since they are important (or more!) than the main project. It's currently limited to project that are already published on the npm registry and using [coveralls.io](https://coveralls.io/) for test coverage publishing so it's really pesimist about the results, but it's a good beginning the NodeOS objective to being an OS (the first one?) with a perfect score of [100% test coverage](https://github.com/NodeOS/NodeOS/issues/75) :-)

**Comment by lite20** [comment]
You don't happen to have an English translation of it do you? :P cheers!

**Comment by piranna** [comment]
Sorry, I don't have it :-(

**Comment by lite20** [comment]
That's okay! I'll just have to find a translator

**Comment by piranna** [comment]
> That's okay! I'll just have to find a translator

I don't know if GDrive support auto-captions as YouTube does...

**Comment by santigimeno** [comment]
Oh, I missed this one! I happen to work @ [UC3M Technology Center](http://www.uc3m.es/ss/Satellite/UC3MInstitucional/es/PortadaMiniSiteA/1371207248804/Parque_cientifico) :P

**Comment by piranna** [comment]
> Oh, I missed this one! I happen to work @ UC3M Technology Center :P

That's cool, I live in Alcorcón! :-D Maybe we could meet us someday now that next weeks are holidays! :-)
