### ISSUE TITLE
Changing Boot Logo

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#231]
Creating a thread so we can focus on competing this task. If anyone has an idea on how to change the Linux boot logo from tux to our own NodeOS image, please share. (I have knowledge, but it's incomplete)

**Comment by lite20** [comment]
Just dumping links for me to read is also appreciated

**Comment by piranna** [comment]
If you search for Linux boot logo there's a lot of tutorials :-) The default steps are mostly

- [ ] create an 80x80 image from the SVG logo
- [ ] reduce colors to 2, 4, 16 and 244 (seems there's a Gimp plugin just for this that create three versions at once)
- [ ] convert logo images in C code
- [ ] patch/overwrite Linux kernel source code with the logo images source code

Now you have where to start to read ;-)

Advanced tasks would be patch the source code adding NodeOS logo as an extra option instead of overwrite files, to create bigger logos (seems it can be up to 1024 pixels), don't tesellate the logo showing one instance for each CPU, and center the image on the screen.

**Comment by lite20** [comment]
I anyone gets a chance, let's try this:

http://web.archive.org/web/20140707092448/http://sumanprasanna.wordpress.com/2012/12/11/how-to-change-your-boot-logo-in-linux-kernel

If I have free time I'll give it a whirl.

**Comment by piranna** [comment]
Yeah, that's the kind of instructions I was talking about :-)

**Comment by lite20** [comment]
Awesome. A git patch? Is that what you have in mind?

**Comment by piranna** [comment]
> Awesome. A git patch? Is that what you have in mind?

Once that's finished, yes, that's the best option. I would prefer to generate the image directly from the SVG file on build time, but seems it would be more difficult... One step at a time! :-)

**Comment by lite20** [comment]
I think if we can generate a ppm and get it working than we can slowly back down the format chain to png, and then svg > png >  pnm and of course ppm

**Comment by piranna** [comment]
> I think if we can generate a ppm and get it working than we can slowly back down the format chain to png, and then svg > png > pnm and of course ppm

Yes, but better left this for a second iteration ;-) On a first instance, I think the patch is just enough, at least for the part of adding the option on KConfig.

**Comment by lite20** [comment]
Can I hand this task off to someone else?

**Comment by piranna** [comment]
It's not assigned to anybody at this moment.

**Comment by Coretool** [comment]
Isn't it possible to use syslinux for this ? Since I'm playing around with syslinux in order to change the keyboard layout, I could try this too...

**Comment by piranna** [comment]
Not sure... I know SysLinux can be used to show an image, but when the kernel gets running, probably they will overwritte the framebuffer :-/ You can take a look on it if you want, we don't loose anything :-)

**Comment by lite20** [comment]
Where is the syslinux setup in NodeOS? And we could disable kernel output... then the image would be there until the terminal appeared :stuck_out_tongue:

**Comment by Coretool** [comment]
That's what I was thinking about... But changing the actual logo is way more efficient ...

**Comment by lite20** [comment]
@Coretool hahah I'd do it but I'm just keep getting lost in the process

**Comment by piranna** [comment]
> Where is the syslinux setup in NodeOS?

Nodeos-rootfs

> And we could disable kernel output... then the image would be there until
the terminal appeared 😛

You can do it with the -quiet flag as kernel parameter.

**Comment by Coretool** [comment]
Is it okay if we store the NodeOS logo (in `ppm` format) at the `NodeOS/media` repo and download it when the kernel is downloaded ?

**Comment by piranna** [comment]
> @piranna Is it okay if we store the NodeOS logo (in ppm format) at the NodeOS/media repo and download it when the kernel is downloaded ?

Yes, it's ok :-)

**Comment by Coretool** [comment]
What size shall the logo be ?

**Comment by piranna** [comment]
The standard is 80x80 pixels, we could look later to use a bigger one.

Remember to use as basis to generate the logo the SVG file, it has the
correct colors!

**Comment by Coretool** [comment]
Sent pr for the `logo.ppm`

**Comment by piranna** [comment]
Merged

2016-06-17 17:54 GMT+02:00 John Green <notifications@github.com>:

> Sent pr for the logo.ppm
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NodeOS/NodeOS/issues/231#issuecomment-226807612>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAgfvtVXjSK68PZJajQAV9B29Qwx74thks5qMsMhgaJpZM4IPn5j>
> .
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by Coretool** [comment]
Ok, I've got the logo, I've got the patches. Now when does the Linux kernel get compiled ? Can't figure it out. Is it `nodeos-barebones` ?

**Comment by piranna** [comment]
Yes, nodeos-barebones :-) Apply the patch on the install script and create
a pull-request on its own repo ;-)

**Comment by piranna** [comment]
Waiting for https://github.com/NodeOS/nodeos-barebones/pull/1 to be merged to close this.

**Comment by piranna** [comment]
Done in master, clossing :-)
