### ISSUE TITLE
ES6 features in NodeOS

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#232]
Hey, i want to know if we can use es6 features like template strings and such things because nodejs.org (https://nodejs.org/en/docs/es6/) and kangax (https://kangax.github.io/compat-table/es6/#node4) shows that in node 4.4.3 we can use them.

And if we can make use of them, should we use it in strict mode?

**Comment by piranna** [comment]
I don't see why not... what do you want to work about?

**Comment by luii** [comment]
Currently im writing tests and the documentation of the `nodeos-mount-*` modules.
And isnt it better to set every script to strict mode because most of the es6 functions need strict mode

**Comment by piranna** [comment]
You are right, so if you want to add strict mode you are welcome :-)

**Comment by luii** [comment]
Cool thanks, i think we should create Guidelines for creating modules for NodeOS
Because if another person creates a core module for NodeOS and this module is then in Non strict mode but every other Module is in strict mode, this module can create errors but they are not registered as errors and this is crucial for stability

**Comment by piranna** [comment]
I agree, or better than that, a checker tool similar to 'standard' so it's
just needed to exec it to know if it's valid. One of the first things, 100%
tests coverage with my module 'coverdeeps' and full strict mode, do you
agree? :-)

**Comment by luii** [comment]
I like the Idea but wouldnt it be to much effort to write such thing?

**Comment by piranna** [comment]
One step at a time ;-) Let's start finishing coverdeeps and we'll move
later to the guidelines checker.

I like the Idea but wouldnt it be to much effort to write such thing?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/NodeOS/NodeOS/issues/232#issuecomment-214820596>

**Comment by lite20** [comment]
I like this idea. I can write a simple tool to do the validation after I
get this boot logo task completed.

**Comment by piranna** [comment]
There you have :-)

**Comment by lite20** [comment]
Faaaaantastic!

**Comment by lite20** [comment]
As I currently don't have access to my usual dev computer, I'll be working on this validation tool for now. I've dubbed it NSV for (node script validator) and it'll be up on Github ^_^

**Comment by piranna** [comment]
Cool :-) Take a look on `standard` module, seems it would be needed only to tune-up it a little bit, there's no need to write it from scratch, just config it :-)

**Comment by lite20** [comment]
> Cool :-) Take a look on standard module, seems it would be needed only to tune-up it a little bit, there's no need to write it from scratch, just config it :-)

Ah, I will check this out!

**Comment by lite20** [comment]
@piranna do you wan't leave the 'no semicolons' rule too? I'm a fan of semicolons but I could easily have it rip them from the code if you want.

**Comment by piranna** [comment]
It's 2016 AND node.js takes lots of ideas from Python, so no semicolons
here except for smileis ;-)

**Comment by lite20** [comment]
Roger that :P

Mind if I make it auto correct the code?

**Comment by piranna** [comment]
How do you plan to do it? I have started to use eslint but didn't have time
to add it everywhere...

**Comment by lite20** [comment]
@piranna simply correct the formatting errors that it can find, dump them to a temporary file as it parses the script. When done, I'll have it replace the old file with the new updated file, and report any changes it couldn't make on it's own. I'll probably have this as an optional feature.

**Comment by piranna** [comment]
Eslint has an option to auto-correct some of the most trivial and common cases, so maybe it's not needed to create a new tool :-) Anyway I think it's better to don't do the autocorrection automatically by default, I have been forced to do it in the past and it works, but you mostly feels the code as it has been written by other if you don't config it correctly.

**Comment by tylerl0706** [comment]
I'm a fan of Eslint! I'm also a fan of Gulp. Why not: https://github.com/adametry/gulp-eslint ? using https://github.com/feross/eslint-config-standard ?

**Comment by luii** [comment]
we could also use the package.json scripts

**Comment by tylerl0706** [comment]
Package.json with eslint totally works for me. So is the issue about code style or ES6 support?

**Comment by piranna** [comment]
> Package.json with eslint totally works for me. So is the issue about code style or ES6 support?

I think the original issue was about "upgrade" NodeOS source code to use ES6 features... I'm -0 here, I agree on use ES6 features on new source code (I'm already doing so partially) now that we use Node.js 6.x or update the code when we add new features or do some bug fixes or add documentation since "we are there", but I think it's a bit of waste of time to upgrade old code that's working to ES6 just for the shake of it, we could use that time to add tests for example (and upgrade the code ES6 once "we are there" ;-) ).

Regarding eslint I don't like too much `standard`, specially the K&R brackets in the same line instead of the Allman ones on a new one... :-P

**Comment by luii** [comment]
@piranna but for the clarity, is it ok from now on to use es6?

> Regarding eslint I don't like too much standard, specially the K&R brackets in the same line instead
> of the Allman ones on a new one... :-P

Until this sentence i didnt knew the indentation styles had names :D
Im more the K&R type

**Comment by piranna** [comment]
> @piranna but for the clarity, is it ok from now on to use es6?

Yes, it's ok :-)

>> Regarding eslint I don't like too much standard, specially the K&R
brackets in the same line instead
>> of the Allman ones on a new one... :-P
>
> Until this sentence i didnt knew the indentation styles had names :D
> Im more the K&R type

It's what more people is use to due to legacy systems and technology
heritage, but it's not the better one...

**Comment by tylerl0706** [comment]
I'm cool with using any code style template. ESLint has a ton of presets. I like the Airbnb preset a lot. But honestly, it doesn't matter to me. 

I'm not the biggest fan of some of the standard rules just cause... I don't know it's very strange haha. But if everyone has their heart on using Standard it's totally cool for me :)

I can totally work on adding ESLint if you want. Just need to know the rules everyone likes :)

**Comment by piranna** [comment]
I started to work on some of them but don't remember where :-P

**Comment by tylerl0706** [comment]
So I found this: http://noeticforce.com/best-javascript-style-guide-for-maintainable-code it's a year old though...

I'm fine with just picking a style guide and going for it unless everyone else has strong opinions on code style. Or we can take a style guide and modify it. 

We could close this issue and open a new one to specifically talk about code style

**Comment by piranna** [comment]
> We could close this issue and open a new one to specifically talk about code style

Good idea.

**Comment by tylerl0706** [comment]
@piranna: should I do that? haha

I can't actually close this issue :(

**Comment by Coretool** [comment]
@tylerl0706 I close for you

**Comment by piranna** [comment]
Create the new one then :-)

**Comment by tylerl0706** [comment]
I'll do that today! Starting at my new job today! (I'm in Seattle, now :-) )

**Comment by piranna** [comment]
Congrats! :-)
