### ISSUE TITLE
Is it time for 1.0?

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#233]
In the last weeks this project has been to quiet both of personal issues of me and others, but also due to some problems that has arised with the final points on the [1.0 roadmap](https://github.com/NodeOS/NodeOS/issues/37), regarding bugs on Node.js and pty.js that are showstoppers for the rewritten nsh, but also for problems with ngit git client. Since these are the only pending points and the core seems to be very stable, what do you think about moving them to post-1.0 and release it? This would allow to do some breaking changes I was planning for post-1.0, specially regarding to the split on several modules and more important the move to npm 3, since the new dependencies algorythm is incompatible with how NodeOS is build.

What do you think? Should be kick it off and release 1.0 once for all, or should first try to fix that issues first? The only one that I find more feasable is the ability to create new users from `logon`, and maybe the `git` client but I don't have control over that last one... The `pty.js` openpty problems probably I could be able to fix them refactoring the module to clean it up and add tests to see if I can find the bug...

/cc @formula1 @lite20 @luii @tylerl0706 @chjj

**Comment by tylerl0706** [comment]
I know I've been pretty inactive the past weeks. It's the end of semester craziness that always gets me! I'm graduating on Thursday so life will be a LOT less crazy after that and I'll actually be around. 

That said, I thought about a NodeOS without git and I feel as if doesn't really feel like a 1.0 without it. Maybe I'm totally wrong. It's,  of course,  my fault for not having it done. 

On the other hand, feeling that momentum of releasing the 1.0 might rejuvenate the quiet repo.

I'm not against any option :) I think both make sense for different reasons.

**Comment by lite20** [comment]
As I imagine each of us have been away for our own reasons I too have been jammed lately with projects in all my classes at the same time, my driving road test in a week, and soccer. (Plus my computer was confiscated)

However I'm still as hyped as ever! Unlike traditional behavior I'm going to suggest against a 1.0 release. Although a 1.0 release is an exhilarating thought that could create momentum 1.0 for any application generally signifies meeting the software minimum requirements.

As a server OS, git is the last essential addition. With git added, the OS can count as complete  reaching its goal and therefore worthy of the title "first edition".

However the hype is still awesome and we can consider incrementing some digits even if it isn't a 1 in the major.

**Comment by piranna** [comment]
So seems both we have been so busy lately and probably in some weeks we'll be a lot more free to move this forward (I hope to read my thesis soon, too :-) ) AND seems to be some consensus about git it's mandatory for 1.0 :-P

So ok, let's do that, we'll try to move this forward and don't publish the 1.0 release until npm can install dependencies from a git repository, do you agree on that as the minimal feature set? :-)

**Comment by tylerl0706** [comment]
I think that sounds good! :)

**Comment by lite20** [comment]
Sounds excellent. Where do we sit with progress on the git client?

**Comment by piranna** [comment]
The last thing I remember where some not-reproducible problems... Maybe if
they are explained we could try to replicate the environment, or find other
ways where to progress...

**Comment by luii** [comment]
@piranna Is there a Issue for this?

**Comment by piranna** [comment]
Yes, there's an issue to follow the progresses on the git client.

**Comment by lite20** [comment]
Closing because 1.0 is a thing :)
