### ISSUE TITLE
Gitter chat room ? 

### ISSUE THREAD

**Issue by jaumard** [NodeOS/NodeOS#235]
Hi, 

I just found this project and I'm really exited about it ! I would like to help if I can :) is there any Gitter chat room to discuss about the project ?

Of course this kind of OS will be great as server but I would like to see it running also on a mobile device with a desktop screen when HDMI is used like MaruOS. But to do this we need an UI, I see multiple issue about this if you don't mind let me know what the official position about this ^^.

Thanks ! Keep you the great work !

**Comment by Coretool** [comment]
I don't think that we have a gitter chat room... Afaik everything is discussed via issues. If you're interessted in the GUI, go check out noGui, it's an approach to give NodeOS a gui!

**Comment by luii** [comment]
We have the #nodeos on the freenode irc

**Comment by lite20** [comment]
> We have the #nodeos on the freenode irc

Does anyone use that? Most discussion that I know of happens via github issues just as @Coretool mentioned.

**Comment by lite20** [comment]
>  I would like to see it running also on a mobile device 

You'll be working a lot with me then as I'm (the only declared) one working on getting this to the mobile scene. Of course our GUI'd editions won't reside here, but as the GUI and all will be but npm modules, we have but to install them on the nodeos build.

>  But to do this we need an UI, I see multiple issue about this if you don't mind let me know what the official position about this ^^.

At the moment all progress is occurring in the noGUI project. NoGUI is the program that will render webpages to the devices display. Think of it as an embedded chrome (essentially, that's what it is).

So if you're wondering where to get started, our first steps are to push [noGUI](https://github.com/Coretool/noGUI) along!

**Comment by piranna** [comment]
AFAIK the discussion is only done here on GitHub issues, using them as a sort of issues tracker, forum and mail list... This allow to have a single point for all the project communications, if there's any other communication channel I'm not aware of it.

Regarding usage on mobile platforms I'm also interested on this and will accept any pull-request about this. nodeos-cross-toolchain can compile an ARM linux kernel, but when executing /init binary it throw a kernel panic. I don't have experience on ARM so I don't know if it's a QEmu problem and didn't test it on real hardware yet, so any help here is welcome.

And also, any help on noGUI or in general is welcome, too :-)

**Comment by lite20** [comment]
Yes I'll be doing extensive work on maintaining NodeOS mobile, and nano
computer support @piranna . I'm doing a hardware run soon but yes the
kernel panic is odd. I'll have a look at it soon.

**Comment by piranna** [comment]
Just curious, what ARM platform are you using?

**Comment by jaumard** [comment]
Thanks guys ! To be honest I don't know anything about OS world, generally I'm Android/iOS dev or front/end (Web with JEE or NodeJS) dev. But I want to learn and help you with this ^^. I have the all family PI at home if it's supported :)

I will take a look at noGUI then ! I'll try to build NodeOS on my mac but so far no luck ^^ 

And maybe start to make a desktop app would be cool too ^^ (hope there will be some bridge to run native command on your noGUI) like this the desktop app can run other app with a windows system, check processes, and why not running Android applications ect...

**Comment by jaumard** [comment]
I manage to test nodeOS on Ubuntu :) how can I set the keyboard to Azerty ? ^^

**Comment by luii** [comment]
Currently there is no binary to change the keyboard layout as far as i know
I personnly use the QWERTZ layout, so i know this problem.

**Comment by piranna** [comment]
It could be done setting it as one of the boot parameters. It's not out of
the box, but it's an easy task. Pull-requests are welcome :-)

**Comment by lite20** [comment]
> Thanks guys ! To be honest I don't know anything about OS world, generally I'm Android/iOS dev or front/end (Web with JEE or NodeJS) dev. But I want to learn and help you with this ^^. I have the all family PI at home if it's supported :)

> I will take a look at noGUI then ! I'll try to build NodeOS on my mac but so far no luck ^^

> And maybe start to make a desktop app would be cool too ^^ (hope there will be some bridge to run native command on your noGUI) like this the desktop app can run other app with a windows system, check processes, and why not running Android applications ect...

Go ahead and shoot me an email at lite260@gmail.com I'll be glad to get you up to speed on how all the under systems work. There's also a bit of useful information on the wiki! (It's in the process of being upgraded)

P.S. if you don't mind, we could do some tests with the PI. NodeOS is having issues with ARM, maybe we can work together and iron those out!

**Comment by lite20** [comment]
> Currently there is no binary to change the keyboard layout as far as i know
I personnly use the QWERTZ layout, so i know this problem.

Thread created: https://github.com/NodeOS/NodeOS/issues/236

**Comment by luii** [comment]
@piranna  I think we should use gitter for answering questions and helping people and use GH Issues for Feature requrests (and discussions) and bugs

**Comment by piranna** [comment]
I'm not too much into chats and ingeractive channels, but I'm not against
them. If someone want to manage the Gitter channel it's ok for me.

**Comment by serapath** [comment]
I found this one `https://gitter.im/NodeOS/NodeOS`. There is no chatting going on, but @groundwater, @piranna and @luii are members.

What I love about gitter is:
* that it's very convenient to use from within the browser
* I can send messages to people offline & online
* it notifies me on desktop and mobile
* it preserves all history and allows to search it.
* i can use markdown
* it auto-syncs with activity on the corresponding gthub repositories

with IRC this is only possible for advanced users.
I love how the `dat` people solved it. They have an IRC bot, who syncs their gitter channel with irc.

**Comment by luii** [comment]
I created the chat just today

**Comment by serapath** [comment]
+1 :-)

**Comment by lite20** [comment]
> Just curious, what ARM platform are you using?

Modded Pi's and custom builds for now :D @piranna

**Comment by lite20** [comment]
Closing because we have one now
