### ISSUE TITLE
Blog's RSS is empty

### ISSUE THREAD

**Issue by aurium** [NodeOS/NodeOS#238]
https://zapier.com/engine/rss/956964/nodeos-blog
(also: this url is not nice)

**Comment by piranna** [comment]
RSS is autogenerated, since internally we use GitHub issues. We used before
Yahoo! Pipes and worked like a charm, but since they closed it we needed to
look for a free alternative, and Zappier seemed to make the work althought
is not so reliable. If you know of an alternative please let us to know.
