### ISSUE TITLE
Test prebuild images

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#241]
Add tests to ensure the prebuild images are working before publishing them.

**Comment by lite20** [comment]
How would we go about automating this?

**Comment by piranna** [comment]
Honestly I'm not sure, the most I can think about is to finish to split the
layers to independent modules and test them separately.

**Comment by piranna** [comment]
I tried to automate this without luck, because it's possible to give kernel parameters only when starting QEmu with the `-kernel` argument, not directly from the ISOs. Only two options would be to use an external kernel, or add an option to the ISOs bootloader.

**Comment by lite20** [comment]
Both seam like reasonable ways of handling it. If we want to test the included kernel it's probably better to use add an option to the ISOs bootloader.

**Comment by piranna** [comment]
> Both seam like reasonable ways of handling it. If we want to test the included kernel it's probably better to use add an option to the ISOs bootloader.

Problem with that, how to pass the option to the bootloader? From the machine/emulator point of view, it's like another OS... :-/ Maybe an external bootloader? Is something like this?

**Comment by lite20** [comment]
@piranna how do you use external things with QEMU?

**Comment by lite20** [comment]
I think the prebuilds may be something that we humans need to physically test, which I don't mind as I test every prebuild anyway.

**Comment by piranna** [comment]
> @piranna how do you use external things with QEMU?

What kind ones?

**Comment by piranna** [comment]
> I think the prebuilds may be something that we humans need to physically
test, which I don't mind as I test every prebuild anyway.

Yes, but it's better if we can be able to automate it.

Seems syslinux has a SERIAL option that open a serial port and allow to
control it, if that's possible we could be able to add a timeout and use
that time window to add the 'console=ttyS0' kernel option so we could be
able to test the ISO images :-)

**Comment by lite20** [comment]
Oh okay, sounds pretty neat!

**Comment by piranna** [comment]
Fixed in master, clossing.
