### ISSUE TITLE
Image viewer: lightgallery 

### ISSUE THREAD

**Issue by atilacamurca** [NodeOS/NodeOS#242]
<http://sachinchoolur.github.io/lightgallery-desktop/>

Do you guys already have plans to have an image viewer, I just found this and it looks good.

**Comment by piranna** [comment]
It looks nice, but it falls way long from NodeOS focus, not only because NodeOS left the apps as an user decision, but also because for GUI apps we propose to use pure HTML5 mechanism that can work on any web browser, that's not the case of Electron. Thank you anyway.
