### ISSUE TITLE
Non-blocking stdio in Node.js 6.x.x

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#245]
Hey just want to point out that in the new versions of node.js stdio is non-blocking as @juliangruber stated.

> Since node 6, stdio is non blocking by default. Besides having several advantages, one obvious
> disatvantage is that sometimes the program exits before all output has been printed. This module
> changes it back to blocking! [blocking-stdio](https://github.com/juliangruber/blocking-stdio)

**Comment by piranna** [comment]
I have give a try to the `nsh` rewrite on Node.js 6.2.2 and definitely it doesn't output anything at all... :-/ Bad thing :-(

**Comment by lite20** [comment]
@piranna does the module [blocking-stdio](https://github.com/juliangruber/blocking-stdio) help at all? Have you tried using it? What's nsh's state by the way? Does it work now :smile: ?

**Comment by piranna** [comment]
No, I didn't tested it.

> What's nsh's state by the way? Does it work now :smile: ?

Let's hope it does... :-)

**Comment by luii** [comment]
Now that we're way ahed of 6.x.x i think its ok to close.
