### ISSUE TITLE
Homepage link is broken.

### ISSUE THREAD

**Issue by m31271n** [NodeOS/NodeOS#246]
<img width="851" alt="screen shot 2016-06-06 at 11 35 53 am" src="https://cloud.githubusercontent.com/assets/12194646/15811408/e898d2fe-2bda-11e6-92fb-804eb2c9ed85.png">

Read More links to http://node-os.com/blog/get-involved/,  but the link is broken.

**Comment by lite20** [comment]
@piranna how to update the webpage?

**Comment by piranna** [comment]
> @piranna how to update the webpage?

It's on the [nodeos.github.io](https://github.com/NodeOS/nodeos.github.io) repository, to publish it push the changes to the `gh-pages` branch. Don't know if we should use it directly and remove the `master` branch...

**Comment by lite20** [comment]
Would we like to invest in repairing this? (Is it still broken?) As the new page is underworks

**Comment by luii** [comment]
Already done. Closing.
