### ISSUE TITLE
nodeos-init musl command not found

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#248]
I've got that error with Arch Linux

``` bash
Compiling init
make: x86_64-nodeos-linux-musl-gcc: Kommando nicht gefunden
<eingebaut>: die Regel für Ziel „init.o“ scheiterte
make: *** [init.o] Fehler 127
rmdir: konnte '/home/philipp/Dokumente/github/NodeOS/node_modules/nodeos-barebones/build/nocona' nicht entfernen: Datei oder Verzeichnis nicht gefunden
```

**Comment by Coretool** [comment]
Try to install `nodeos-barebones` again ?!

**Comment by luii** [comment]
I just cloned the repo and got  this

**Comment by piranna** [comment]
Does this stil apply on master?

**Comment by luii** [comment]
I get errors but not this one

**Comment by piranna** [comment]
> I get errors but not this one

Can you post them? If you have some bizarre problems, maybe you would clone the NodeOS repo again and start over after saving your changes somewhere...

**Comment by luii** [comment]
```bash
> genfatfs@1.0.1 install /home/philipp/Dokumente/NodeOS/node_modules/nodeos-rootfs/node_modules/genfatfs
> prebuild-install -d https://github.com/NodeOS/genfatfs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build


> nodeos-rootfs@1.0.0-RC2.1 install /home/philipp/Dokumente/NodeOS/node_modules/nodeos-rootfs
> scripts/install

     fetch : https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.gz
  progress : [====================] 100% 0.0s

npm ERR! Linux 4.6.2-1-ARCH
npm ERR! argv "/home/philipp/.nvm/versions/node/v4.4.2/bin/node" "/home/philipp/.nvm/versions/node/v4.4.2/bin/npm" "i"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! path /home/philipp/Dokumente/NodeOS/node_modules/nodeos-usersfs/node_modules/nodeos-nodejs/node_modules/nodeos-cross-toolchain/bin/addr2line
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/philipp/Dokumente/NodeOS/node_modules/nodeos-usersfs/node_modules/nodeos-nodejs/node_modules/nodeos-cross-toolchain/bin/addr2line'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/philipp/Dokumente/NodeOS/npm-debug.log
```

**Comment by piranna** [comment]
Yeah, well... I've deprecated npm2 since now dependencies on npm3 has a deterministic flowchart :-P Upgrade to Node.js >= 5.0.0 or npm >= 3.0.0 and you should go :-)

**Comment by luii** [comment]
install process with node 5.12.0 seems to be fine but i get another error that dont is displayed 
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/home/philipp/.nvm/versions/node/v5.12.0/bin/node',
1 verbose cli   '/home/philipp/.nvm/versions/node/v5.12.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle NodeOS@1.0.0-RC2~prestart: NodeOS@1.0.0-RC2
6 silly lifecycle NodeOS@1.0.0-RC2~prestart: no script for prestart, continuing
7 info lifecycle NodeOS@1.0.0-RC2~start: NodeOS@1.0.0-RC2
8 verbose lifecycle NodeOS@1.0.0-RC2~start: unsafe-perm in lifecycle true
9 verbose lifecycle NodeOS@1.0.0-RC2~start: PATH: /home/philipp/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/node-gyp-bin:/home/philipp/Dokumente/NodeOS/node_modules/.bin:/home/philipp/.nvm/versions/node/v5.12.0/bin:/home/philipp/.nvm/versions/node/v5.12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle NodeOS@1.0.0-RC2~start: CWD: /home/philipp/Dokumente/NodeOS
11 silly lifecycle NodeOS@1.0.0-RC2~start: Args: [ '-c', 'scripts/start' ]
12 silly lifecycle NodeOS@1.0.0-RC2~start: Returned: code: 1  signal: null
13 info lifecycle NodeOS@1.0.0-RC2~start: Failed to exec start script
14 verbose stack Error: NodeOS@1.0.0-RC2 start: `scripts/start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/philipp/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/philipp/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid NodeOS@1.0.0-RC2
16 verbose cwd /home/philipp/Dokumente/NodeOS
17 error Linux 4.6.2-1-ARCH
18 error argv "/home/philipp/.nvm/versions/node/v5.12.0/bin/node" "/home/philipp/.nvm/versions/node/v5.12.0/bin/npm" "start"
19 error node v5.12.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error NodeOS@1.0.0-RC2 start: `scripts/start`
22 error Exit status 1
23 error Failed at the NodeOS@1.0.0-RC2 start script 'scripts/start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the NodeOS package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     scripts/start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs NodeOS
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls NodeOS
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Also i tried to install with 6.2.1 and got very strange errors

**Comment by piranna** [comment]
Have you executed `npm run build` after `npm install`? Now dependencies downloading and build process are splitted due how npm3 works. Yes, I forgot to add it to the docs, sorry... :-(

**Comment by luii** [comment]
Thats maybe the key to the thing

**Comment by piranna** [comment]
> Thats maybe the key to the thing

Check it. If it works, could you be able to update the readme?

**Comment by luii** [comment]
@piranna got this after `npm start`

```bash
→ npm start                                                           [fb487d9]

> NodeOS@1.0.0-RC2 start /home/philipp/Dokumente/NodeOS
> scripts/start

qemu-system-x86_64: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```

**Comment by piranna** [comment]
You need to install the shared library. Exec `sudo bin/install-dependencies` :-)

I've tried to build a static version of qemu, but `libsdl` needed for the framebuffer is giving problems... :-( I would remove it and allow only a text interface and *maybe* use the VNC interface for graphic one, but this would require a VNC client to access it... What do you think?

**Comment by luii** [comment]
I dont have any idea for what the framebuffer is for and whats a vnc interface is, ive never worked on this low level but id like to know what it is

**Comment by piranna** [comment]
Framebuffer is a simple way to paint graphics on the screen, for example the small Tux penguin on boot is paint using framebuffer by the kernel itself. VNC is a protocol for remote graphic sessions like TeamViewer or RemoteDesktop, so using it we would not need to use SDL to paint a "real" screen.

**Comment by lite20** [comment]
@luii if you want a bit more, the framebuffer represents the byte storage of a graphic display, like a monitor. You interact with it via shared memory and alter it's contents much like an RGB image file.

**Comment by piranna** [comment]
I think the best option would be to remove SDL support and use by default only a text interface on the same terminal it's executed, and the ones that want to use a graphic interface, then they use a VNC viewer. Thoughs?

**Comment by d3x0r** [comment]
I updated to npm@3  (.10.6)
I tried npm run build
I treid bin/install-dependancies (no dpkg; am also on arch) 


[root@tower2 NodeOS]# npm3 install nodeos-barebones
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
NodeOS@1.0.0-RC2 /home/d3x0r/work/NodeOS
├── UNMET PEER DEPENDENCY nodeos-barebones@1.0.0-RC2.3 (git://github.com/nodeos/nodeos-barebones.git#36e886e120ed54569b99aeb2630ac300634b7084)
├── UNMET PEER DEPENDENCY nodeos-initramfs@1.0.0-RC2.4 (git://github.com/nodeos/nodeos-initramfs.git#1f48f4150cc62a83c8c73c6a4ad86b8856091452)
└─┬ nodeos-usersfs@1.0.0-RC2 (git://github.com/nodeos/nodeos-usersfs.git#1d20cad02ce8466a7b99922857161388de087d99)
  ├── bin-getty@0.0.0  extraneous (git://github.com/nodeos/node-bin-getty.git#d8346f15860de4f5b6cc534217429a00016e5793)
  ├── bin-ifconfig@0.0.0  extraneous (git://github.com/nodeos/ifconfig.git#f07ccd16f4ad8b4c47c2880aad75179d99390ab7)
  ├── bin-ip@0.0.0  extraneous (git://github.com/nodeos/ip.git#f0e685493db31ca9117b93245d8a8e85478b476c)
  └── bin-nsh@0.4.0  extraneous (git://github.com/piranna/nsh.git#51d8131d34d1f78937e54dc33b5e954718212632)

npm WARN nodeos-rootfs@1.0.0-RC2.0 requires a peer of nodeos-barebones@1.0.0-RC2.2 but none was installed.
npm WARN nodeos-rootfs@1.0.0-RC2.0 requires a peer of nodeos-initramfs@1.0.0-RC2.3 but none was installed.

was also that version og gcc- not found.

**Comment by piranna** [comment]
What's exactly the problem do you have?

**Comment by d3x0r** [comment]
"What's exactly the problem do you have?"

UNMET PEER DEPENDENCY nodeos-barebones@1.0.0-RC2.3 (git://github.com/nodeos/nodeos-barebones.git#36e886e120ed54569b99aeb2630ac300634b7084)
├── UNMET PEER DEPENDENCY nodeos-initramfs@1.0.0-RC2.4 (git://github.com/nodeos/nodeos-initramfs.git#1f48f4150cc62a83c8c73c6a4ad86b8856091452)

-or-

x86_64-nodeos-linux-musl-gcc: Command not found

**Comment by piranna** [comment]
Unmeet dependencies are not the problem, you should be doing it wrong in
other place. I can't be able to test NodeOS building in Arch linux so you
are alone here, but I can help you and accept pull-requests to support it.

**Comment by d3x0r** [comment]
how about some hints to diagnose why it is failing?

why I can't npm3 install  or npm3 install ndoeos-barebones ? always fails.

**Comment by Coretool** [comment]
@d3x0r Is `0.10.6` your node version ? If so, could you update that to a newer ? I ran into some problems (on arch too) when I tried building nodeOS with 'very old' versions of node

**Comment by d3x0r** [comment]
No Node 6.5.0 is my node version.
npm 3 has a sub-version of .10.6     (3.10.6)

**Comment by luii** [comment]
@d3x0r Im using Arch too, please install the following Prerequisites and Dependencies from this [page](https://github.com/NodeOS/NodeOS/wiki/Building-From-Source#step-2-arch-linux-dependencies)

**Comment by piranna** [comment]
bin/installDependencies should be updated to detect Arch linux and install
the correct dependencies...

**Comment by piranna** [comment]
We could use something like https://github.com/arve0/system-install

**Comment by d3x0r** [comment]
[root@tower2 b]# pacman -S gcc texinfo python2 bc pixman lib32-pixman cdrkit cpio autoconf automake sdl
warning: gcc-6.1.1-5 is up to date -- reinstalling
warning: texinfo-6.1-4 is up to date -- reinstalling
warning: python2-2.7.12-1 is up to date -- reinstalling
warning: pixman-0.34.0-1 is up to date -- reinstalling
error: target not found: lib32-pixman
warning: cpio-2.12-3 is up to date -- reinstalling
warning: autoconf-2.69-3 is up to date -- reinstalling
warning: automake-1.15-1 is up to date -- reinstalling
warning: sdl-1.2.15-7 is up to date -- reinstalling

No help.

**Comment by d3x0r** [comment]
Did some more digging, and in node_modules there are things like nodeos-barebones (with a few small files) 

Unfortunatly in nodeos-cross-toolchain this error shows up....

```
In file included from /home/d3x0r/work/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/gcc/cp/except.c:1023:0:
cfns.gperf: In function 'const char* libc_name_p(const char*, unsigned int)':
cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute
cfns.gperf:26:14: note: 'const char* libc_name_p(const char*, unsigned int)' previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function 'const char* libc_name_p(const char*, unsigned int)' used but never defined
make[2]: *** [Makefile:1065: cp/except.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

which if I take the error literally and a search I find
https://github.com/mxe/mxe/issues/1361

but then the nodeos-cross-toolchain disappears :(  so I can't really see what version of GCC it is that's failing... the previous issue has a fix from 19 days ago; but doesn't matter if it's not gcc 4.8/9 something

**Comment by piranna** [comment]
What version of Node js/npm and gcc are you using on your system?

**Comment by d3x0r** [comment]
```
[root@tower2 ~]# npm -v
3.10.6
[root@tower2 ~]# node -v
v6.5.0
[root@tower2 ~]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160802 (GCC)

```

**Comment by piranna** [comment]
Seems to be a problem in the version of gcc of Arch, try using an older
one. Reference build environment is Ubuntu, and nodeos-cross-compiler
generates a gcc 5.3.0 toolchain.

**Comment by piranna** [comment]
Any update on this? @luii and @d3x0r, are you still having problems with Arch, or we can close this?

**Comment by d3x0r** [comment]
I recently updated

npm -v
3.10.7

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.2.1 20160830 (GCC)


```
cd node_modules/nodeos-cross-toolchain
scripts/prebuild
scripts/build
```

And it still fails.

I updated scripts/prebuild to download 5.4.0 gcc but still use the 5.3.0 patch....

bin/build doesn't like running twice in a row with a partial build ... it doesn't re-extract linux headers somehow?

```
[root@tower2 nodeos-cross-toolchain]# scripts/build
Compiling musl
/home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/musl/configure: unknown option --silent
checking for C compiler...
/home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/musl/configure: cannot find a C compiler
```


I am getting a TON of these warnings; maybe a patch could help; mabye it's expanding multiple levels of macros...


```
/home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/gcc/config/elfos.h:170:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
In file included from ./tm.h:51:0,
                 from /home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/gcc/ddg.c:25:
/home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/gcc/defaults.h:126:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       fprintf ((FILE), ","HOST_WIDE_INT_PRINT_UNSIGNED",%u\n",  \
                        ^
```


Got a lot further.... but I suspect the patch has silently failed.

```
In file included from /home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/libgcc/libgcc2.c:27:0:
/home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/libgcc/../gcc/tsystem.h:87:19: fatal error: stdio.h: No such file or directory
compilation terminated.
make[2]: *** [Makefile:466: _muldi3.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/libgcc/libgcc2.c:27:0:
/home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/libgcc/../gcc/tsystem.h:87:19: fatal error: stdio.h: No such file or directory
compilation terminated.
make[2]: *** [Makefile:466: _negdi2.o] Error 1
In file included from /home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/libgcc/libgcc2.c:27:0:
/home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/deps/gcc/libgcc/../gcc/tsystem.h:87:19: fatal error: stdio.h: No such file or directory
compilation terminated.
make[2]: *** [Makefile:466: _lshrdi3.o] Error 1
make[1]: *** [Makefile:13307: all-target-libgcc] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:881: all] Error 2
+ exit 52
+ err 52
+ rmStep /home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/build/nocona/gcc_final
+ rm -rf /home/d3x0r/work/NodeOS/node_modules/nodeos-cross-toolchain/build/nocona/gcc_final
+ exit 52
```

**Comment by piranna** [comment]
I haven't used Arch before so I don't know what could be happening, sorry
:-(

**Comment by luii** [comment]
I cant reproduce these errors with Arch
I got a lot of warnings but the build finished.

```
Successfully built Layer-3 image 'usersfs'

> NodeOS@1.0.0-RC2 postbuild /home/philipp/Dokumente/github/NodeOS
> scripts/postbuild

------------------------------------------
Success!
You just built a custom NodeOS image
------------------------------------------

- Interactively run your image with:
    npm start

λ philipp [Dokumente/github/NodeOS] at  master ✔ 
→ npm start                                                                                             [6aede62]

> NodeOS@1.0.0-RC2 start /home/philipp/Dokumente/github/NodeOS
> scripts/start

qemu-system-x86_64: cannot initialize crypto: Unable to initialize gcrypt

```
```
→ gcc -v                                                                                                [6aede62]
Es werden eingebaute Spezifikationen verwendet.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Ziel: x86_64-pc-linux-gnu
Konfiguriert mit: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread-Modell: posix
gcc-Version 6.1.1 20160707 (GCC) 

λ philipp [Dokumente/github/NodeOS] at  master ✔ 
→ npm -v                                                                                                [6aede62]
3.10.3

λ philipp [Dokumente/github/NodeOS] at  master ✔ 
→ node -v                                                                                               [6aede62]
v6.5.0
```

**Comment by d3x0r** [comment]
Was that a new tree - a fresh clone from the git repo and then npm install?

**Comment by piranna** [comment]
@d3x0r, can you be able to download a fresh install and try again?

**Comment by d3x0r** [comment]
Yes, after hearing that news, I did.
unforutnatly 
npm install fails on genext2fs

```
configure.in:10: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:10: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:13: installing './compile'
configure.in:10: installing './install-sh'
configure.in:10: installing './missing'
Makefile.am: error: required file './README' not found
Makefile.am: installing './depcomp'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
parallel-tests: installing './test-driver'
*** automake failed :(
```

and genext2fs hasn't changed in 9 years....

**Comment by piranna** [comment]
Can you provide the full error output? That doesn't makes sense...

**Comment by d3x0r** [comment]
And unfortunatly when it fails, it evaporates so I can't go poke at it...

[err.txt](https://github.com/NodeOS/NodeOS/files/468148/err.txt)

The end of that says I should have info in npm-debug.log but I don't see one of those.

**Comment by d3x0r** [comment]
found npm-debug.log and attached it to last message

**Comment by piranna** [comment]
It's strange that it doesn't download a prebuild image of `genext2fs`, but more strange that that autoconf failed. Try to download [genext2fs](https://github.com/NodeOS/genext2fs) and compile it locally with `npm install` on your machine, to see where's the problem.

**Comment by d3x0r** [comment]
I did start a new project and just did npm install genext2fs, and it fails to build 
Makefile.am automagically requires README....
http://stackoverflow.com/questions/15013672/use-autotools-with-readme-md
Which there's options to work around.
After it had installed everything in test/node_modules/genext2fx  I had gone into that directory and did a 'touch README' and it finished.
The other version I had modified the Makefile.am to have 'AUTOMAKE_OPTIONS = foreign'  and that also built successfully.

Both of those modifications are outside the scope of this project unfortunately :)

```
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

	autoconf-2.69.tar.gz	2012-04-24 23:17	1.8M	 
```

And autoconf hasn't changed in 5 years... so I don't know how it has built on anyone elses system?  Unless there was a canned binary?

**Comment by luii** [comment]
@d3x0r im also using autoconf 2.69

**Comment by d3x0r** [comment]
automake is the thing that's actually thowing the README error

**Comment by luii** [comment]
@d3x0r automake is also 1.15 i really dont know why it throws this error on your system

**Comment by piranna** [comment]
I don't know too, i have revised it and the README file is already on the
Github repo... Could you be able to exec 'npm install genext2fs
--no-scripts' and tell us if it's available there?

**Comment by d3x0r** [comment]
Still fails...
tracked down the npm package.jon for genext2fs...


```
 cat ~/.npm/genext2fs/1.4.1-0/package/package.json
{"name":"genext2fs","version":"1.4.1-0","description":"ext2 filesystem generator for embedded systems","bin":{"genext2fs":"genext2fs"},"main":"index.js","scripts":{"BigRedButton":"scripts/BigRedButton","build":"scripts/build","install":"prebuild-install -d https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build","start":"./genext2fs","test":"./test.sh"},"repository":{"type":"git","url":"git+https://github.com/NodeOS/genext2fs.git"},"keywords":["ext2","ext3","ext4","filesystem","image"],"author":{"name":"Xavier Bestel","email":"xavier.bestel@free.fr"},"license":"GPL-2.0","bugs":{"url":"https://github.com/NodeOS/genext2fs/issues"},"homepage":"https://github.com/NodeOS/genext2fs#readme","dependencies":{"prebuild-install":"1.0.2"},"devDependencies":{"prebuild":"^4.2.2"},"contributors":[{"name":"Xavier Bestel","email":"xavier.bestel@free.fr"}],"gitHead":"c9a96b7a34cecdb81ace5e51e417b51a0a740275","_id":"genext2fs@1.4.1-0","_shasum":"bd002532151538adfdc29995cd83e281b2c3887b","_from":"genext2fs@latest","_npmVersion":"3.9.3","_nodeVersion":"6.2.1","_npmUser":{"name":"piranna","email":"piranna@gmail.com"},"dist":{"shasum":"bd002532151538adfdc29995cd83e281b2c3887b","tarball":"https://registry.npmjs.org/genext2fs/-/genext2fs-1.4.1-0.tgz"},"maintainers":[{"name":"piranna","email":"piranna@gmail.com"}],"_npmOperationalInternal":{"host":"packages-12-west.internal.npmjs.com","tmp":"tmp/genext2fs-1.4.1-0.tgz_1466686621501_0.9280801126733422"},"directories":{},"_resolved":"https://registry.npmjs.org/genext2fs/-/genext2fs-1.4.1-0.tgz","readme":"ERROR: No README data found!"}
```

"tarball":"https://registry.npmjs.org/genext2fs/-/genext2fs-1.4.1-0.tgz"

That tarball does not have README.



```
[root@tower2 makeextfs]# wget https://registry.npmjs.org/genext2fs/-/genext2fs-1.4.1-0.tgz
--2016-09-14 10:39:47--  https://registry.npmjs.org/genext2fs/-/genext2fs-1.4.1-0.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 151.101.40.162
Connecting to registry.npmjs.org (registry.npmjs.org)|151.101.40.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93170 (91K) [application/octet-stream]
Saving to: ‘genext2fs-1.4.1-0.tgz’

genext2fs-1.4.1-0.tgz            100%[=======================================================>]  90.99K  --.-KB/s    in 0.07s

2016-09-14 10:39:47 (1.34 MB/s) - ‘genext2fs-1.4.1-0.tgz’ saved [93170/93170]

[root@tower2 makeextfs]# ls
genext2fs-1.4.1-0.tgz  nm  node_modules  npm-debug.log
[root@tower2 makeextfs]# tar -zxf genext2fs-1.4.1-0.tgz
[root@tower2 makeextfs]# ls
genext2fs-1.4.1-0.tgz  nm  node_modules  npm-debug.log  package
[root@tower2 makeextfs]# cd package/
[root@tower2 package]# ls
AUTHORS     clean.sh      debian            genext2fs.8  INSTALL      NEWS          scripts        test.sh
autogen.sh  configure.in  device_table.txt  genext2fs.c  m4           package.json  test-gen.lib   TODO
ChangeLog   COPYING       genext2fs         index.js     Makefile.am  README.md     test-mount.sh
[root@tower2 package]#
```

**Comment by piranna** [comment]
So it seems that would be the reason... since it was working correctly with
prebuild, probably I didn't paid more atention to that.

**Comment by luii** [comment]
@d3x0r do you still have these errors from 2 years ago? I've just reinstalled Arch and it works like a charm just like before.

**Comment by d3x0r** [comment]
Haven't tried in a bit...

**Comment by luii** [comment]
Would be good to know because we have some dead issues that are already resolved

**Comment by d3x0r** [comment]
Finally got back around to checking... did a
```
#git pull  
#npm install .
#npm run build

Success!
You just built a custom NodeOS image

#npm start 
(#pacman -S libcurl-gnutls)
#npm start  # ... and get an X window from qemu :)
```
works for me :)
