### ISSUE TITLE
Release 2016-06-16 Empty

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#252]
The release 2016-06-16 contains nothing but a README and a run script in each of its packages. Why is this?

**Comment by piranna** [comment]
Good catch. I'm doing some huge (but cool ;-) ) changes and somethings are getting broken, but I hope they will be for good :-) I've just removed it :-)

**Comment by lite20** [comment]
Ah okay! If you'd like, next time there's a blank I can remove it myself? Save you the time.

**Comment by piranna** [comment]
Ok, that would be cool :-)
