### ISSUE TITLE
kexec fails to compile

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#254]
Unfortunately, the build process is still fighting me. At the moment, kexec fails to compile apparently with legitimate code errors. Do I need to use a different npm version? Error: http://pastebin.ubuntu.com/17719186/

**Comment by lite20** [comment]
Was using the wrong node version :)

**Comment by piranna** [comment]
Kexec was giving me lately some ugly problems... :-/ Maybe we are giving
too much pressure on the build mechanism?

**Comment by lite20** [comment]
@piranna what do you mean by that?

**Comment by piranna** [comment]
Problems with node-gyp where memory rampaged.

**Comment by lite20** [comment]
@piranna oh! Yeah the memory usage of the build process is remarkable. Are there ways that we could shrink it? What exactly is it that's eating so much memory? Only node-gyp?

**Comment by piranna** [comment]
Memory is mostly wasted by 'download' module, since it cache the full file
in memory. Seems it now support streams, so if you want to update
'download-manager', go for it.

**Comment by lite20** [comment]
@piranna will do. Could you tackle the new error I hit? I'm not finding the cause right off the bat, and since error's aren't reported with the line that called it... :P

**Comment by piranna** [comment]
You can find the line by searching the exit status. Anyway it should be
already fixed.

**Comment by lite20** [comment]
@piranna awesome I'll pull and try again.
