### ISSUE TITLE
ENOENT Build script error

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#255]
I hit the following error while compiling NodeOS. It appears like a misconstructed path and I'm going to go look into it right now and see if I can fix it myself.

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /home/lite/Documents/NodeOS/node_modules/nodeos-usersfs/node_modules/genext2fs/genext2fs
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/lite/Documents/NodeOS/node_modules/nodeos-usersfs/node_modules/genext2fs/genext2fs'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.

**Comment by piranna** [comment]
Does this stil apply on master?

**Comment by lite20** [comment]
I'll run a test again in 15 minutes to see.

**Comment by luii** [comment]
It dont apply for me on Arch Linux

**Comment by piranna** [comment]
So we can be able to close it?

**Comment by lite20** [comment]
Yep. We can close it.
