### ISSUE TITLE
1.0.0-RC2

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#259]
Just exactly one month after my degree thesis (with distinction, f*ck yeah ;-) ) and with a lot of nights without sleep, we have available [NodeOS 1.0.0-RC2](https://github.com/NodeOS/NodeOS/releases/tag/v1.0.0-RC2).

There has been some problems lately with the packages and the build process, but they are due to the heavy changes on the architecture that I hope they are going to be better for the future. The main one, is the split of the different layers on independent, isolated and autonomous projects that are themselves published on NPM, but also (and that's the important part) they have their own tests [passing on SemaphoreCI](https://semaphoreci.com/nodeos) and configured to work with [GreenKeeper](http://greenkeeper.io), so when we'll move to 1.0.0 final we'll be able to work on a real Rolling Release distro, and also there have been suggestion to [include an autoupdater](https://github.com/NodeOS/NodeOS/issues/247) on NodeOS itself. As an implementation detail, these layers and submodules (like [qemu](https://github.com/NodeOS/qemu), that it's now [published on npm](https://www.npmjs.com/package/qemu)) use extensively the [prebuild-install](https://github.com/mafintosh/prebuild-install) module to distribute prebuild images of their components, so no more pop-corn & movies to build NodeOS but just only a coffee. Yes, build process it's _blasingly fast_, and there's also a lot of room for improvement so we could end up blurrying the line between install and compile times by merging both processes ;-)

Other important change due to the increasing number of installing problems is the movement to npm3 and deprecation of npm2, so now build process is deterministic, faster and use less memory (also in NodeOS disk images, that have decreased ;-) ). Only drawback is that since npm3 considers the `install` process a one-time execution it's needed to split the install of the dependencies (`npm install`) and the generation of the NodeOS image (`npm run build`), but this also allow better flexibility and also remove the need of network connection when building the system since all the modules included on the NodeOS images has been set as dependencies of the NodeOS module itself, so they are getting cached for later.

But probably the most important change is Node.js, because not only it has got [it's own npm package](https://www.npmjs.com/package/nodejs) downloading prebuild binaries based on musl (maybe we should propose to Node.js org to host and distribute them side-by-side with their glibc ones?), but also it has been upgraded to bleeding edge 6.2.2! :-D There has been some problems because `/proc` was not being mounted and [it's needed by musl](https://github.com/nodejs/node/issues/7175#issuecomment-227170756), but thanks to it I give the chance to do some improvements to `nodeos-init` and now it's easier to use and robust, cleanly clossing the system itself on shut-down :-)

Let's more to 1.0.0! :-D

**Comment by lite20** [comment]
> Yes, build process it's blasingly fast

A

**Comment by lite20** [comment]
> Yes, build process it's blasingly fast

About time! Yaay!

> there have been suggestion to include an autoupdater on NodeOS itself

Haha hey look mom, it's me!

> they have their own tests passing on SemaphoreCI and configured to work with GreenKeeper, so when we'll move to 1.0.0 final we'll be able to work on a real Rolling Release distro

This is fantastic! A completely automated self-maintained system on it's way! The auto-updater will seal the deal ;)

> but also it has been upgraded to bleeding edge 6.2.2! :-D

There we go! Now we're a bleeding edge distro! The leading edge of technology, like we were always supposed to be!

> Let's more to 1.0.0! :-D

Let's go! :D

**Comment by piranna** [comment]
> Haha hey look mom, it's me!

Lol! X-D


> This is fantastic! A completely automated self-maintained system on it's way! The auto-updater will seal the deal ;)

Totally, in fact the cherry on the top of the cake would be to end up having [semantic release](https://github.com/semantic-release/semantic-release) :-D But it will be tough the get up to it in a sane and stable way... By splitting the layers in several projects tests have improved a lot, but they are a pain in the *ss and since now I will not have so much time as before due to work and personal life and maybe invest some time in other smaller side projects... :-/ That's one of the reasons I wantes to release the RC2 as soon as possible, to left NodeOS in a good state during some time, manage NodeOS is exhausting :-P Maybe it would be time to find some spondsors or fundraising...


> like we were always supposed to be!

Totally... at least we are a showcase of the state-of-the-art on several topics, that's not bad too :-D

**Comment by lite20** [comment]
> Maybe it would be time to find some spondsors or fundraising...

haha yeah that's not a bad idea!

> manage NodeOS is exhausting

Yeah! Even more a reason to get it to manage itself haha!

>  maybe invest some time in other smaller side projects

Ah you should check out some of my side projects if you have time; I feel you'd like them! HexCade for example, is an attempt to make a VM language but it implements a few awesome features most languages don't have and handles threads beautifully ^_^

**Comment by piranna** [comment]
> haha yeah that's not a bad idea!

There are several problems, like who is payed and how. Up this moment, beside the site domain that got payed by @groundwater (and anyway it's cheap) it's everything working on free services so there's no costs here, so it would make more sense to get sponsors to pay work hours or to fix some issues, but that's difficult to find and to do in a fair and ethical way... :-/ This would need a discussion on it's own, the debate would be really long...


> Yeah! Even more a reason to get it to manage itself haha!

That's why I have been trying to automate it as much as possible ;-)


> Ah you should check out some of my side projects if you have time; I feel you'd like them! HexCade for example, is an attempt to make a VM language but it implements a few awesome features most languages don't have and handles threads beautifully ^_^

Link or didn't happen ;-)

**Comment by lite20** [comment]
[Here you go!](https://bitbucket.org/Lite20/hexcade)

P.S. I'm still organizing things and I'll probably split HexCadi and Unipop into two separate projects but if you have any questions about how underlying technologies work (especially the one's I haven't written yet) just create a thread! Create many threads if you so please!

**Comment by piranna** [comment]
Why it's needed the preprocessor? Almost no languaje use them today or have
them integrated in the languaje itself...

**Comment by lite20** [comment]
Preprocessor allows developers to custom tween and optimize code before it's even shipped. Sort-of like javac for Java. @piranna

The client has it too though so it can be performed at runtime. Do you think this should be changed? (If so just create a new issue thread :D)

**Comment by piranna** [comment]
> Preprocessor allows developers to custom tween and optimize code before
it's even shipped. Sort-of like javac for Java. @piranna

JavaC is the compiler... By far I only know of two languages that use a
preprocesor, C and Python, and this later one is only to clean-up the sugar
sintaxys and in fact is integrated on the bytecode compiler as a
transparent step. I think you should do the same... KISS, you know ;-)

**Comment by lite20** [comment]
@piranna yeah I merged the preprocessor and the interpreter. It should be clean to take for a walk soon.

**Comment by piranna** [comment]
> @piranna yeah I merged the preprocessor and the interpreter. It should be clean to take for a walk soon.

Cool :-)

**Comment by darajava** [comment]
Don't swear it's unsightly
