### ISSUE TITLE
Face-lift the node-os.com website?

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#260]
Hi! We have a lot of front-end developers lurking around NodeOS and as nice as the website is, it could certainly be more polished and more responsive.

I'm suggesting we give the website a nice face-lift and polish it off as we welcome people to our shiny 1.0.0-RC2 release! If needed, I'd love to lead the creation of the new page, and involve all our talented front-end designers that I know sit around here lurking waiting for the renderer noGUI to be ready (on which @coretool has been making some [excellent progress!](https://github.com/Coretool/noGUI/issues/12) Kudos to you man!)

Interested to hear what you guys have to say!

**Comment by piranna** [comment]
I was going to assign it to you, but I've seen you have done it already :-P

**Comment by lite20** [comment]
Yay! Okay, is the website hosted on github pages?

**Comment by piranna** [comment]
> Yay! Okay, is the website hosted on github pages?

[Yep](https://github.com/NodeOS/nodeos.github.io) :-)

**Comment by lite20** [comment]
Okie dokie! I'll get to work then! Time to awake those slumbering front-end dev's

**Comment by lite20** [comment]
@piranna can I would tag it as a blog post but I'd like people to see the RC2 post, so we can tag the website thread tomorrow?

**Comment by piranna** [comment]
> @piranna can I would tag it as a blog post but I'd like people to see the RC2 post, so we can tag the website thread tomorrow?

Yes, let's wait some days.
