### ISSUE TITLE
Build using Clang

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#267]
In the now closed issue https://github.com/NodeOS/NodeOS/issues/165 @piranna said:

> Don't know, NodeOS cross-toolchain is based on GCC, but I would like to see it working with Clang instead :-)

Let's discuss the advantages of using Clang over GCC, and the work involved in swapping GCC out. Is it worth the switch?

**Comment by luii** [comment]
We should use a Compiler Flag for swapping out gcc with clang

**Comment by lite20** [comment]
@luii thats an awesome idea! That was users can select whichever they would like to work with

**Comment by piranna** [comment]
This discussion should be done on the `nodeos-cross-toolchain` project. Besides that, adding a flag to select what one to generate is fine for me, main concern is the support of clang to compile both on Linux kernel and Node.js (and Node.js compiled modules).

**Comment by lite20** [comment]
Ah okay. Moving thread.
