### ISSUE TITLE
Grub2 Disk Image

### ISSUE THREAD

**Issue by SpaceboyRoss01** [NodeOS/NodeOS#275]
Hey, I've been working on an os using NodeOS and I want to make a disk image. So far, I am having troubles loading in the usersfs file. Can anyone help me?

**Comment by piranna** [comment]
bin/installUsb

**Comment by SpaceboyRoss01** [comment]
I am using a prebuilt image.

**Comment by piranna** [comment]
Iso images should be able to be burn directly.

**Comment by SpaceboyRoss01** [comment]
I'm using the qemu prebuilt image.

**Comment by piranna** [comment]
What problems are you having?

**Comment by SpaceboyRoss01** [comment]
I can't find the usersfs file.

**Comment by luii** [comment]
Is the usersfs file not present or does it print just a message that it cant find the usersfs

**Comment by SpaceboyRoss01** [comment]
It can't find it, but the file exists on the disk image.

**Comment by lite20** [comment]
If it asks you to enter a path, used /dev/sdb2

**Comment by piranna** [comment]
We need to fid some way to make nodeos-mount-filesystems to detect them by
partuuid...

**Comment by lite20** [comment]
> We need to fid some way to make nodeos-mount-filesystems to detect them by
partuuid...

Create a new thread?

**Comment by piranna** [comment]
>> We need to fid some way to make nodeos-mount-filesystems to detect them
by
>> partuuid...
>
> Create a new thread?

For example... I have been searching a bit and udev makes it plainly simple
because adds some symlinks on /dev from the partuuid to the actual device,
but udev is too complex for the scheme we want for NodeOS. On /proc didn't
found anything useful, just only /proc/partitions but don't have any UUID
info, don't know if there would be some more luck on /sys... :-/

**Comment by piranna** [comment]
RC3 now is able to find automatically the partitions based on UUID, clossing.
