### ISSUE TITLE
List all dependencies

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#283]
List on the wiki or the [docs](https://github.com/NodeOS/docs) repo all the dependencies tree of NodeOS and its layers as a tree, and collect them all the badges. This would allow in a single glance to see the global status of the project.

**Comment by Coretool** [comment]
To which depth do you want the graph ?

**Comment by piranna** [comment]
> To which depth do you want the graph ?

All of them, the same way [coverdeeps](https://github.com/piranna/coverdeeps) works. Maybe just only remove duplicates. In fact, an easy way to fetch the dependencies tree would be to use `coverdeeps`... :-) Problem is that it doesn't support git repos yet, only modules published on npm :-(

**Comment by Coretool** [comment]
Are 'git-only' repositories the repositories which are referenced like this one :

```json
  "devDependencies": {
    "prebuild": "piranna/prebuild#prerelease", <- this ?
    "qemu": "NodeOS/qemu",
    "suppose": "^0.6.1"
  },
```
If so, I think I can fix that for you

**Comment by piranna** [comment]
> Are 'git-only' repositories the repositories which are referenced like this one :
> 
>   "devDependencies": {
>     "prebuild": "piranna/prebuild#prerelease", <- this ?
>     "qemu": "NodeOS/qemu",
>     "suppose": "^0.6.1"
>   },

Yes, they are. I think it would be easy to fix, both by doing the check on `coverdeeps` or better (but more complicated) directly on `npm-remote-ls`.


> If so, I think I can fix that for you

Pull-requests are welcome :-)

**Comment by piranna** [comment]
I'm thinking that on a first iteration would be enough just to list only the dependencies of the project, and later check all of them whem moving to achieve a 100% test coverage on all the dependencies (using coverdeeps).

**Comment by lite20** [comment]
Once we have the list, this will be an easy insert into the docs that I could do for you.

**Comment by piranna** [comment]
Ok, that's cool :-D Should we left the wiki for this kind of things and use
docs repo for more formal documentation?

**Comment by piranna** [comment]
I have done the list at https://github.com/NodeOS/NodeOS/wiki/NodeOS-project-dependencies-tree, so we can now start working on it. Clossing.

**Comment by lite20** [comment]
excellent, thank you!

**Comment by piranna** [comment]
You are welcome :-)
