### ISSUE TITLE
Split `nodeos-mount-filesystems`

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#285]
Create a basic `nodeos-boot` module to separate system initialization from filesystems mounting.

**Comment by luii** [comment]
You can assign this issue to me

**Comment by piranna** [comment]
This is a bit delicate, I wanted to move the users isolation mechanism to
Jocker. How do you plan to split it?

**Comment by piranna** [comment]
Partial work is currently done in master.

**Comment by piranna** [comment]
I have just finished this on master using modules [nodeos-boot-singleUser](https://github.com/piranna/nodeos-boot-singleUser), [nodeos-boot-singleUserMount](https://github.com/piranna/nodeos-boot-singleUserMount) and [nodeos-boot-multiUser](https://github.com/piranna/nodeos-boot-multiUser), all of them executing user code inside an un-priviledged environment by using [jocker](https://github.com/piranna/jocker), and also converted the parsing of Linux kernel cmdline to an independent module at [linux-cmdline](https://github.com/piranna/linux-cmdline). This will allow to easily create single-process and single user systems by using [nos-init](https://github.com/sbuller/nos-init/) by @sbuller, although it would need some minor tune-up, so I'm clossing this.
