### ISSUE TITLE
sound/opengl and child_process ?

### ISSUE THREAD

**Issue by stevenvachon** [NodeOS/NodeOS#29]
Since there is no bash as the primary runtime, I'm curious if there is still bash access; specifically for Node's `child_process.spawn()`.

Also, does NodeOS currently include sound and OpenGL libraries?

**Comment by lite20** [comment]
I'm curious. What happens when you call child process.spawn? Is bash secretly there hidden behind the scenes?

**Comment by piranna** [comment]
> I'm curious. What happens when you call child process.spawn? Is bash secretly there hidden behind the scenes?

No, it doesn't, it exec directly the binary provided as the first argument.

**Comment by lite20** [comment]
Okay this is what I thought. In that case this function should work perfectly on NodeOS. In this case no there is no bash access, and I may close the thread :P
