### ISSUE TITLE
Update `download-manager` to use upstream `download`

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#290]
[download](https://github.com/kevva/download) 4.x now is based on streams, so it will use a lot less memory by doing decompression on the fly

**Comment by piranna** [comment]
`download` now is based on streams but it's still storing the full file in memory, so it's useless to us as is it. We'll need to create our own download mechanism, luckily now the code of `download` [is fairly simple](https://github.com/kevva/download/blob/master/index.js) and we can use it as basis :-)

**Comment by Coretool** [comment]
I can take that since my logo PR depends on the download manager anyway ...

**Comment by piranna** [comment]
I'm having a review on it, 'download' use streams but it's still storing it
on memory so it's useless. I had a previous atempt of doing the downloads
directly but didn't fully work, I'll upload the changes so you can be able
to review them.

**Comment by piranna** [comment]
@Coretool, I have just pushed my updated code without `download` module and also added some test coverage. I'll try to add later an integration test copied from `nodeos-cross-toolchain` that's the most complex of the usage cases, so let's hope we can find why it was not working...

**Comment by piranna** [comment]
I finally managed to make it work! :-D [It was a bug on `got`](https://github.com/sindresorhus/got/issues/223). I need to test it a little more but so far it's fast and don't consume RAM, that's just what I wanted :-D If you want to take a look I've uploaded the code to the `download-manager` repo :-)

**Comment by piranna** [comment]
New version of `download-manager` is being used on all NodeOS packages. clossing.
