### ISSUE TITLE
distro?

### ISSUE THREAD

**Issue by stevenvachon** [NodeOS/NodeOS#30]
I think it'd be great if there were an *.iso distribution like other Linux variants. It could just be all the lightest, most basic packages necessary to boot up into a node process. This is actually what I'd thought Node OS was, then I realized that it builds on top of an existing Ubuntu installation.

**Comment by piranna** [comment]
I've think about this and more than a distro (that NodeOS is already a Linux distro...) what we need is a Live disk image, so it can be burned to a CD or USB pendrive and boot from there. For this we'll need before to make root partition to be really read-only, that's currently being in progress.

**Comment by piranna** [comment]
After the changes to make NodeOS [rootless](https://github.com/NodeOS/NodeOS/issues/118), the ISO images are working on QEmu, now it keeps to test them in real hardware and publish somewhere :-) Any suggestion? Any volunteer? :-P

To build it, use ```PLATFORM=pc_image npm install```.

**Comment by piranna** [comment]
Now we have an autogenerated CD-live :-)
