### ISSUE TITLE
Failed at the nodeos-mount@0.2.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by ganxunzou** [NodeOS/NodeOS#303]
npm WARN nodeos-rootfs@1.0.0-RC2.0 requires a peer of nodeos-barebones@1.0.0-RC2.2 but none was installed.
npm WARN nodeos-rootfs@1.0.0-RC2.0 requires a peer of nodeos-initramfs@1.0.0-RC2.3 but none was installed.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/GXZ/.nvm/versions/node/v6.2.1/bin/node" "/Users/GXZ/.nvm/versions/node/v6.2.1/bin/npm" "install" "nodeos-mount@0.2.0"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! nodeos-mount@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeos-mount@0.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodeos-mount package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodeos-mount
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodeos-mount
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/GXZ/WebstormProjects/MyProject/NodeOS/npm-debug.log

**Comment by piranna** [comment]
That error output don't help to figure out what's the problem, since it
just only shows that you are using OSX but it should be already fixed for
that or it's just a matter of accept a pull-request. Can you check that?

**Comment by piranna** [comment]
This will be fixed on next published version of `ǹodeos-mount`.

**Comment by piranna** [comment]
This should be already fixed in master, clossing.
