### ISSUE TITLE
Qemu: cannot initialize gcrypt

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#304]
I get this error after the compilation of NodeOS on Arch

``` bash
Successfully built Layer-3 image 'usersfs'

> NodeOS@1.0.0-RC2 postbuild /home/philipp/Dokumente/github/NodeOS
> scripts/postbuild

------------------------------------------
Success!
You just built a custom NodeOS image
------------------------------------------

- Interactively run your image with:
    npm start

λ philipp [Dokumente/github/NodeOS] at  master ✔ 
→ npm start                                                                                             [6aede62]

> NodeOS@1.0.0-RC2 start /home/philipp/Dokumente/github/NodeOS
> scripts/start

qemu-system-x86_64: cannot initialize crypto: Unable to initialize gcrypt
```

**Comment by piranna** [comment]
I'm thinking to remove the `gcrypt` support on QEmu, but this will also remove support for SDL output, so you would need to use a VNC viewer to connect to it and have a framebuffer terminal. Do you think this is acceptable, maybe adding some info about how to connect to it?

**Comment by luii** [comment]
Why do you want to remove gcrypt support, why dont we just enable gcrypt?
With SDL you mean the Simple DirectMedia Layer?
I dont deny the idea, but why should it use a remote client to connect to it (a headless machine)?

**Comment by piranna** [comment]
> Why do you want to remove gcrypt support, why dont we just enable gcrypt?

The simpler the better. I think they were giving problems to make a static build...


> With SDL you mean the Simple DirectMedia Layer?

Yes, that's it.


> I dont deny the idea, but why should it use a remote client to connect to it (a headless machine)?

Because at this moment we don't have a real GUI beside some experiments with FBDev and CJKTTY, just a terminal one, so we can have on Linux a headless QEmu instance and serialize the output to the current console, and when we want to experiment with a GUI start by hand a VNC viewer or automatically dispatch one on a web browser using noVNC :-)

**Comment by luii** [comment]
After i reinstall my System because of a Kernel Panic (that i couldnt resolve) i build NodeOS and install Qemu on my System and now the error from the first post has vanished!
I dont know if it was a old version of qemu or a invalid version of gcrypt but now it works like charm.
I think we can close this Issue.

**Comment by piranna** [comment]
Probably invalid version of gcrypt, that's why I'm trying to do static
builds. The more I think about it, the more I believe I should remove SDL
support on QEmu builds and use and independent VNC viewer for graphic
usages... :-/

**Comment by luii** [comment]
Already resolved
