### ISSUE TITLE
Maintain npkg.org

### ISSUE THREAD

**Issue by groundwater** [NodeOS/NodeOS#31]
I put up a few packages on http://npgk.org for keeping track of useful node-os modules on npm.

If anyone would like to help maintain that site, please let me know.

**Comment by rajzshkr** [comment]
@groundwater I am interested in contributing to this project.

**Comment by piranna** [comment]
Hi Raja, pkease to meet you. I'm the current project lead developer and maintainer. What are you interested in colllaborate?

**Comment by lite20** [comment]
npkg depricated. Closing
