### ISSUE TITLE
Node.js 7.0.0

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#313]
Node.js has been recently updated but it's failing to build, se need to review that.

**Comment by G07cha** [comment]
[List of changes](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md) in v7 might come in handy.

**Comment by luii** [comment]
@piranna Why doesnt NodeOS compile with Node 7.x.x?

**Comment by piranna** [comment]
it has some issues with cross-compilation due to new version of v8, I'm
waiting to them get fixed

**Comment by luii** [comment]
Is there any progress? Maybe they're fixed with the newest version (9.2.0 and earlier)?

**Comment by piranna** [comment]
Yes, this is already fixed and latests versions are being used, clossing.

**Comment by luii** [comment]
@piranna Nice then we can finally use the node-ife module. Magnificent!

**Comment by piranna** [comment]
> @piranna Nice then we can finally use the node-ife module. Magnificent!

That seems nice :-)
