### ISSUE TITLE
Cannot find coreutils.js

### ISSUE THREAD

**Issue by OMantere** [NodeOS/NodeOS#314]
Getting this when the REPL gets started. Cant find that anywhere either, nor can i find the piranna/Coreutils.js module in the package.json of any module. Where should coreutils.js be coming from? Would expect this to be a dependency in nsh but this is not the case.

~~~~
module.js:471
    throw err;
    ^

Error: Cannot find module 'coreutils.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/lib/node_modules/bin-nsh/lib/builtins.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
~~~~

**Comment by piranna** [comment]
That was a fail on my side, I changed nsh to use Coreutils.js and did it locally but forgot to upload the changes, specially because I'm thinking to refactor it (again) to use bash-parse instead of shell-parser-js module, but also because lately I lack of time and I've been refactoring the build process to try to do it more modular and easier to automate. I would accept some pull-requests and help to fix that issues.

**Comment by OMantere** [comment]
[https://github.com/piranna/nsh/pull/1] should fix this.

**Comment by piranna** [comment]
Can you check it by installing nsh in a vanilla Linux? I'm not sure if there are some missing points on coreutils.js itself...

**Comment by luii** [comment]
I get the same on Arch Linux after building and installing additional dependencies i get after i login the `coreutils.js` error

**Comment by piranna** [comment]
I'll try to retake that when I finish the refactor on the build system (spoiler: yesterday I got it working :-) ). Until that, you can be able to try to fix nsh and make it work on your regular systems.

**Comment by OMantere** [comment]
> Can you check it by installing nsh in a vanilla Linux? I'm not sure if there are some missing points on coreutils.js itself...

Nsh seems to be working fine in vanilla linux. I mean it starts up without errors.

**Comment by piranna** [comment]
Does it works normally?

**Comment by OMantere** [comment]
Yes, at least the basic commands.

**Comment by piranna** [comment]
Merged, please check if it works now.

**Comment by luii** [comment]
Works perfectly!

**Comment by piranna** [comment]
So is this fixed? Can we close it?

**Comment by luii** [comment]
Yes, it works on Arch Linux with a clean build

**Comment by piranna** [comment]
Cool then :-) Please notify any other problem you see with it.
