### ISSUE TITLE
Qemu: Image format for usersfs

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#315]
I know this is just a warning but, i think it's better to address this bug/warning because letting the qemu executable guess which format the usersfs has could lead to write operations on block 0 in the usersfs.

``` bash
WARNING: Image format was not specified for 'out/x86_64/pc_qemu/usersfs' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
```

If i have a solution, then i make a PR

**Comment by piranna** [comment]
Just by setting the raw gormat would be enough :-)

**Comment by luii** [comment]
Ok i already found the solution:
```js
args.push('-drive', `file=${join(outDir, 'usersfs')},format=raw,index=0`)
```
instead of
```js
args.push('-hda', join(outDir, 'usersfs'))
```

**Comment by piranna** [comment]
Yes please, create a pull-request for that, and if possible do the same on the 'start' and 'test' scripts of all the layer modules that need it.

**Comment by piranna** [comment]
Any update on this? The warning doesn't hurt, but it would be nice to don't show it.

**Comment by luii** [comment]
Totally forgot do this one
