### ISSUE TITLE
Can I build this OS using a ubuntu docker image?

### ISSUE THREAD

**Issue by navarroaxel** [NodeOS/NodeOS#320]
1. I have start docker using: docker run -it ubuntu bash
2. I have follow the guides (git clone, apt-get install [everything], npm install) and everything is OK, but when I run npm start I'm getting the following error:
````SHELL
root@f393130772cf:/NodeOS/scripts# npm start

> NodeOS@1.0.0-RC2 start /NodeOS
> scripts/start

fs.js:1014
  return binding.readlink(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, readlink 'out/latest'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:1014:18)
    at Object.<anonymous> (/NodeOS/scripts/start:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

````

3. The only issue I found before was this:
````SHELL
root@f393130772cf:/NodeOS/scripts# apt-get install -y libuuid:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libuuid:i386
````

**Comment by piranna** [comment]
You need to exec `npm run build` to generate it, in the future maybe we add prebuild images for each one of the layers, we are working on this path.

**Comment by navarroaxel** [comment]
I don't know why the build script is throwing this error to me:
````SHELL
scripts/build: line 14: cd: node_modules/nodeos-rootfs: No such file or directory
````

**Comment by piranna** [comment]
This is strange... Anyway I'm doing a full refactor fixing a lot of things and one of them is the deprecation of `nodeos-rootfs`, some of the changes are currently published and hope to finish them in the next days.

**Comment by navarroaxel** [comment]
1. You have renamed this repo: https://github.com/NodeOS/nodeos-rootfs to bootfs (makes redirect). That's why I have no node_modules/nodeos-rootfs folder.
2. The bootfs does not have a ``script.build: "scripts/build"`` defined in the package.json
3. The script/build does not set the -F y -O arguments, so the bootfs fails to build.
4. When I call the bootfs with a -F argument (iso or img) I get the following error: ``cp: missing destination file operand after '/NodeOS/node_modules/nodeos-bootfs/build/nocona/efiboot/kernel.img'``

**Comment by piranna** [comment]
As I told you, we are doing a full refactor and things are a bit unstable at this moment. One of the reasons of the refactor is just to have a better environment so this kind of things could not happen again in the future after we release the final 1.0.0 version.

**Comment by piranna** [comment]
Any update with this? The refactor was finished some weeks ago so now it should be straighforward to download the prebuild images of the layers...

**Comment by navarroaxel** [comment]
debian/ubuntu's apt-get says unable to locate package libuuid. What I need to add?

**Comment by luii** [comment]
Isnt `libuuid` part of `util-linux`? Maybe downloading this would solve your problem(?) I dont know for sure because im using Arch Linux
