### ISSUE TITLE
Cannot find module /bin/exclfs

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#326]
Got this error after trying to run the generated docker image.

```bash
λ luii [Dokumente/git/NodeOS] at master ✔ 
→ npm run docker

> NodeOS@1.0.0-RC3 docker /home/luii/Dokumente/git/NodeOS
> scripts/docker

mount procfs: Resource busy
module.js:471
    throw err;
    ^

Error: Cannot find module '/bin/exclfs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/lib/node_modules/usrbinenv/server.js:97:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by piranna** [comment]
What steps has you followed?

**Comment by luii** [comment]
1. `npm i`
2. `PLATFORM=docker run build`
3. `npm run dockerBuild`
4. `npm run docker`

**Comment by luii** [comment]
@piranna just now i checked the prebuilds of docker and they got the same error
because im updating the wiki

**Comment by luii** [comment]
@piranna i think i found the missing piece
i've added a symlink for exclfs to point into the `/bin/exclfs` directory

```bash
  # Install FUSE & ExclFS

  SRC_FUSE=$SRC_FUSE/out/$CPU

  eval "$NPMi" -g piranna/exclfs                  \
      --fuse__include_dirs=$SRC_FUSE/include/fuse \
      --fuse__library_dirs=$SRC_FUSE/lib          \
      --fuse__libraries=-lfuse                    || err 20

  cp $SRC_FUSE/lib/libfuse.so* $STEP_DIR/lib || err 21
  ln -fs ../.bin/exclfs         $STEP_DIR/bin/exclf <--- here
```

this, somehow seems to work - docker boots up and the init.js script gets called

```bash
$ npm run docker

> NodeOS@1.0.0-RC3 docker /home/luii/Dokumente/git/NodeOS
> scripts/docker

mount procfs: Resource busy
Hello! I'm a user init script :-)
...→ npm run docker                                                                          [1e4a7da]

> NodeOS@1.0.0-RC3 docker /home/luii/Dokumente/git/NodeOS
> scripts/docker

mount procfs: Resource busy
Hello! I'm a user init script :-)

```

but the only downside is, that getty dont gets called(?)
because i cant login

**Comment by piranna** [comment]
Yes, I need to review and upload all my code... `bin-getty` can't be able to get access to the console don't know why, that's why I changed it and exec directly `logon` on Docker instead. Hackish, but does the job, only that I'm not sure if the commands are being executed as `root` that way... :-/

**Comment by piranna** [comment]
This should be fixed now in master, I check it and the fault was due to the missing changes I did not uploaded. Could you be able to check it?

I think we need to find a solution for automatically publishing of the layers to prevent this... Hope we can release 1.0 soon so we can use semver after that, point is that I need to find time to try to fix `nsh`, the thing with the stdio file descriptors seems to be a difficult one... :-/

**Comment by luii** [comment]
Yeah ill check if its working now!

**Comment by luii** [comment]
Yes it works so we can close this issue!

**Comment by piranna** [comment]
> Yes it works so we can close this issue!

Awesome! Then we have now official support for Docker again :-D We should update de readme file then... ;-)

**Comment by luii** [comment]
Yes, should i do it?

**Comment by piranna** [comment]
Please and thank you :-) I was thinking we could add a list or a table with the platforms were NodeOS can currently be build and were can be executed, how do you see it?

**Comment by luii** [comment]
that is a really good idea, should i add this to the readme and the wiki?

**Comment by piranna** [comment]
I was thinking on the readme, about the wiki we should think about what to do with it now that we have the `docs` repo...

**Comment by luii** [comment]
@piranna is it ok to update the readme in general? Adding the logo at the top and restructuring it?
I would like to use [this](https://github.com/NodeOS/media/blob/master/NodeOS.png) logo because it looks way better than the blue svg and it feels more natural

**Comment by piranna** [comment]
> @piranna is it ok to update the readme in general? Adding the logo at the top and restructuring it?

It's ok, but do it in a pull-request so we can discuss it.


> I would like to use this logo because it looks way better than the blue svg and it feels more natural

What do you mean? Both images are the same, in fact the PNG is rasterized from the SVG one...

**Comment by luii** [comment]
> What do you mean? Both images are the same, in fact the PNG is rasterized from the SVG one...

Dont the svg has a dark blue color on your pc?

**Comment by piranna** [comment]
No, it doesn't... It's #0000AA in both cases, and the central diamond is
#00AAAA.

**Comment by luii** [comment]
![bildschirmfoto vom 2017-02-20 17-21-47](https://cloud.githubusercontent.com/assets/8077014/23133371/1cc757b2-f791-11e6-8db7-659b0fcd9754.png)

they arent the same the central diamond ist in fact the right color but not the other parts

**Comment by piranna** [comment]
You are right, and in fact the dates show the png is older. Probably I
added it for historical reasons, can you check if it has an ugly line at
the bottom? The new canonical one is SVG, with terminal compatible colors.

**Comment by beshur** [comment]
Have this error when trying to `sh run.sh` in the release
/v1.0.0-RC3/x86_64-docker.zip

In /v1.0.0-RC3/i386-docker.zip

```
sha256:1040d312b2337e3c13df7f2f0fcc1d99be7825db01a835ed1d99a96542785b6b
Sending build context to Docker daemon  45.04MB
Step 1/7 : FROM nodeos/barebones
 ---> 1040d312b233
Step 2/7 : MAINTAINER Jesús Leganés Combarro 'piranna' <piranna@gmail.com>
 ---> Running in 89ba4d2d25d6
Removing intermediate container 89ba4d2d25d6
 ---> 942a3ab57d3f
Step 3/7 : ADD initramfs.tar.gz /
 ---> 40c7b2fa050b
Step 4/7 : VOLUME /tmp
 ---> Running in cb535f5ef73f
Removing intermediate container cb535f5ef73f
 ---> 732058190875
Step 5/7 : ADD usersfs.tar.gz /tmp
 ---> 72aba1ed73fa
Step 6/7 : ENV root container
 ---> Running in 9f871b226d0b
Removing intermediate container 9f871b226d0b
 ---> ae22418e2eff
Step 7/7 : ENTRYPOINT ["/init"]
 ---> Running in ed3921b5b9b2
Removing intermediate container ed3921b5b9b2
 ---> 85f30b535eeb
Successfully built 85f30b535eeb
Successfully tagged nodeos/initramfs:latest
mount procfs: Resource busy
execvp: No such file or directory
/dev/pts: Resource busy
/dev: Resource busy
termination: Operation not permitted
```

OS X, 10.13.3.

**Comment by piranna** [comment]
Don't have OSX to check it, only official platform is Ubuntu. Pull-requests are welcome.

**Comment by beshur** [comment]
I see, but probably not capable of porting/making it compatible with OS X.

**Comment by LoganDark** [comment]
@luii please remove your notices from the wiki pages. They're no longer accurate, and (quite frankly) look out of place due to the bad grammar.

**Comment by luii** [comment]
thanks, done.

**Comment by LoganDark** [comment]
Thanks!
