### ISSUE TITLE
Qemu: -redir deprecation warning

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#328]
QEmu's `-redir` option is deprecated, we should use `-net` or `-netdev` instead

```bash
$qemu-system-x86_64: -redir tcp:50080::80: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
$qemu-system-x86_64: -redir tcp:50443::443: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
```

**Comment by piranna** [comment]
Do you know what's the exact alternative? If so, I would merge a pull-request for that.

**Comment by piranna** [comment]
Do you know what's the exact alternative? If so, I would merge a pull-request for that.

**Comment by luii** [comment]
Well the net commands are obsolete but they're working

**Comment by piranna** [comment]
It should be easy to do, just only didn't have time to work on it.
