### ISSUE TITLE
Add demo user credentials to documentation 

### ISSUE THREAD

**Issue by djesmond** [NodeOS/NodeOS#333]
Hi
I just started looking into this project, so i fired up a prebuilt binary from the latest release.
However I couldn't find the user credentials for the demo filesystem anywhere.
I guessed my way to the nodeos one.
Have I missed something or is it missing from the wiki?

I could add it, but Im new to OSS (and GitHub Wiki) so I haven't.

**Comment by luii** [comment]
The Username and Password for the demo FS should be both `nodeos` like stated in [here](https://github.com/NodeOS/NodeOS/wiki/Building-From-Source#step-5-run-your-fresh-nodeos-build)

**Comment by djesmond** [comment]
Alright. I must admit that i did not search in the building from source section. 
I don't know if it would be moving/adding it so that it was easier to find?

**Comment by luii** [comment]
Yeah it would be easier to find if we move it and we'll do that because the updated wiki goes into the docs repository

**Comment by djesmond** [comment]
Sounds great. Simply wanted to point it out to make it easier for starters. I'll close this one

**Comment by piranna** [comment]
I think that info should be on the readme of the [nodeos-usersfs](https://github.com/NodeOS/nodeos-usersfs) repo.

**Comment by djesmond** [comment]
I would also be nice if it was included in the readme for the releases, but it's just a recommendation. It isn't a major thing in anyway. And as I mentioned, I managed to find the information needed. It just wasn't completely clear where it was. (As a newcomer)

**Comment by piranna** [comment]
> It would also be nice if it was included in the readme for the releases, but it's just a recommendation

Good idea! :-D Info on the readme of the releases could definitely be improved :-) Also I'm thinking it would be good to add some description text on the releases about what platform is intended each one of the tarfiles. Would you like to write both? :-)

**Comment by djesmond** [comment]
Hi. Sorry for the late reply. I will take a look at it this weekend and see what i can do :)

**Comment by djesmond** [comment]
I've added some additional information in the readme's for the builds. I was wondering if you had any suggestions to things you wanted to be added?
Also, could you expand on the tarfiles description idea?

**Comment by piranna** [comment]
> I've added some additional information in the readme's for the builds. I was wondering if you had any suggestions to things you wanted to be added?

Mostly all the needed info for a newcomer that just download the tarfile without reading anything else could be able to exec NodeOS: system dependencies, how to run it, how to burn on an USB (when aplicable)... This kind of things.


> Also, could you expand on the tarfiles description idea?

Releases are generated automatically, and now we have a lof of files for diferent targets and platforms. A minimal text explaining what't the correct one you need to download would be useful...
