### ISSUE TITLE
Update `node-dup2`

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#334]
`node-dup2` code is fairly old and [needs to be updated](https://github.com/solidco2/node-dup2/issues/1), if someone accepts the challenge please tell (it's a small module, so could be useful is someone want to learn to build compiled modules), if not I'll try to update it myself. Seems it could be the missing thing to make `nsh` to work, similarly as [how I did in `P9sh`](https://github.com/piranna/P9sh/blob/5d5380eefb02ace2858355fab265deb986163c08/src/pipeline.c#L81-L97) :-)

**Comment by piranna** [comment]
Another option would be to add it to our own module [node-src-unistd](https://github.com/NodeOS/node-src-unistd)... :-P

**Comment by luii** [comment]
Is it ok if I update it to Node Addon Api (N-API). If yes assign me the Task and i'll update it as soon as i'm home.

**Comment by piranna** [comment]
Assigned ;-) Now that `nsh` correctly works this is not needed anymore, but it would be good to have this module updated, and probably would be good for learning tasks :-)

**Comment by piranna** [comment]
Regarding `node-src-unistd`, yes, this is being actively used ;-)

**Comment by luii** [comment]
Module is updated with everything and it works flawlessly!
The only thing to do is writing tests.
If you want i can port `node-src-unistd` to napi
