### ISSUE TITLE
NodeOS Shutdown Command

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#338]
I tried a bunch of common keywords and nothing worked which led me to wonder:

Does NodeOS even have a shutdown command? In the passed I've simply closed the QEMU window. Is there a way for NodeOS to request a shutdown internally?

**Comment by piranna** [comment]
Not yet :-) NodeOS follow the old philosophy that "UNIX systems are not
designed to be halted", so apps must ve designed having in mind that
anybody could plug the cord at any time. Also, by don't having an
administrator user, this could not have been done in a safe way. On the
other hand, nodeos-init is listening for the traditional Ctrl-Alt-Del combo
to do a clean shutdown, and the same when the last process exits.

My bachelor thesis tutor asked me about adding a command for that... It
would be done, by adding a service to the root user to listen for request
otover network with some control heuristics like only accepting from
localhost and some specific users, and shutdown the system by sending a
SIGTERM to pid 1, or send the SIGTERM from any user (this needs to be
tested), but priority on this is too low so it's open for everybody todo it
:-)

**Comment by lite20** [comment]
Sounds good! Thank you!

**Comment by piranna** [comment]
Are you willing to work on that shutdown command/system?

**Comment by lite20** [comment]
@piranna would I just be writing a node module to make a call to the kernel to shutdown?

**Comment by piranna** [comment]
Well, I would try first if you can send SIGTERM to pid 1 as a regular user,
and if not, create a web service that listen on localhost and check against
a list of valid users and send the SIGTERM instead, so we can exec it as
root, and a cli command to inboke that web service.
