### ISSUE TITLE
Using hyper and hterm as the terminal for nodeOS

### ISSUE THREAD

**Issue by regisbsb** [NodeOS/NodeOS#340]
Have you guys thought about it?
https://github.com/zeit/hyper
https://github.com/zeit/hyper/blob/master/lib/hterm.js
https://chromium.googlesource.com/apps/libapps/+/master/hterm

**Comment by regisbsb** [comment]
https://github.com/macton/hterm

**Comment by piranna** [comment]
These are about client terminal applications, nothing to do with NodeOS.
