### ISSUE TITLE
Could not access KVM kernel module

### ISSUE THREAD

**Issue by wallgeek** [NodeOS/NodeOS#342]
Getting error "Could not access KVM kernel module. NodeOS will be slower without it" in "npm start" command. 

My system does not support KVM. Is there any way to proceed further without it?

**Comment by piranna** [comment]
You could be able to pass the --disable-kvm flag to QEmu, or also send a
pull-request with a better autodetection mechanism.

**Comment by wallgeek** [comment]
I exactly had no idea how to pass --disable-kvm flag to qemu. So I tried `npm start --disable-kvm` but didn't work. I tried `npm run build --disable-kvm` but didn't work too. So I read your this link [https://github.com/NodeOS/NodeOS/blob/master/scripts/start#L34](url) and commented out the line but didn't work. 

So after scanning the script file I commented out "-enable-kvm" from args array and also commented out "args.shift()" from "if(kvm.test(contents) === false)" and now it is working fine.

**Comment by piranna** [comment]
I'm happy to know you were able to fix it :-)

Just curious, why are you using NodeOS for?

**Comment by wallgeek** [comment]
I have been working with Nodejs a lot these days and when I read about NodeOS, I got excited and was curious to know more about it. 

I wanted to try it out and learn more about its capabilities but couldn't find proper documentation. So whatever I am getting, I am trying to figure it out as much as I can and would love to contribute, if possible, in future.

**Comment by piranna** [comment]
> would love to contribute, if possible, in future

Of course it's possible :-D So far, if you find difficult to follow the documentation you could be able to send us the corrections and clarifications that you'll find, in fact documentation is an area where we need some big help here :-D Would you want to work on that? :-)

**Comment by wallgeek** [comment]
Sure, I would like to work on that. :)
