### ISSUE TITLE
NodeOS NPM Account

### ISSUE THREAD

**Issue by joshgarde** [NodeOS/NodeOS#343]
Can we have the NodeOS user on NPM converted over to a organization? NPM recently just made orgs free and packages don't have to be managed by personal accounts.

https://www.npmjs.com/~nodeos
https://www.npmjs.com/features
https://www.npmjs.com/docs/orgs/migrating-a-user-account.html

@groundwater @piranna

**Comment by joshgarde** [comment]
Just a side note - I do have the node-os organization name on npm if it's easier just to use that instead

**Comment by piranna** [comment]
The only reason why we were not using a npm organization was because they were paid!!! :-D Now we have it, thanks! ;-)
