### ISSUE TITLE
port 80

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#35]
Alice start a http server in port 80, Bob want to do same... What happens?

**Comment by piranna** [comment]
Reverse proxy should

- [ ] redirect to users servers based on request username or path
- [ ] register domains requested by that users to be redirected (vhost)
- [ ] maybe overwrite http module so redirection of ports can be transparent (.listen() method)

**Comment by piranna** [comment]
Reverse proxy could use http auth with credentials from ```logon```, and only accept https and secure websockets (wss) since it doesn't makes sense to request some credentials and later transfer the data in raw...

**Comment by lite20** [comment]
wasnt the reverse proxy created? Closing, but re-open if I'm in error

**Comment by lite20** [comment]
@piranna is that automated or are you just watching to see every time I close a thread? :P

**Comment by piranna** [comment]
Reverse proxy is working correctly and integrated, but it's only focused for HTTP and WebSockets. This issue is more related to discuss what to do with other incoming ports. One solution would be to don't accept them and only allow incomming petitions for HTTP and WebSockets since they can be easily identified, and maybe allow any other protocol that has an easy support for a reverse proxy in some way that don't involve NAT or similar techniques, but this would restrict us to only allow high-level protocols...

**Comment by lite20** [comment]
@piranna I suggest we leave the other ports as "fend for yourself" ports. We enable a reverse proxy for as many protocols as we can, but for those that we can't we leave the default functionality. Whoever gets there first, gets the port. As stated above:

>> Alice start a http server in port 80, Bob want to do same... What happens?

> bob can't?

If it isn't on a reverse proxy, bob can't. Everyone with a reverse proxy deals with this issue already so we can see it more as adding a bonus in creating the reverse proxy, than it is losing out not passing the other ports through a proxy.

**Comment by piranna** [comment]
Here I find three situations:

1. priviledged ports (< 1024), only root user (UID 0) can open them, reverse proxy should manage them someway if it makes sense (telnet, ssh...), but how? Just ignore them and suggest/force people to use other alternatives (mainly HTTP and WebSockets)?
2. regular ports (>= 1024), i find ok the first come first serve approach here
3. regular ports with easy support for reverse proxy, this ones could/should be managed as it's currently done with HTTP/WebSockets, but don't know of any other protocol that has this functionality

We should take in account the fact that I had in mind the reverse proxy to be able to register some servers for some particular domains that's currently not implemented (don't know if to use a UNIX socket or something similar so clients can send the register requests), maybe something similar would be done with the priviledged ports, but in this case it would more transparent if it would be automatically done by piggybacking the `net` buildin module... I think external `node_modules` have priority over the build-in ones, so we could add it in the `initramfs`, but I don't like to add too much things there... Or could it be just enought to request devs to explicitly use a custom version of it?

**Comment by lite20** [comment]
> priviledged ports (< 1024), only root user (UID 0) can open them, reverse proxy should manage them someway if it makes sense (telnet, ssh...), but how? Just ignore them and suggest/force people to use other alternatives (mainly HTTP and WebSockets)?

If you create a manager they could simply be ignored, yes.

>  I think external node_modules have priority over the build-in ones, so we could add it in the initramfs

We're officially exiting my realm of knowledge :P

>  Or could it be just enought to request devs to explicitly use a custom version of it?

What do you mean by this? How would this work?

**Comment by piranna** [comment]
>> priviledged ports (< 1024), only root user (UID 0) can open them,
reverse proxy should manage them someway if it makes sense (telnet,
ssh...), but how? Just ignore them and suggest/force people to use other
alternatives (mainly HTTP and WebSockets)?
>
> If you create a manager they could simply be ignored, yes.

Working on ;-)

>> I think external node_modules have priority over the build-in ones, so
we could add it in the initramfs
>
> We're officially exiting my realm of knowledge :P
>>
>> Or could it be just enought to request devs to explicitly use a custom
version of it?
>
> What do you mean by this? How would this work?

I have check the docs and build-ins have the highest priority, so only
solution is devs will need to explicitly require a module to use
priviledged ports :-(

**Comment by piranna** [comment]
I have upgraded `nodeos-reverse-proxy` to accept registration of domains for HTTP and WebSocket connections and to proxy registered ports. This needs on the client the usage of the module [nodeos-reverse-proxy-register](https://github.com/piranna/nodeos-reverse-proxy-register), that transparently piggy-back on top of the Node.js build-in `dgram` and `net` modules to register ports listening, and export a `register()` and `unregister()` functions to allow registration of domains. Communications with `nodeos-reverse-proxy` are done using `POST` requests to the urls `http://127.0.0.1/_register` and `http://127.0.0.1/_unregister` respectively, that later are filtered by `nodeos-reverse-proxy` to only allow requests from the local own machine. Clossing.
