### ISSUE TITLE
Dependencies script assumes Debian-based distro

### ISSUE THREAD

**Issue by sergiouve** [NodeOS/NodeOS#353]
Hi,

I just tried to boot up NodeOs on one of my Fedora machines. I couldn't run the
install-dependencies script since it assumes a Debian-based system, and relies on 
apt-get to install the required dependencies.

Is there a reason behind this? Or is it simply because all the NodeOs development
happens to be done in Debian-based systems/virtual boxes?

**Comment by piranna** [comment]
Well... not exactly Debian-based distros, but Ubuntu based ;-) There was some adaptations for OSX and Arch Linux, so there should not be too much problems in adapt it to RPM-based systems. As usual, pull-requests are welcome :-)

**Comment by sergiouve** [comment]
I'll make some tweaks to the script then.

Also, since we are in the subject, has nvm been considered for the installation/management of Node?

**Comment by piranna** [comment]
We use our own compilation of Node.js using musl library, you can get it with the `nodeos-nodejs` package.

**Comment by luii** [comment]
I've create a pull request for this (#383).
Im checking for the Release file in the `/etc` folder 
(e.g. `/etc/arch-release`) i've just copied the dependencies since arch needs all the dependencies that i've listed on the wiki and so i copied Thema to gentoo

**Comment by piranna** [comment]
This should be already fixed in master, clossing.
