### ISSUE TITLE
April Fools Day is over

### ISSUE THREAD

**Issue by SCKelemen** [NodeOS/NodeOS#361]
April fools day was several months ago. Isn't it about time to delete this joke?

**Comment by piranna** [comment]
This is not a joke.

**Comment by luii** [comment]
what is not a joke?

**Comment by piranna** [comment]
NodeOS is NOT a joke, it's a real thing.

**Comment by rsp** [comment]
@piranna Why would it be a joke?

**Comment by piranna** [comment]
> @piranna Why would it be a joke?

Don't know, ask @SCKelemen, that's the one that think this is and April's Fools Day joke... You know, haters gona hate...
