### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by gjsieben** [NodeOS/NodeOS#365]
Hello,

I booted up NodeOS, and logged in with "nodeos"/"nodeos" and ran:

`npm install c9`

However, it crashed with this error:
`npm ERR! nospc ENOSPC: no space left on device, write`
`npm ERR! nospc This is most likely not a problem with npm itself`
`npm ERR! nospc and is related to insufficient space on your system.`

I still have plenty of space left. Thoughts?

**Comment by piranna** [comment]
What image are you using? QEmu `usersfs` partition is a bit space constrained since it's only for demo and test purposses...

**Comment by gjsieben** [comment]
I followed the Build instructions on the Wiki.

**Comment by piranna** [comment]
> I followed the Build instructions on the Wiki.

Then yes, you have the default `usersfs` size constrains. If you are just playing with NodeOS, a quick workaround would be to flash it to a pendrive with `bin/install-usb` script, it will expand `usersfs` to the size of the USB thumb. If you are willing to contribute, you could add an argument to [nodeos-usersfs](https://github.com/NodeOS/nodeos-usersfs) to define an alternative size and give it as parameter of NodeOS build system too, so you can create a default partition with a bit more space. Also, it's on the roadmap to allow to define the path of already created custom layers, so in the long term it will be the best alternative.

**Comment by gjsieben** [comment]
Okay, thanks! I will try contributing (if I can).

**Comment by piranna** [comment]
You are welcome :-) I hope to add the support to define the custom usersfs
image in the next days... only that we'll need to have some tool to create
them, too :-/
