### ISSUE TITLE
Clarification regarding project

### ISSUE THREAD

**Issue by agauniyal** [NodeOS/NodeOS#369]
Could someone clarify what exactly is NodeOs? Going by the name I assumed it was another operating system being written and got excited till I encountered this line -
> NodeOS is a Node.js based operating system, built-off of the Linux kernel

So are you using Linux kernel temporarily(maybe as a bootloader) and patching your kernel binaries on the fly? But reading sources I couldn't find such code 🤔 . Or is it more like a distribution for eg Ubuntu, Gnome etc, rather than an OS? Ubuntu and other distributions do call them Operating systems because they use Linux kernel plus lots of additional goodies such as window manager, compositor, tons of useful and daily driver gui applications like Libreoffice, firefox etc. Is it something in b/w both of these? Is there some piece of code/program which could be called its direct alternative so that it would be easier to understand.

I'm genuinely curious about this and I hope someone will answer my query 😄

**Comment by piranna** [comment]
I think there are some (minors) confusions on the terms used on your post (Gnome is not a distribution, but a desktop environment, for example), but acording to them, yes, NodeOS can be considered a Linux distribution like Ubuntu or Fedora, only that almost all its user space libraries and programs are written in Node.js. The linux kernel is compiled as part of the `nodeos-barebones` module, and also it's capable to run on Docker. Does this answer your questions?

**Comment by agauniyal** [comment]
Hi @piranna, 
> Gnome is not a distribution, but a desktop environment, for example)

I wasn't talking about gnome desktop but the actual gnome distribution here - https://ubuntugnome.org/ but despite that, I agree that some of my terms could be ambiguous there 😅 .

> all its user space libraries and programs are written in Node.js

So from what I understand, NodeOS is another operating system where all programs are written in javascript instead of c-lang/cpp/gtk etc technologies(when compared to existing distributions), and is a direct alternative to Ubuntu/Fedora type operating systems?

**Comment by piranna** [comment]
> NodeOS is another operating system where all programs are written in javascript instead of c-lang/cpp/gtk etc technologies(when compared to existing distributions)

Yes, that's it.


> is a direct alternative to Ubuntu/Fedora type operating systems?

Well, it depends of your purposses, if you just want to run Node.js programs for example on a cloud Docker, then yes, it's a direct alternative :-)

**Comment by agauniyal** [comment]
Thanks, I find that a satisfactory answer to my query :)

**Comment by piranna** [comment]
You are welcome :-)
