### ISSUE TITLE
[GitClone] Can get help?

### ISSUE THREAD

**Issue by MartinPPG** [NodeOS/NodeOS#372]
Sorry, I dont know where I can type it, but I need help, I cant clone NodeOS Reposity, I getting error(Its attached as file). I am tried to google it, and I dont found solution, and when I tried to clone other reposities, that works well, without, I Dont know why, Can I get help? Thanks
![snimka obrazovky z 2017-09-14 19-00-47](https://user-images.githubusercontent.com/20891196/30443259-39a47078-997f-11e7-8da5-971a68f40229.png)

**Comment by piranna** [comment]
You are clonning using git protocol instead of http, this requires you add a SSH private key on your Github account, so Github can be able to identify your computer.

**Comment by MartinPPG** [comment]
How can I do that?

**Comment by piranna** [comment]
https://github.com/settings/keys

**Comment by bogdanbiv** [comment]
Please close this, it's not related to NodeOS itself, it has more to do with supporting people to use Github itself.
