### ISSUE TITLE
`npm run build` Fails

### ISSUE THREAD

**Issue by Miwrzezl** [NodeOS/NodeOS#378]
I'm running into an issue which prevents NodeOS from building via source.

```
$ npm run build

> NodeOS@1.0.0-RC3 build <path-redundant>/WolfCast
> scripts/build

scripts/build: line 2: $'\r': command not found
scripts/build: line 9: $'\r': command not found
: invalid option name0: set: pipefail
scripts/build: line 11: $'\r': command not found
scripts/build: line 12: $'\r': command not found
scripts/build: line 14: syntax error near unexpected token `$'in\r''
'cripts/build: line 14: `  case $opt in
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! NodeOS@1.0.0-RC3 build: `scripts/build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the NodeOS@1.0.0-RC3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This is a great concept, but it was poorly executed with little (or no) planning beforehand.

**Comment by piranna** [comment]
This is a problem of downloading the source code with git under Windows, it's not a problem of NodeOS. Oficial development environment is Ubuntu Linux, outside that you are in your own.

Regarding your last statement, if you have some idea about how the project could be improved, open and issue or better do a pull-request.
