### ISSUE TITLE
Boot directly to Linux Framebuffer

### ISSUE THREAD

**Issue by seanewest** [NodeOS/NodeOS#39]
I recently learned about the Linux Framebuffer ([wikipedia link](http://en.wikipedia.org/wiki/Linux_framebuffer)) which is a console interface that is built into the Linux Kernel and actually allows direct access to the framebuffer for images/videos/games etc. This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/3216121/3423396/ede3abb4-ff93-11e3-84d8-2e9cbdc0363e.png)

Maybe we could avoid all of the X window system, by simply booting to this and seeing what people make of it? In fact, there already is a GUI windowing system *built-in* to the kernel based on Framebuffer http://directory.fsf.org/wiki/FramebufferUI. I can imagine a GUI that has split panes like in tmux or vim, but with the ability to insert images and video or interactive elements.

I mostly am thinking about this to minimize how much we put between the linux kernel and the node.js runtime. If the kernel already has way of allowing us to do text+images+video+windows then maybe we could just start with that and allow anything on top of that to be strictly provided by npm?

**Comment by piranna** [comment]
I've been experimenting in the last days about Unicode support and increase number of rows and columns of the terminal, and seems the framebuffer came by free :-) @netlovers and me were experiencing some slugginesh in the last days seems related to it, but when using a bigger console so auto-enabled the framebuffer, seems it got the previous performance, so due to this two things now I'm not so reliant to have framebuffer support... :-) Node.js bindings, anyone :-P

**Comment by formula1** [comment]
I'm extremely excited about this.

**Comment by piranna** [comment]
What part, exactly?

**Comment by formula1** [comment]
Being able to render arbitrary pixel values to the framebuffer. It opens up so many opportunities

**Comment by piranna** [comment]
You can do it right now by writting directly on /dev/fbdev and seems it's
easy to do, but there's no currently Javascript wrapper to make things
easier. It would be cool if node-canvas could be able to use it as backend
or develop an API compatible module (like node-openvg-canvas does), but
seems framebuffer is slow compared to other alternatives and it would be a
huge work to implement all canvas primitives, but a simple wrapper with
some minimal primitives would be an easy task to have some simple graphics
on the terminal and could be a first step for something bigger :-)

**Comment by formula1** [comment]
Ah, I see. Its non-accellerated on ubuntu. Well, this might be an interesting project. After I'm done with the blog, I may toy around with this a bit.

**Comment by piranna** [comment]
Oh, cool! :-D Yeah, this can be a funny one :-) I would do first a wrapper
class that receive the path of the fbdev device and implement its
primitives, and later inherit it on another one to implement the high level
operations.

**Comment by piranna** [comment]
I've done a quick look and seems you can be able to simply open the ```/dev/fb0``` device and write the pixel data there using ```seek()```, but it's simpler to ```mmap()``` it so you can access to the framebuffer as a memory region painting directly the pixels, and using ```iocall()``` to request info to the kernel about the framebuffer. A wrapper class would be easy to craft and later implement [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) on top of it or adapt [node-canvas](https://github.com/Automattic/node-canvas) to use it as backend (mostly copy the data on each frame). Problem is that it would be only software rasterized :-( but could be a starting point... :-)

**Comment by piranna** [comment]
I've [open an issue on node-canvas](https://github.com/Automattic/node-canvas/issues/533) to request support for fbdev backend :-)

**Comment by piranna** [comment]
[I have been trying to create a statically linked version of node-canvas](https://github.com/Automattic/node-canvas/issues/551#issuecomment-114253760) and although it compiles correctly it fails with a missing symbol, but it seems to work correctly on Ubuntu. Anyone have any idea?

**Comment by formula1** [comment]
So, I barley work in c++ at all but heres what I am assuming
1) You can import/link to a shared library that is accessible from memory
2) You can import a static library if you have access to where it is on the filesystem
3) You can import a shared library however you must indicate where it is on the filesystem if it doesn't exist in memory yet

Heres what I understand
1) After compilation, node canvas is correctly linking to libjpeg-turbo
2) libjpeg-turbo seems to be expected to be preinstalled and available. Something that has caused [many other issues](https://github.com/Automattic/node-canvas/search?q=libjpeg-turbo&type=Issues&utf8=%E2%9C%93)
3) libjpeg8-dev seems to be prefered over libjpeg62 as per (this issue)[https://github.com/Automattic/node-canvas/issues/110#issuecomment-1771228]

How can we tell that libjpeg is accessible by libraries?

**Comment by piranna** [comment]
Sorry for the delay, exams.


> 2) libjpeg-turbo seems to be expected to be preinstalled and available. Something that has caused many other issues

There was a fork that allowed to create a statically linked version of node-canvas although it was one year old, abandoned and needed some fix-ups, but it's the one [I've used as basis](https://github.com/NodeOS/node-canvas). According to the ```ldd``` output the only libraries it makes reference are the C lib and the gcc runtime, both on Ubuntu with glibc and NodeOS with musl.


> 3) libjpeg8-dev seems to be prefered over libjpeg62 as per this issue

This is not a problem since I've told before, it's using the statically linked one :-) Just to be sure I renamed the dynamic library of libjpeg-turbo and the Ubuntu version still worked, so it's not using it at all. Also, both the .o files and the canvas.node one have references to the problematic jinit_arith_decode function so don't know what could be happening... :-/

I've just updated the version of the libraries of node-canvas and there's no success, so [I've written to the libjpeg-turbo mail list](http://sourceforge.net/p/libjpeg-turbo/mailman/message/34242078/) to see if they can help us, since I suspect it could be some incompatibility with musl. I start to think we should have musl installed on Ubuntu just to check this glibc compatibility things... Don't know if we should write in the musl mail list too...

**Comment by piranna** [comment]
It was really though, needing a lot of fixes and headbanging, probably unstable, will need more work and will last to get into main code, but...

![fbdev](https://cloud.githubusercontent.com/assets/532414/8397585/71869a7e-1dd1-11e5-8cd2-c48d9a1a1ac1.png)

It works!!! :-D I've ported [node-canvas](https://github.com/NodeOS/node-canvas) to NodeOS!!! :-D

**Comment by piranna** [comment]
![pantallazo-9](https://cloud.githubusercontent.com/assets/532414/8889486/bc3c03e0-32dc-11e5-80bf-75ad7a1ab389.png)

Now node-canvas works correctly inside NodeOS and QEmu, problem was related to default emulated Cirrus graphic card, that only support 24 bits color and Cairo 24 bits mode is really 32 bits ignoring alpha channel. By changing to the ```stdvga``` graphic card and using a 32 bits color mode it work flawlessly, so now we have FbDev and graphic support on NodeOS :-) Next step, get WebKit support :-P

**Comment by Drulac** [comment]
How can we do it ?
How can we use node-canvas to directly draw to the console ?
Do you have some code sample ?

**Comment by piranna** [comment]
> How can we use node-canvas to directly draw to the console ?

`node-canvas` now has support for several backends, the only missing part that they are somewhat exhitant to add is the support for static linking on my fork, with it it's possible to make it work.

**Comment by luii** [comment]
what do you mean by static linking, something like `*.lib`?

**Comment by piranna** [comment]
> what do you mean by static linking, something like *.lib?

I think `*-Lib` are OSX dinamic libraries, I'm talking about compile `node-canvas` as a standalone `*.node` file without external library dependencies.

**Comment by luii** [comment]
ahh ok like i did it with the nodegit lib, made it self unpacking like but i get this error when i try to install it:
```bash
> @nodeos/termios@0.0.0 install /home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/root/lib/node_modules/@nodeos/getty/node_modules/@nodeos/termios
> node-gyp rebuild

make: Verzeichnis „/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/root/lib/node_modules/@nodeos/getty/node_modules/@nodeos/termios/build“ wird betreten
  CXX(target) Release/obj.target/binding/src/termios.o
make: *** [binding.target.mk:95: Release/obj.target/binding/src/termios.o] Fehler 127
make: Verzeichnis „/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/root/lib/node_modules/@nodeos/getty/node_modules/@nodeos/termios/build“ wird verlassen
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/philipp/Dokumente/git/nodeos-usersfs/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.8-1-ARCH
gyp ERR! command "/home/philipp/.nvm/versions/node/v9.2.0/bin/node" "/home/philipp/Dokumente/git/nodeos-usersfs/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/root/lib/node_modules/@nodeos/getty/node_modules/@nodeos/termios
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/root/lib
├─┬ logon@0.1.4

....

  ├── is-docker@1.1.0
  └─┬ mkdirp@0.5.1
    └── minimist@0.0.8

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodeos/termios@0.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodeos/termios@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/philipp/.npm/_logs/2018-01-03T15_53_08_503Z-debug.log
Error building '/home/philipp/Dokumente/git/nodeos-usersfs/build/nocona/root'
npm ERR! code ELIFECYCLE
npm ERR! errno 12
npm ERR! nodeos-usersfs@1.0.0-RC3.3 build: `scripts/build`
npm ERR! Exit status 12
npm ERR!
npm ERR! Failed at the nodeos-usersfs@1.0.0-RC3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/philipp/.npm/_logs/2018-01-03T15_53_09_599Z-debug.log
npm WARN /home/philipp/Dokumente/git/nodeos-usersfs/node_modules/ansi-regex is not a child of /home/philipp/Dokumente/git/NodeOS
npm ERR! code ELIFECYCLE
npm ERR! errno 12
npm ERR! nodeos-usersfs@1.0.0-RC3.3 install: `prebuild-install -d https://github.com/NodeOS/nodeos-usersfs/releases/download/v{version}/{platform}-{arch}.tar.gz || (buildDependencies && npm run build)`
npm ERR! Exit status 12
npm ERR!
npm ERR! Failed at the nodeos-usersfs@1.0.0-RC3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/philipp/.npm/_logs/2018-01-03T15_53_10_706Z-debug.log
```

**Comment by bitterbit** [comment]
Has there been any progress on this? :grin:
