### ISSUE TITLE
Integrate node-red project

### ISSUE THREAD

**Issue by mdimai666** [NodeOS/NodeOS#391]
NODE-REDis very simple and convenient. it could be integrated into the OS.
[nodered.org](nodered.org)

**Comment by piranna** [comment]
I know of node-red project, really interesting one. How do you think it could be integrated? So far, I think it would mostly be application specific, how do you think it could be integrated globally at OS level and what advantages would it provide?

**Comment by LoganDark** [comment]
I feel like this should be more of a package than a required OS thing.
