### ISSUE TITLE
How to set the path to the shared libs in `/lib/` while cross compile

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#393]
@piranna I've created a package that create a shared `libcurl.so*` and i've placed the lib inside `/lib` through the initramfs package, so my question how can i link `nodeos-nodegit` against this libary and later place nodegit inside node. Because at the time `nodeos-nodegit` says that it cant find libcurl.so . But it's actually in the `lib/` folder.
Im trying to figure out how i can configure `libgit2` with this "path" for it to work.

**Comment by piranna** [comment]
Although it could be feasable to have per-user "global" shared libraries, I haven't tried that, sorry :-( It should be feasable, but so far only it's being used the `lib` folder created by the cross-compiler, that has the basic things. My idea about NodeOS was that the libraries like `libcurl` were linked statically to their dependent `*.node` file, making it standalone. Could you try to link `nodeos-nodegit` against the `*.a` files of `libcurl.a` and `libgit2.a`? :-)

**Comment by luii** [comment]
I can and will i just was curious if its possible to use These libs. For the Future we could use a Compiler inside nodeos and compile them at runtime to this things if im right?
