### ISSUE TITLE
Request for comments

### ISSUE THREAD

**Issue by d3x0r** [NodeOS/NodeOS#396]
I just released a package https://www.npmjs.com/package/sack-gui
which is the first package that I would like to add to NodeOS.  It removes the need for a LOT of other projects....

**Comment by d3x0r** [comment]
Not really closed... open for comment.

**Comment by luii** [comment]
What exactly is this project that you've proposed here?
I would like to know more about it.

**Comment by d3x0r** [comment]
What I would like to get eventually is intel to support the vulkan without_X flag... and have a javascript driven gui/system....
It's hard to justify a GUI for Node when there's already the browser......
