### ISSUE TITLE
sudo docker -t -i nodeos/nodeos error

### ISSUE THREAD

**Issue by yasuoganliang** [NodeOS/NodeOS#400]
[yujinsheng@haha ~]$ sudo docker run -t -i nodeos/nodeos
mount procfs: Operation not permitted
mount devtmpfs: Operation not permitted
Trace: { Error: EPERM, Operation not permitted 'overlay'
    at Error (native) errno: 1, code: 'EPERM', path: 'overlay', syscall: 'mount' }
    at onerror (/lib/node_modules/nodeos-boot-multiUser/server.js:23:11)
    at /lib/node_modules/nodeos-boot-multiUser/server.js:46:26
    at /lib/node_modules/nodeos-boot-multiUser/lib/index.js:97:24
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:198:24
Starting REPL session

[root@haha ~]# docker run -t -i nodeos/nodeos
mount procfs: Operation not permitted
mount devtmpfs: Operation not permitted
Trace: { Error: EPERM, Operation not permitted 'overlay'
    at Error (native) errno: 1, code: 'EPERM', path: 'overlay', syscall: 'mount' }
    at onerror (/lib/node_modules/nodeos-boot-multiUser/server.js:23:11)
    at /lib/node_modules/nodeos-boot-multiUser/server.js:46:26
    at /lib/node_modules/nodeos-boot-multiUser/lib/index.js:97:24
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:198:24
Starting REPL session
NodeOS-boot-multiuser>

**Comment by piranna** [comment]
As said in other issues, Docker images needs to be executed with some extra flags to allow it to access `/dev/fuse` device and mount OverlayFS filesystems, so correct way to execute it is with `npm start` from source code, that already has the flags. Pull-requests to set this flags by default in the Dockerfile or improve documentation regarding this topic are welcome.

**Comment by yasuoganliang** [comment]
ok
