### ISSUE TITLE
Please delete this repository immediately

### ISSUE THREAD

**Issue by salvadorp2001** [NodeOS/NodeOS#402]

**Comment by luii** [comment]
Why?

**Comment by blinkdog** [comment]
Why doesn't anybody open useful and insightful issues like these on my repositories?

**Comment by vitkarpov** [comment]
👆true story, bro! High five!
пт, 6 апр. 2018 г. в 8:45, Patrick Meade <notifications@github.com>:

**Comment by piranna** [comment]
I admit first time I found something similar to this I got it really personal, but now I'm taking a more Zen-like mindset: ignore it, don't feed the troll, and report abuse to Github administrators to take the correct action and close its account :-) That's funny to be sometimes a BOFH... :smiling_imp:
