### ISSUE TITLE
About documentation and website

### ISSUE THREAD

**Issue by rbecheras** [NodeOS/NodeOS#403]
Hi guys !

I just discovered NodeOS ! Its amazing you guys all rocks!

I hope I will help you for development and documentation; and the French translation too (because I'm French).

But I don't understand, where is the source of the node-os.com website ?

First I searched the NodeOS org's repositories for a repository looking like "nodeos.github.io" or "www" or "docs"... but I didn't find any.

Then I browsed the NodeOS/NodeOS repository to find a "docs" branch or a "docs" folder.

I found the docs folder and it looks like the source for the website but weirdly the published docs on the website is more up to date than the source in nthe docs folder...

For example, the page "Using-precompiled-Binaries" exist on the website (http://node-os.com/docs/Using-precompiled-Binaries.html) but not in the docs folder of this repo.

And the markdown file for the sidebar is not filled by a link for that page, but the item exist (https://github.com/NodeOS/NodeOS/blob/master/docs/_Sidebar.md)

So, what it the trick ?

How can I contribute for submiting PRs for the website docs ?

Finally, is there a dedicated team for French translation who I need to talk about before starting to submit PR ? Or I can just submit my PRs ?

**Comment by luii** [comment]
@rbecheras sorry to answer so late i thought someone had answered this question.
Someone on our Team has made the website and its laying somewhere on a repository in his account.
If i find it i let you know right away!

**Comment by luii** [comment]
Here you go: [joshgarde/nodeos.github.io](https://github.com/joshgarde/nodeos.github.io/tree/v2)

**Comment by rbecheras** [comment]
Ok thanks!

But why not https://github.com/NodeOS/nodeos.github.io ?

**Comment by luii** [comment]
Its actually the link you had posted, it has all the commits merged in from joshgarde's repo.

**Comment by rbecheras** [comment]
Ok thank you very much.
I close the issue now.
