### ISSUE TITLE
Issue / Feature / Pull-Request Templates

### ISSUE THREAD

**Issue by luii** [NodeOS/NodeOS#405]
@piranna It would be good to structure issues with a template, if you're don't against it i'll prepare a template for opening a issue.

**Comment by piranna** [comment]
It's ok for me. What do you have in mind?

**Comment by luii** [comment]
If someone has an problem with the installation or build process and opens a issue, that you need to specify the versions, operating system and some other things alongside with the log of the build process.
It's a bit irritating if you need to ask every time you have a new issue like #404. 
It's clearer for us what we have to do and what problem it could be.

Some possible questions:

- Operating System
- Node version (installed locally)
- NPM version (installed locally)
- NodeOS version (downloaded)
- Platform (either qemu, docker, raspi, etc...)

if its a custom build would be good to know if the user uses a custom usersfs, barebones, etc
- Custom Usersfs / Barebones / Software / etc...

**Comment by bogdanbiv** [comment]
Expected / Actual as separate items could also be useful for focusing on the problem.

**Comment by luii** [comment]
@bogdanbiv Already did it in #406
