### ISSUE TITLE
Command ls causes logout

### ISSUE THREAD

**Issue by bogdanbiv** [NodeOS/NodeOS#407]
Using luii's proposed template from #405:

1.     Operating System: Manjaro Linux (Arch Linux based)
     Node version (installed locally): v10.2.0   -- Would NodeOS work under nvm?
     NPM version (installed locally): 6.1.0  -- perhaps nvm could also help me from downgrading NPM
     NodeOS version (downloaded): NodeOS@1.0.0-RC3 (latest, fresh git checkout)
     Platform (either qemu, docker, raspi, etc...): QEmu, built via `npm run build`

2.     Screenshots: https://i.imgur.com/p34GP3L.png ![screenshot_20180601_204814_ls_causes_logout](https://user-images.githubusercontent.com/104334/40856527-e4e21d7c-65e0-11e8-9ec3-373cb979c921.png)
3.     How to reproduce:
3.1        npm run build
3.2        npm run start
3.3        wait for NodeOS shell
3.4        login with nodeos / nodeos
3.5        commands that work: env, echo, pwd, man, npm search
3.6        type ls -> events.js:160 -> Unhandled 'error' event
4.     describing the bug: ls causes and error which is not handled, causes logout
`Error is 'TypeError: Invalid non-string/buffer chunk' /bin/getty exited with code 7`

OCR'ed from the screenshot linked above (and corrected manually):
```
> ls 
events.js:160 
  throw er: // Unhandled 'error' event 
  ^
  
TypeError: Invalid non-string/buffer chunk 
at chunkInvalid (_stream_readable.js:393:10) 
at readableAddChunk (_stream_readable.js:148:12) 
at WriteStream.Readable.push (_stream_readable.js:134:10) 
at emitOne (euents.js:96:13) at Domain.emit (euents.js:188:7) 
at Domain._errorHandler (domain.js:97:23) 
at process._fatalException (bootstrap_node.js:293:33) 
at Domain._errorHandler (domain.js:124:26) 
at process._fatalException (bootstrap_node.js:293:33) 
bin/getty /bin/logon: "/bin/getty" exited with code 7 Welcome to NodeOS!: username:
```

**Comment by luii** [comment]
Duplicate #397 use the `/bin/ls` instead
