### ISSUE TITLE
Mobile OS

### ISSUE THREAD

**Issue by laurensiusadi** [NodeOS/NodeOS#431]
I have an idea to develop NodeOS into a Mobile OS that runs on smartphones, and apps that's written in JS will run on it, or use PWA (Progressive Web Apps - that currently install-able on android). So the world have another option besides Android, iOS, and Kai OS, etc. An OS which is privacy-focused, monopoly-free (because Google controls everything), and totally open-source.

Since JS (PWA) will run on the OS, current web developers can develop their app or web apps just straight working. So the app ecosystem shouldn't be a problem (like Windows Phone had).

Any thoughts?

P.S. I'm a front end JS developer that don't know shell/linux coding. I can do UI/UX too.

There's some discussion on #114 but that was years ago.

**Comment by asdf23** [comment]
Are you familiar with Firefox OS it was a fully working html/js OS . Mozilla killed our but I believe it lives on. Ory was an amazing OS but just needed more

**Comment by laurensiusadi** [comment]
I didn't know that. Definitely will check Firefox OS, and see why it fails and what can be done.

**Comment by laurensiusadi** [comment]
I've heard of KaiOS before, but didn't notice they're using HTML, CSS, and JS for their apps.
To my surprise, it is forked from FirefoxOS B2G.

**Comment by RossComputerGuy** [comment]
FirefoxOS failed because it didn't have native application support so nobody could develop resource demanding apps or anything that needed to be written in a lower level language. Here's a video from TechAltar explaining it better: https://www.youtube.com/watch?v=YA-Enxfhl0E

**Comment by asdf23** [comment]
it failed for two reasons:

1) mozilla pulled the plug and did not support ( no build instructions,
bizarre hard to get phones, $)

2) it was too open. I could take any game copy it, hack it which scared off
some. And I'm convinced big brother which is largely in control of the
mobile area didn't want this taking off

**Comment by laurensiusadi** [comment]
> 
> 
> FirefoxOS failed because it didn't have native application support so nobody could develop resource demanding apps or anything that needed to be written in a lower level language. Here's a video from TechAltar explaining it better: https://www.youtube.com/watch?v=YA-Enxfhl0E

Just watched it, just now, before checking github.

Now I'm curious if KaiOS could be made on better phones ($100-$200) instead of their current line up ($17-$100)
