### ISSUE TITLE
Can't run any commands.

### ISSUE THREAD

**Issue by Stanlyhalo** [NodeOS/NodeOS#436]
So I installed the x86_64-pc-iso.zip, than I unzipped it, and I ran a command through Windows PowerShell and got it to open with qemu, it loaded the OS in the terminal, but when it came to run a command like "ls", it gave me an error. I'm currently at school sadly, but as soon as I get home, I'll take a screenshot and post it.

**Comment by RossComputerGuy** [comment]
Duplicate of #397

**Comment by Stanlyhalo** [comment]
It never asks me to login, and the error as I recall from my memory was different.

Edit*: While I'm at school, can someone send the steps to correctly use NodeOS in Windows 10 (using qemu), because idk if theirs a problem with mine, I'll reply in about 2-3 hours.

**Comment by Stanlyhalo** [comment]
Sorry I'm getting back so late, but this is what I get:
![image](https://user-images.githubusercontent.com/36088749/76590644-14d65f00-64ab-11ea-9d78-5179d5b71e86.png)

**Comment by Stanlyhalo** [comment]
This is the command I have to run to run it in qemu: "qemu-system-x86_64.exe -boot d -cdrom D:\nodeos\bootfs.iso -m 512"

Edit*: I also did try to download the github repo and do "npm start", but I get an error saying " 'scripts' is not recognized as an internal or external command".

**Comment by Stanlyhalo** [comment]
I'm gonna close this to instead use the downloaded github repo so I can modify it.
