### ISSUE TITLE
Problems trying to use github repo in Windows 10.

### ISSUE THREAD

**Issue by Stanlyhalo** [NodeOS/NodeOS#437]
I'm using Windows 10 Home, and I am trying to use NodeOS for Windows 10 from the github zip download. I unzipped it and now I'm trying to use it, first I did "npm install", their were a lot of red errors, but I'm pretty sure it might be okay (idk, it made a log file), but when I do "npm run build", it throws: " 'scripts' is not recognized as an internal or external command".

**Comment by Stanlyhalo** [comment]
I put "node" before it says "scripts/build" in the build key of scripts in the package.json. But I get a new error: 
#!/usr/bin/env bash
^
SyntaxError: Invalid or unexpected token

Edit*: Should I try making my NodeOS custom os in a linux os?

**Comment by RossComputerGuy** [comment]
You have to run the scripts under Linux, bash scripts don't work in PowerShell and Window's cmdline.

**Comment by Stanlyhalo** [comment]
Aw man, time to make my windows machine dual boot then.

**Comment by RossComputerGuy** [comment]
You could just use a VM.

**Comment by Stanlyhalo** [comment]
Btw I ended up just using Ubunto WSL.
