### ISSUE TITLE
GUI Support

### ISSUE THREAD

**Issue by Sant268** [NodeOS/NodeOS#438]
Hello,
I'm interested about this project, and so I wanted to ask if there is any ongoing efforts to build a GUI for this OS.

**Comment by piranna** [comment]
NodeOS is mostly a server-only OS, but there was some effort to provide it a client-server architecture GUI based on web technologies (http + websockets). Take a look for oneshoot and nodeos-reverse-proxy projects.

For a single-head configuration where the GUI is in the same machine were NodeOS is running, there was some tries to compile and run chromium_shell directly on top of Linux KMS/GDI, but it was somewhat complicated. Some time ago I read about some advances done by Intel where it was possible to watch Youtube videos and have normal web usage, so would it be nice to give it another try. Pull-requests are welcome :-)

**Comment by Sant268** [comment]
> NodeOS is mostly a server-only OS, but there was some effort to provide it a client-server architecture GUI based on web technologies (http + websockets). Take a look for oneshoot and nodeos-reverse-proxy projects.

I'll try to hack together a GUI, nice little task ;)

**Comment by piranna** [comment]
> I'll try to hack together a GUI, nice little task ;)

There was some conversations about providing support for https://www.os-js.org/, being served by NodeOS and accessing to its files using WebDAV. Before starting your own GUI, please take a look on this path.

**Comment by Sant268** [comment]
> > I'll try to hack together a GUI, nice little task ;)
> 
> There was some conversations about providing support for https://www.os-js.org/, being served by NodeOS and accessing to its files using WebDAV. Before starting your own GUI, please take a look on this path.

Sure! Thank you for your insight, but it's just that I've been following this project silently for some years, and I've just got confident enough to contribute :) 
I just wanted to pay something back to the community

**Comment by Rubix982** [comment]
Looking forward to looking at your pull request, @Sant268 . I just saw this repo last December, and I got really intrigued with the idea, but haven't made any contributions towards it myself. 
Would really like to see how implement a GUI for this and they stuff you might use. 
Cheers!

**Comment by piranna** [comment]
> I just wanted to pay something back to the community

Documentation and keep updated libraries and services are another useful tasks and would help you to understand it better, not everything is just coding :-)


> Would really like to see how implement a GUI for this and they stuff you might use.

Take a look at the conversation at https://github.com/os-js/OS.js/issues/742, probably will give you some ideas.
