### ISSUE TITLE
Javascript was a mistake

### ISSUE THREAD

**Issue by soldatami** [NodeOS/NodeOS#442]
examine what you're doing

**Comment by piranna** [comment]
Reported and blocked due to harrasment.

**Comment by stoneRdev** [comment]
Blocking is a good move.
If I may quote #Hacktoberfest from https://hacktoberfest.digitalocean.com/ :
"
Hacktoberfest® is open to everyone in our global community. Whether you’re a developer, student learning to code, event host, or company of any size, you can help drive growth of open source and make positive contributions to an ever-growing community. All backgrounds and skill levels are encouraged to complete the challenge. 
"

But more specifically, this:
" ...and make positive contributions..."

This does not mean going around making headaches for developers. We work hard. Too hard to have to deal with script kiddies thinking its okay to use a public event meant for "...positive contributions..." to destroy or degrade someones hard work.

@qorg11 , until you shape up, I hope you never get that free T-shirt.
