### ISSUE TITLE
Get Involved blog post should be a wiki page

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#54]
<a href="https://github.com/balupton"><img src="https://avatars.githubusercontent.com/u/61148?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balupton](https://github.com/balupton)**
_Wednesday May 28, 2014 at 13:05 GMT_
_Originally opened as https://github.com/NodeOS/NodeOS-Docker/issues/8_

----

Having your documentation on the blog is confusing, as it screams "is this still up to date?". Would be great to have all NodeOS documentation on the NodeOS github wiki (which appears to be disabled)

**Comment by lite20** [comment]
New wiki being put together!
