### ISSUE TITLE
npkg install bin-ncurl failed

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#60]
<a href="https://github.com/fbukevin"><img src="https://avatars.githubusercontent.com/u/4548874?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fbukevin](https://github.com/fbukevin)**
_Thursday Sep 11, 2014 at 10:02 GMT_
_Originally opened as https://github.com/NodeOS/NodeOS-Docker/issues/14_

----

I was doing the second exercise on my machine - Ubuntu 14.04 LTS, x64.
My docker version is 1.0.1 , node version  is v0.10.31.
But I got npm ERR with following messages：

```
/ # npkg install bin-ncurl
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm http 504 http://linux-x86.node-os.com/bin-ncurl
npm ERR! registry error parsing json
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm http 504 http://linux-x86.node-os.com/bin-ncurl
npm ERR! registry error parsing json
npm http GET http://linux-x86.node-os.com/bin-ncurl
npm http 504 http://linux-x86.node-os.com/bin-ncurl
npm ERR! registry error parsing json
[SyntaxError: Unexpected token <
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.5.0</center>
</body>
</html>
]
/ # 
```

**Comment by zedtux** [comment]
In the end, is there any workaround for this issue ?

**Comment by piranna** [comment]
Currently no, first we need to re-enable network support, so npm can work from inside NodeOS. Also there's the problem with compiled modules, but maybe if the cross-compiler can be moved to an independent package so we could have a build toolchain and by using some of the alternatives to gyp that don't depend on Python, maybe node-gyp could work. Until that happens, there's no workaround, sorry :-(

**Comment by zedtux** [comment]
So if I understand correctly, as the `npkg` command doesn't work based on what you said, it's not possible to install other commands than the one installed, or is there an alternative to `npkg` (like `npm` directely) ? (Limiting the interest and fun on NodeOS ;))

**Comment by trisys3** [comment]
`npm` doesn't seem to be working, either.  I'm on `Boot2Docker` on Windows, but other images, like the Ubuntu one, go on the Internet so it's not my setup.

**Comment by piranna** [comment]
There's no network support currently and we need to re-enable, it's in the shorterm roadmap (but any help is greatly welcome!!!). You can be able to add the packages you want to install to the ```packages.txt``` file at ```node_modules/nodeos-usersfs``` package, so the next time you build NodeOS they will be included.

**Comment by lite20** [comment]
closing as npkg is depricated.
