### ISSUE TITLE
Universal GUI for Command Line apps and installers

### ISSUE THREAD

**Issue by TheJaredWilcurt** [NodeOS/NodeOS#68]
**EDIT**: http://github.com/TheJaredWilcurt/UGUI

Something I've always wanted to see from the Linux community is a Universal GUI that can act as a skin for command line based programs. There are so many great tools that come out that experts use that take years to get a GUI (if they ever do). Here's my proposal.

GUI libraries are often too cumbersome to spend time on implementing and they take time away from developing the actual tool itself (adding features and fixing bugs). What we need is a GUI system that everyone already knows how to work with. The obvious choice is HTML/CSS. With Node-OS, we already have a great JS environment that we can use to layer HTML/CSS on top of to act as the interface for command line applications.

This UGUI (Universal GUI) could have Webkit or Gecko at it's core, and allow a basic API to send commands to the terminal via form elements on the page, and then handle the returned values, wrapping them in tags and inserting them in to the DOM.

Setting it up this way means that front end designers who are used to the HTML/CSS world can participate and take care of the GUI quickly and easily, leaving the developers of the CLI part to work on bugs and features.

If this could be created, I think it would really open up not just Node-OS to a wider audience, but Linux in general (so long as you have Node installed presuming it's the prerequisite).

Also, this could be used for installing packages without the need to type "npm install grunt". I know it's 3 words, and npm install is awesome, but this same concept described above could be used to for an installer GUI, something the Linux community has been severely lacking in.

**Comment by lite20** [comment]
Safe to close this as inactive?

**Comment by TheJaredWilcurt** [comment]
yes
