### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by zwhitchcox** [NodeOS/NodeOS#76]
Could someone please give me idiot-proof instructions? The README file did not work for me. This is what I did:

Install Docker
```Shell
git clone https://github.com/NodeOS/NodeOS
cd NodeOS
sudo docker run -t -i nodeos/nodeos
```

And I get the error: 
```Err
2014/11/01 15:33:26 Post http:///var/run/docker.sock/v1.15/containers/create: dial unix /var/run/docker.sock: no such file or directory
```

**Comment by lite20** [comment]
Closing this thread, as docker progress has begun and is being monitored on other threads.
