### ISSUE TITLE
What to do with io.js?

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#87]
Recently it has showed a Node.js fork that's getting a lot of traction, what we should do here (specially with the name of the project :-P)?

https://github.com/iojs/io.js

**Comment by netlovers** [comment]
With the beta(?) release of io.js (https://iojs.org/) it looks like some big projects already started using it instead of node. For example node-webkit:
https://groups.google.com/forum/#!msg/nwjs-general/V1FhvfaFIzQ/720xKVd0jNkJ
It is nw.js from now on.

**Comment by piranna** [comment]
There are some problems with compiled modules due to the updated v8 engine,
and NodeOS depend too much on them. In fact, @netlovers has had a hard time
updating them to Node.js 0.11.x... No, we are not moving to io.js soon, at
least until this issues get fixed, and honestly I hope (as a lot others)
that both projects get reunited, because if not compatibility problems will
go to worse :-(

**Comment by leukhin** [comment]
I think io.js over time will go even further, so distance between io.js and NodeOS will be longest eventually.

**Comment by piranna** [comment]
> I think io.js over time will go even further, so distance between io.js and NodeOS will be longest eventually.

That would be a shame... :-( but until that, it's better to wait
before doing the jump (at least until current alpha version is
released), and I would do it in a branch to see how different they
are. The implications of changing the runtime are huge...


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by leukhin** [comment]
@piranna I think it is the right point

**Comment by piranna** [comment]
:+1:

**Comment by piranna** [comment]
https://platzi.com/blog/node-js-convergence/

Node.js & io.js will join efforces to create a neutral foundation that will administer the development of a joined project that in the long term will replace both of them and will have all the improvements done in the last 6 months separatelly and that will be released as Node.js 3.0 (since io.js is already at the 2.0.1 version). Now that this point is clear I will close this issue since it's not needed anymore :-)

(Sh*t, I liked _[something].js_ as project name... :-P )
