### ISSUE TITLE
Pre-compiled binary modules

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#93]
Use [node-pre-gyp](http://cylonjs.com/blog/tags/node-pre-gyp/) to generate and host pre-compiled binary modules so install of NodeOS can be faster (not all the people want to spend 1.5 hours just to do a quick test of the system...) and also help on install of binary modules until we are able to make NodeOS self-hosted.

**Comment by cethap** [comment]
Enviado desde mi smartphone BlackBerry 10.lioJJjd                                                                                                                                                                                                                                         De: Jesús Leganés CombarronlCombar rollo melk hFkc4j‎DIuEnviado: lunes, 26 de enero de 2015 04:37 jIdo al Lxa.m.Para: NodeOS/NodeOSx// r=«±‎Responder a: NodeOS/NodeOSAsunto: [NodeOS] Pre-compiled binary modules (#93)Use node-pre-gyp to generate and host pre-compiled binary modules so install of NodeOS can be faster (not all the people want to spend 1.5 hours just to do a quick test of the system...) and also help on install of binary modules until we are able to make NodeOS self-hosted.

—Reply to this email directly or view it on GitHub.

**Comment by piranna** [comment]
Done in master using `prebuild-install` instead, clossing.
