### ISSUE TITLE
Confused about workflow during boot

### ISSUE THREAD

**Issue by ayusun** [NodeOS/NodeOS#97]
I am pretty new to OS Development. Although I do have some theoretical concepts but that's theoretical and I am pretty much confused here. Although doc does help. But still it would be of help o actually understand how the entire booting process occur.

So, I know, that first kernel boots, which looks for initrd/initramfs(in our case) which then run init. Then mount root file system and then some daemons and then user filesystem.

* In Node OS , I found that in barebones linux kernel and node.js is present. Now there are two files first is config and other is cpio.txt

Now

    CONFIG_INITRAMFS_SOURCE="cpio.txt"
and in Cpio.txt there is a line that says
   
     slink /init bin/node 0100 0 0

Now, I was following some resources online to understand how things work and i stumbled on this

    http://landley.net/writing/rootfs-howto.html
According to the resource, we are using the third way by using a text file and we are making node.js as our /init.

In this case, aren't we jumping from kernel loading to running init directly. But according to resource first it should unzip the initramfs.cpio.gz in Node Os- initramfs and then run init(I saw there is one init.js). So I want to know how Actually are we moving from level-1 to level-2.

* Now, in node_modules>century we have a readme that says century is supposed to be pid 1. Isn't init is pid 1

* init.js expects an argument (code uses argv), so what kind of arguments are we supplying to it.

* In init.js, I inserted a console.log in between the code(before log function), just to see at which moment init.js starts executing, but i couldn't find it anywhere during boot time.(i tried consol.log("-----") there were too many ----, Easily noticeable) 

Well these are the few question from Level 1 and 2.

By the way, the following questions are not related to Level but about Node OS in general

* Why Node OS, seems to be so slow, It takes about 46 secs to run forever and then waits for about good 40-50 secs and then prompts for username. Moreover, the execution of commands also seems a bit delayed. Like if I try ls, it takes about 1-2 secs and then returns the result. Is it my problem or the behavior in general.

* I have never used QEmu, so don't really know how it works. But I saw start script in Scripts folder. And there are various arguments that we provide like linux kernel image, initramfs images, rootfs image. So are we supposed to provide all these. Or just the location of linux kernel will do.

I am trying to create a map on how things are happening and may post some more doubts in the future on the workflow.

**Comment by piranna** [comment]
> So I want to know how Actually are we moving from level-1 to level-2.

Quoting the link you provided,

> An external initramfs archive is extracted after the kernel's built-in archive, so if the two contain any of the same files the external archive should overwrite the built-in one.[5] This means you can update or customize rootfs without replacing your kernel.

When giving an external initramfs, it will overwrite the one included in the kernel, and in fact it will overwrite the /init link to point to century as PID 1 instead of to Node.js binary.


> init.js expects an argument (code uses argv), so what kind of arguments are we supplying to it.

The executable to exec after itself. Pretty usual /init behaviour.


> Why Node OS, seems to be so slow, It takes about 46 secs to run forever and then waits for about good 40-50 secs and then prompts for username. Moreover, the execution of commands also seems a bit delayed. Like if I try ls, it takes about 1-2 secs and then returns the result. Is it my problem or the behavior in general.

It should not be so slow. Make sure you are using KVM on your system.


> And there are various arguments that we provide like linux kernel image, initramfs images, rootfs image. So are we supposed to provide all these.

Obviously, yes.

**Comment by ayusun** [comment]
Thank you for your comment. Sorry if it may seem a little naive , but I would like a little more clarification.

So, when the kernel starts, it reads the cpio.txt, in which the slink line makes node.js binary as init and at the same time starts its execution. Now kernel then extracts the contents of the initramfs.cpio.gz and replaces init. Right?(And in some article somewhere I did read that kernel looks for some known location like sbin for the init file.) How the kernel actually finds this initramfs.cpio.gz file.

Because to nodeos-barebones, the path to initram.cpio.gz is ../nodeos-initramfs/initramfs.cpio.gz. So how does it find this file. 

I hope I am clear this time.

Regarding, Speed. Ok its KVM problem. Yeah, I was having a problem and i was advised to comment out that argument. Ok I will install it 

Thanks :)

**Comment by piranna** [comment]
Kernel first de-compress both initramfs images, and after that exec /init, not before. Kernel find it because we are telling him where to find it on the boot arguments.

**Comment by ayusun** [comment]
Ok, now its bit clear.

So you mean to say the arguments that we provide in npm start actually works in finding initramfs.cpio.gz.(the one referring to qemu-system-i386(x86_64) [args]). Is it because of this?

If yes, then exactly at what moment node binary starts executing. It has to start before init starts executing.

Thank you again for being so patient with these questions :)

**Comment by piranna** [comment]
> So you mean to say the arguments that we provide in npm start actually works in finding initramfs.cpio.gz.(the one referring to qemu-system-i386(x86_64) [args]). Is it because of this?

Yes, that's it.


> If yes, then exactly at what moment node binary starts executing. It has to start before init starts executing.

/init is carfted in Javascript, so it's executed automatically

**Comment by ayusun** [comment]
Yeah, I didn't had this idea that individual arguments are passed and on that basis the emulator runs. I was under the impression that linux kernel automatically finds the entire thing and boots up. We are supposed to pass an argument.

Just now, I tried running qemu by passing all those arguments step by step and it seems to have cleared everything.

Thanks again. I will be grazing over the entire code base once to see how the rest of the things are working.
