### ISSUE TITLE
A dummy question

### ISSUE THREAD

**Issue by Cyrillius** [NodeOS/NodeOS#98]
Hello!

I am a student in embedded system. I think your project is really interesting but I don't really understand why you want to use a linux kernel. Linux is allready an operating system  and add a lot of things that the v8 javascript engine doesn't need. We can just implement only what we need and get all the cpu ressources for Node.js.

![image](https://cloud.githubusercontent.com/assets/7454018/6094037/7710a318-af18-11e4-9247-a5b687043916.png)

Instead to use a software timer we can use an hardware timer and we don't need a scheduler Node.js is single thread (I think).

**Comment by piranna** [comment]
> Linux is allready an operating system

Linux is NOT an operating system, it-s just a kernel, the same way as mach or Xnu or KernelNT.exe are the kernels of FreeBSD, MacOS X or Windows. A Linux OS is a Linux kernel based OS, that-s being Ubuntu, Fedora, Android, FirefoxOS, ChromeOS... or NodeOS ;-)

As you pointed out, we could remove Linux and use Node.js baremetal, but we would need to add some basic baremetal functions for example by using newlib, and the only advantage over runtime.js (the project where you took the diagrams) is the Node.js APIs, that is already on their roadmap.


> Instead to use a software timer we can use an hardware timer and we don't need a scheduler Node.js is single thread (I think).

Node.js and Javascript are single-threaded from a programmer point of view, but internally they are multithreaded and Node.js devs are working on making it multi-process.
